== Preface.

The following sheets exhibit a plain man`'s undisguised
account of his own progress in religion:
an artless narrative of his sincere and hearty endeavours, as much as in him lay,
to promote the doctrine of the Gospel of Christ in the earth.

The motives inducing him to undertake the office of a preacher,
appear to have been perfectly consonant to the precepts of Holy Scripture,
and to the practice of Christ and his apostles, namely:

[.numbered]
1st. A clear, cogent, and convincing evidence of a Divine call,
and heavenly impulse thereunto.

[.numbered]
2nd. An indispensable sense of his duty necessarily
obliging him to yield obedience to that call.
And

[.numbered]
3rd. The sweet returns of inward peace and Divine
consolation accompanying his obedience therein,
greatly conduced to his confirmation and perseverance in the way of his duty.

To the performance of this he found himself measurably prepared and qualified;
for his own experience of the love of God, and of the operations of his holy Spirit,
in gradually purging out the corruptions of his own heart,
did excite and augment in him a Christian love to his fellow creatures,
attended with an ardent zeal, and an incessant desire for their conversion.

An inward purgation from sin is a necessary and essential
qualification of a Gospel minister;
and no man can be such without it;
for God does not send unclean messengers on his errand:

It is the constant method of his Divine wisdom, under this Gospel dispensation,
through the purging of his holy Spirit,
to cleanse and purify the inside of every vessel which he
permits to be made use of in the service of his sanctuary.

Every unsanctified person who pretends to preach the Gospel of Christ,
should consider that unanswerable query of our blessed Saviour to the Pharisees of old;
"`O generation of vipers, how can you, being evil, speak good things?
for out of the abundance of the heart the mouth speaks.`"

A practice of this nature is condemned, even in the time of the Mosaic Law,
by the royal psalmist, in these words: "`Unto the wicked, God says,
What right have you to do to declare my statutes,
or that you should take my covenant in your mouth?`"

But alas! self-interest prompts men to turn a deaf ear even to Divine expostulations,
and unholy persons, in despite of the most express prohibitions,
continue to intrude themselves into holy things;
and to be busying themselves about external circumstances and ceremonies, while the life,
spirit, and substance of true religion is unattainable by them,
until it shall please God, in the exceeding riches of his grace,
to cleanse their hearts from all unrighteousness; for which conversion we heartily wish.

The author of the ensuing narrative was another sort of preacher;
a free giver of what himself had freely received,
a liberal and openhearted communicator of his religious experiences,
without respect to persons.

He directed the sheep of Christ to follow the voice of Christ himself, the good Shepherd,
whose omnipresence renders his voice audible to every one of his sheep,
however separate or dispersed throughout the world.

His conversation was free, generous and affable;
neither did he shun the society of those whom he was sent to convert;
his mission being somewhat correspondent to that of his Lord and Master,
who declared concerning himself; "`I am not come to call the righteous,
but sinners to repentance.`"

He was of a grave deportment, and of a tall, comely and manly aspect.
His public preaching was attended with Divine authority and innocence,
which commanded the attention of the hearers; and his voice being clear,
strong and distinct,
was capable of conveying his exhortations to the
ears and understandings of a very numerous auditory;
of which a remarkable instance appears in his preaching at Jedburg, in Scotland,
mentioned in his account.

His literary accomplishments were but small,
extending little further than to enable him to read the Scriptures in his mother tongue;
yet by constant use and application, he became thoroughly versed therein,
and was enabled by the force of their testimony,
to confront and confute the gainsayers of his doctrine,
which was in all points strictly agreeable to and consonant therewith.

In the religious Society to which he was joined,
he conducted himself as a man of peace and prudence,
choosing to walk in the plain and middle path, without declining to any extreme:
so that he neither idolized forms, nor contemned good order.

His estimation and repute among his friends and neighbours,
will appear by the testimony of the Monthly and Quarterly Meetings of Bridport,
in Dorsetshire, to which he belonged, given forth since his decease, wherein they say,
that "`It pleased the Lord to endue him with a large gift in the ministry,
in which he was a faithful labourer, and gave himself up for that service;
that he had a gift of utterance superior to many, sound in judgment and doctrine,
and very convincing to the understandings of those who heard him.`"

This testimony concerning him is true,
and a man of his penetration and capacity could not but
discern his own improvement in the gift he had received.
He therefore stood upon his guard, lest through self-love and conceit,
he should depart from that humility, which is the ornament of every Gospel minister.

This Christian virtue was generally his concomitant, during the course of his pilgrimage;
and is remarkable in this account, keeping it clear from any tincture of self-applause.

In preaching, his declarations proceeded from his heart; and in writing,
his relations of his services and his exhortations, spring from the same fountain.

Wherefore we recommend to your serious consideration what he has written,
as comprehended in that excellent description of a good man, given by Christ himself:
"`A good man, out of the good treasure of his heart, brings forth that which is good.`"

May the good brought forth out of this good man`'s heart effectually reach unto yours,
and through the Divine blessing operate to your spiritual
benefit and improvement in that which is good.

So shall the design of the deceased author,
in leaving behind him this account of his life and travels, be in some degree answered,
and the writer of this preface shall have the end he aims at;
who with sincere desires for the saving health and welfare of all mankind,
takes his leave, and bids them heartily farewell.

[.signed-section-signature]
J+++.+++ Besse.
