== Chapter I.

I was born in Westmoreland, within the compass of Great Strickland Monthly Meeting,
about the year 1676, and was entered in that register.
My father died before I was one month old;
but I have been informed that he was very honest and zealous for truth in his time,
having been a considerable sufferer for the cause of religion,
both in loss of goods and liberty,
the meeting being kept in his house in some of the hottest
times of persecution in King Charles the second`'s reign.
Being left so young,
and my mother having but a scanty subsistence of
about four pounds and ten shillings a year,
with a dwelling for herself and two children,
at about thirteen years of age I was put to learn the trade of a blacksmith,
with an uncle who used me unkindly.
I was afterwards placed apprentice to a very honest Friend belonging to Brigflatts meeting,
near Sedbergh in Yorkshire, whose name was Samuel Parrot.
All this time I had no taste of religion, but devoted myself to pleasure,
as much as my circumstances would permit,
though my mother had kept me very strictly while I was under her care.
She would frequently in winter evenings take opportunities
to tell me passages of my dear father`'s sufferings,
admonishing me so to live,
that I might be worthy to bear the name of so good a man`'s son,
and not bring a reproach on myself and parents: also putting me in mind,
that if she should be taken away,
I should greatly miss her both for advice and other ways to assist me;
and advised me to fear the Lord now in my youth,
that I might be favoured with his blessing.
These admonitions at times brought me into great tenderness,
being afraid that she would die before I was capable to live in the world;
and she took me frequently to meetings with her,
where she often had some words in testimony.
Persecution being still very hot,
and Friends locked out of their meetinghouse at Strickland, we met at the door,
and I remember when I was a child, and went to meeting with my mother,
the informers came twice; the first time the meeting had been over about half an hour,
the second time not quite so long, so that we escaped their hands both times.
Many Friends were in prison at Appleby for attending that meeting,
whom my dear mother went to visit, taking me along with her,
and we had a meeting with the prisoners,
several Friends from other places being likewise there by appointment.
I observed, though very young, how tender and broken they were;
and I was very inquisitive of my mother, why they cried so much, and you too, said I,
why did you?
She told me that I could not understand the reason of it then,
but when I grew up more to man`'s state I might.

To return to my apprenticeship; I had a very kind loving master and mistress,
but who had little consideration about religion, nor any taste thereof.
On first-days I frequented meetings, and the greater part of my time I slept,
but took no account of preaching, nor received any other benefit,
than that being there kept me out of bad company,
which indeed is a very great service to youth.
I took much liberty in discourse, and was taken notice of as a witty, sensible young man:
but often on my bed I reflected on my way of life with sorrow,
yet frequently fell into the same way again.
I never was given to swearing, nor to any very gross vice, but what I gave way to most,
was jesting, and turns of wit to provoke mirth, which gave me often, after it was over,
a heavy heart.
Thus I went on for nearly three years; but one first-day, being at meeting,
a young woman named Anne Wilson, was there and preached.
She was very zealous, and I fixing my eye upon her, she, with a great zeal,
pointed her finger at me, uttering these words with much power; "`A Quaker by tradition,
you come to meeting as you went from it the last time, and go from it as you came to it,
but are no better for your coming; what will you do in the end?`"
This was so suited to my condition, that, like Saul, I was smitten to the ground,
but turning my thoughts inward, in secret I cried, Lord, what shall I do to help it?
And a voice as it were spoke in my heart, saying.
Look unto me, and I will help you; and I found much comfort,
which made me shed abundance of tears.
Then I remembered what my mother told me some years before,
that when I grew up more to man`'s state,
I should know the reason of that tenderness and weeping, which I now did to purpose.
I went home with a heavy heart, and could neither eat nor sleep as I used to do,
but my work never succeeded better in my hands than it did at this time,
nor was my mind ever less in it.

My conduct, as well as countenance, was much altered,
so that several in the family were fearful that I should fall into a kind of melancholy;
but I longed for the meeting day, and thought it a very long week.
When the time of meeting came, my mind was soon fixed and stayed upon God,
and I found an uncommon enjoyment that gave me great satisfaction,
my understanding being opened, and all the faculties of my mind so quick,
that I seemed another man.
A divine and spiritual sweetness abiding with me night and day, for some time,
I began to see and understand the Scriptures,
and the nature of preaching the doctrine of the Gospel in the power and spirit,
plainly seeing a difference between a preacher of the letter and of the spirit,
which till then I was wholly ignorant of, not having before that,
the least degree that I could perceive of Divine understanding.
But upon looking back and considering what I had heard such and such Friends preach,
which at that time I did not understand, I now understood it clearly,
which was a plain demonstration to me, that all saving knowledge is from Divine light,
which we cannot comprehend, until we are assisted so to do by a visitation from heaven.

Now the Scriptures and ministry from the openings of the Spirit,
seemed so clear and plain to my understanding,
that I wondered any body remained unconvinced,
supposing them to see the truths of the Gospel in the same light that I did.
That saying of the apostle,
wherein he asserts his knowledge of the Son of God being come,
to be by "`receiving an understanding from him,`" was clearly discovered to me,
so that I plainly saw a distinction between the children of light,
and the children of this world--the spiritual and the natural man;
and that the natural man could not receive the things of the Spirit of God,
being foolishness to him; he cannot know them,
because they are known "`only by the Spirit,`" as the apostle asserts;
and I found myself much improved in Divine wisdom and saving knowledge.
As I was going to meeting, walking alone, it came very livingly into my mind,
that if I was but faithful and obedient to the heavenly vision,
I should soon be qualified to teach others, and more especially,
as I saw by experience wherein my shortness had been,
in being contented and easy with a form of truth and religion,
which I had only by education, being brought up in plainness of both habit and speech;
but all this, though very good in its place, did not make me a true Christian;
I was but a Quaker by tradition, and that by education only, and not from the Scriptures,
because they were a book sealed to me.
And I now saw plainly, that education, though ever so carefully administered,
would not do the work; although a pious education ought by no means to be neglected,
but all parents and guardians ought to be stirred up to their duty in that respect;
yet we must consider, that it is not in the power of parents, or the most pious tutors,
to confer grace, which is the gift of God alone;
nor can any come into the true fold but by this door,
as said our Saviour concerning himself.

It plainly appeared to me, there was no other way but this:
by the "`Spirit of Christ alone,`" to attain to true faith, which works by love,
and gives victory over our infirmities and evil deeds, working such a change in us,
that we can in truth, from experience, say,
"`we are born from above;`" and by virtue of that birth only,
is the true knowledge of the kingdom, and the things of God attained,
and by no other way or means, although ever so well contrived by human art.
Being experimentally sensible of this change wrought in my mind,
it looked the more likely that I might, in time,
be qualified to speak to others of my own experience
of the operation of the spirit in my mind,
not thinking the time so near at hand, as it appeared when I came to the meeting;
for I had not sat long therein, when a great weight fell upon me,
with some words to speak; but I considered, being willing to be my own carver,
that it was too soon to undertake such a task, being but an infant in religion;
not remembering the small time between Paul`'s conversion and his preaching the Gospel: Acts 9:20.
My former conduct with my companions,
many of whom were in the meeting at the same time, also stood much in my way,
for my reformation was but three weeks old that very day, so that I concluded,
so sudden a change would hardly be borne.

I did not at that time, for these reasons, give up, and the burden was taken from me.
But after meeting it came upon me again with double weight,
and affected me so very greatly, that I was much alone,
and my countenance so altered with weeping,
that my master took occasion to inquire how it was with me.
I gave him as plain an account as I was capable of,
with which he was much affected and broken into tears.
I feared that I had by disobedience so much offended, that I should be cast off forever:
but, with exhortations from Scripture and otherwise, he endeavoured to pacify me,
not doubting but that I should again have the like offer made me,
putting me in mind of Gideon`'s fleece, etc.
Judges vi.
When next meeting day came, I went in great weakness and fear,
and would rather have gone elsewhere, than to meeting.
Sometime after I was in the meeting, I felt the same concern as before,
and sat under the weight of it until the meeting was almost over,
and then hardly knew how I got upon my feet, but did,
and broke out with a loud voice in these words: "`Fear not them which kill the body,
but are not able to kill the soul;
but rather fear Him which is able to destroy both body and soul in hell.
I say, fear you Him who will terribly shake the earth,
that all which is moveable may be shaken and removed out of the way,
that that which is immovable may stand.`"
This was all I had to say at that time.
But oh! the joy and sweetness I felt afterward, I cannot express,
and the pleasure of my mind appeared in my countenance,
so that my master took notice of it, and spoke so feelingly,
as plainly demonstrated he was a partaker with me of the same rejoicing:
this was about the year 1696, on that called Christmas day,
it falling that year upon the first-day of the week.

Having as it may be said, thus broken the ice, the next time was not quite so hard,
but I said very little, and seldom appeared for a year or two,
having about three years of my apprenticeship to serve,
which I did with fidelity and truth.
The last year of my time, I found a concern in my mind to visit Scotland,
being very rarely without some degree of Divine virtue, either by night or day;
therefore I thought, if it was so with me then,
it would be much more so when I had nothing to mind but Divine things;
but I found it otherwise, of which in its place.
I may not omit to mention that about two years after I first spoke in meeting,
I opened the New Testament at that passage spoken by our Saviour, Matt. 10:28.
to the same effect with what was first opened on my mind,
as mentioned above,
which then I knew not to be the saying of Christ to warn them against the fear of men;
although no doubt I had read it, but had taken so little notice of what I read,
that it was to me as if it had never been written.
But it was a great comfort to me,
that I was thus opened in a material point of doctrine
of our blessed Lord at my first setting out.

About the same time I had a desire to visit a neighbouring meeting called Yelland,
it being the first that I ever had a concern to visit,
and desired my dear friend Isaac Alexander to go with me.
Agreeing upon the time,
I went to Isaac`'s brother`'s house the seventh-day evening before, where Isaac lived;
and he and I went to visit James Wilson and his parents that evening:
James was under convincement, but not his parents.
We had some conference, but being called to supper, left off abruptly.
After supper I could not be easy without repeating my visit,
and James`'s mother being very quick in the Scriptures,
she desired my judgment on those texts in Isaiah and Peter: "`Behold,
I create new heavens, and a new earth, wherein dwells righteousness.`"
And my understanding was opened to preach unto her the new birth so effectually,
that she was thoroughly convinced, and continued an honest Friend to her dying day,
going to meeting the very next day, and so held on while able to attend meetings.

My time of servitude being at an end,
my master was very willing to keep me in his service, and spoke to me about it,
which gave me an opportunity to open my mind to him about my visit to Scotland.
He then told me to acquaint some of the elders in the meeting therewith,
for it was necessary I should have a certificate,
to show the unity of the brethren with my journey; which accordingly I did,
and had a certificate; Isaac Alexander being my companion, had a certificate likewise.

We went to Kendal, being the first meeting, and then to Preston, Yelland, Height,
Hawkeshead, and visited part of Lancashire and Yorkshire, in about three or four weeks.
But the poverty of my spirit was so exceedingly great and bitter,
that I could scarcely bear it, but cried out aloud, which so surprised my companion,
that being on foot, he feared it would be too hard for me,
for I complained that I was deceived or mistaken; because,
while I was in my master`'s work,
I rarely by night or day was without some degree of Divine virtue on my mind,
but now I could feel nothing but the bitterness of death and darkness;
all comfort was hid from me for a time, and I was baptized into death indeed.
As we went along, I said to Isaac with a vehemence of spirit:
"`Oh! that I was in my master`'s work again,
and favoured with my former enjoyments of Divine life, how acceptable it would be!`"
We came at our journey`'s end, to one Miles Birket`'s,
who was more than usually kind to us; but alas, he did not know my state and poverty.
Next day we went to another meeting at Hawkeshead, it was a little better with me,
but very poor; and so we performed our journey in about a month,
and he returned to his father`'s house, and I to my master Parrot`'s.

I was very reluctant to go to Scotland,
having been proved with so much poverty of spirit,
the cup was so bitter I could hardly bear it; however, I kept my mind to myself,
and we set forward on foot, visiting part of Cumberland in our way,
and I thought Isaac had fine service, so much superior to mine,
that after him I was afraid to lessen or hurt what good he had done;
and before him I was afraid to stand in his way.
He was much admired indeed, and some were convinced by his ministry:
we accomplished that journey in about two months time.
At our return hay harvest came on, and I went to mowing,
and on meeting days went just where my mind led me, and grew in my ministry very much,
and the Lord let me see his kindness to lead me through that state of poverty,
which was of great service to qualify me to speak to others in the like condition,
and that trials of sundry kinds were for my improvement and good,
tending to my establishment in the true root of a Divine and spiritual ministry;
and the doctrine of our Saviour and his apostle did much comfort me, so that I became,
in the opinion of several, an able minister, although but short,
seldom standing a quarter of an hour.
But alas!
I have seen since that I was but a mere babe in the work.

This summer passed over, and by my harvest work at hay and corn I got a little money,
being just pennyless before, so that I travelled to a meeting, fourteen or fifteen miles,
three times forth and back on foot all alone, with three halfpence,
being all the money I had, and thinking to refresh myself in the way,
when I came near the house of entertainment, I found myself so strong and cheerful,
that I thought I might need it more at another time, and so kept it.

Towards the fall I bought a horse,
and put myself in a condition for another journey with my old companion again.
We thought either of us pretty sufficient to hold a meeting; however,
I was to go with him through Bishopric and Yorkshire,
and he was to go with me into the west, as to Wilts, Somersetshire, Devonshire, etc.
We had not proceeded far, before I was very much shut up,
and had no satisfaction at all in going further with him.
I told him how it was with me, and we were both willing to part;
and I went to be at York on first-day, and meeting with dear John Richardson,
I laid my concern before him, and as a nursing father he spoke very encouragingly to me,
and he got meetings appointed for me at Wetherby, and so forward towards Doncaster.
I went on in great fear, and after meeting at Wetherby,
Benjamin Brown spoke very encouragingly, that "`the Lord would enlarge my gift;
and when you find it so,`" said he, "`do not value yourself upon it,
but give the honour of it where it is due, and keep humble, and God will bless you,
and make you a useful member in his hand.`"

My next meeting was at Wakefield, which was very much to my comfort and encouragement.
Then to Pontefract, where I had no cause to complain;
a Friend after meeting cavilled and found fault with what I had said,
which brought some uneasiness upon me: but being afterwards told he used to do so,
and that he was not in unity, it brought me off pretty light and easy.
I went from there to Doncaster on seventh-day, it being market day there:
I was conducted to Thomas Aldam`'s quarters, he being in town,
who soon came and looked at me, I thought austerely, first inquiring from where I came,
and if I had a certificate?
To all which I gave proper answers, and showed him my certificate;
all this seemed agreeable, and he undertook to appoint meetings forward,
and sent me home with his son.
Not having ever been so closely examined before, I feared how I should come off,
Thomas Aldam being a noted minister; but at last he came home,
and was very tender and kind indeed.
Next day, being first-day, we repaired to meeting,
and I came off much beyond what I expected, and preached almost an hour,
so that I was very cheerful in my spirit after it,
and we had a little opportunity in the evening, and all ended brave and well.

The week following I went to Blithe,
and took meetings in course as they lay by Maplebeck to Nottingham.
At Maplebeck there was a brave old living Friend, with whom I had great comfort,
his name was John Camm.
At this place I had the best meeting that I had ever had,
and it produced a remarkable effect upon me.
I thought the bitterness and anguish of death, which I had gone through before,
might now be over in a great degree,
and I should go on smoother and with more ease for time to come,
for the Friends showed me much respect,
and I was visited in the evening and morning before I left them,
by several who lived nigh: in short, I thought more of myself than I had done before,
that I remember.
Two or three of them went with me to Nottingham, seeming much pleased with my company.
It being seventh-day, I was there on first-day at two meetings,
and came off tolerably well, but not as at Maplebeck.

The third-day following I was at Castle Dunnington,
where was a fine collection of Friends; I preached some time among them,
but found not authority and life, as I thought, to attend me as before; however,
I desired another meeting with them in the evening, which was readily assented to,
which was very large, considering that place.
I seemed very poor and low,
and blamed myself much for appointing another meeting
in so poor and weak a frame of mind.
The meeting came on, and proved better than I expected; but I was very low,
and it being a clear moonlight night,
I walked into the Friend`'s orchard behind his house, bemoaning myself very much,
as having lost my guide, and fallen from that happy condition I was in the week before.
The Friend of the house finding I tarried, came out to me,
having a sense of my low state and condition, and inquiring how I did,
he began to speak in praise of those two meetings, and of the service I had in them.
All this did not raise my spirits; we went in, but he perceived I was very low,
and he and his wife endeavoured to comfort me.
His wife had a fine gift in the ministry,
and she told me some experiences she had gone through, but all did not do,
nor come near my condition.

Next day I went to Swannington in Leicestershire,
and there was a fine body of Friends again, and I had not sat long, before I felt,
as I thought, as good an authority to preach as ever, and stood up, not doubting an open,
satisfactory meeting.
I had not stood above fifteen minutes if so many,
until all was shut up and it seemed as though both the sun and air were darkened.
I sat down under a great cloud, to think what I should do, appealing to God,
that I had no ill design, but much otherwise, and in secret earnestly desiring help;
and immediately it was said in me, as though a voice had spoken intelligibly,
"`You run and God has not sent you; you speak but God does not speak by you;
therefore you shall not profit the people.`"
It may be thought if I was bad before, I was much worse now.
I was under the very hour and power of death and darkness,
being at my wits end what to do; and under this great temptation several ways presented;
such as my turning myself out of the line of Friends,
which I found would be somewhat hard to do,
as I always had a guide from one place to another: then it presented to turn home again,
and by that method I might get rid of Friends as guides,
and make the best of my way to some part of Ireland, sell my horse, and get work,
where I was not known, at my trade.
But then the honour of the Monthly Meeting, that had given me so good a certificate,
would be affected by my so doing: and having considered of several ways to take,
at last this presented, to make away with myself in some river or pond,
as though it had been an accident, and this would cover all.
Thus for a time I was bewildered, not seeing where I was; but since,
it plainly appeared I was under the influence of the spirit of antichrist.
Begging heartily for help, I fell on my knees, and prayed with such fervency,
that there were but few under the roof who were not melted into tears,
and it was such a time as I never had before nor since in prayer, as I remember;
and thus that meeting ended.

Next I went to a town called Hinckley,
and there was a considerable number of Friends and other people;
I was extremely low and poor, but had a comfortable meeting, which much healed me,
and set me to rights again.

I visited Leicestershire pretty generally, and a woman of some account,
whose name was Jemima Mountney, was convinced, and was with me at sundry meetings,
and was exceedingly tender and loving, being thoroughly reached and satisfied.
When we parted, she was so open-hearted that I was called aside by her,
and after having said something to me about her inward condition,
she offered me some pieces of gold, which I told her I dared not touch.
She very courteously, and with a becoming, genteel mien,
told me she was both able and willing,
and as she had no other way that she could show her gratitude
for that spiritual good she had received from my ministry,
she could do no less, beseeching that I would receive it,
as the true token of her love and respect.
In answer, I said, it was what I never had done, nor could I now do it;
but all the reward I desired and expected was, that she might carefully,
with a sincere heart, endeavour that her obedience did keep pace with her knowledge,
the hearing of which would rejoice my soul: we parted in great love and tenderness.
I heard that sundry others were convinced in that neighbourhood.
A very honest Friend, whose name was Brooks,
took great pains to get the seeking people to meeting,
and I was very much enlarged in pertinent matter,
suitable to the states of such seeking souls.

Out of Leicestershire,
being well rewarded for the bitterness I suffered before I came into it,
which was as much as I could bear, I passed into Warwickshire,
and had some good opportunities in that county at Warwick and other places.
I found I often hurt myself by speaking too fast and too loud;
against which I endeavoured to guard as much as I could;
but when I felt my heart filled with the power of Divine love,
I was apt to forget myself and break out.
I found it proper therefore to stop, and make a short pause,
with secret prayer for preservation, and that I would be supplied with matter and power,
that might do the hearers good.
Thus I went on, and grew sensibly in experience and judgment,
and became in some small degree skilful in dividing the word.
I had been straitened in my mind respecting searching the Scriptures,
lest I should thereby be tempted to lean upon them,
and by gathering either manna or sticks on the sabbath-day, death would ensue.
But at last I had freedom to examine the text,
and to consider where the strength of the argument lay,
both before and after the words I had repeated.
By this I saw I was often very defective,
in not laying hold of the most suitable part to confirm the subject or matter I was upon,
and this conduct did me great service.

Another difficulty stood in my way, which was this; some former openings would come up,
which I dared not meddle with, lest by so doing I should become formal,
and lose that Divine spring which I had always depended upon;
but the Lord was pleased to show me, that old matter, opened in new life, was always new,
and that it was the renewings of the spirit alone which made it new;
and that the principal thing I was to guard against was,
not to endeavour to bring in old openings in my own will, without the aid of the spirit;
and that if I stood single and resigned to the Divine will,
I should be preserved from errors of this nature.

Out of Warwickshire I travelled into Worcestershire,
visiting sundry meetings in that county, and found a fresh supply every day.
I was at Worcester on first-day, and after the meeting in the forenoon,
an ancient Friend examined me very closely, from where I came, and for a certificate;
to all which I gave him answers.
My certificate being at my quarters in my saddle-bag, he could not then see it;
but I had a very good meeting as I thought, and my landlord William Pardee, a brave,
sensible elder, advised me not to be uneasy at the old Friend`'s examining me, for,
said he, he does so to every stranger.

We went to meeting in the afternoon, which was very large, and I was largely opened,
and had very good service; but the old Friend, after the meeting,
was upon me in the same strain to see my certificate, but I had it not about me,
at which he seemed much displeased.
I made no reply, but told him I was very willing he should see it;
but my landlord took him up, and told him,
he thought the young man had already shown us his best certificate, in both the meetings;
but nevertheless, said he, come to my house in the evening, and you shall see it:
so we parted.
My landlord thought he had showed himself disagreeable in his conduct,
and fearing it would be an uneasiness to me, spoke very tenderly,
and like a nursing father encouraged me, saying,
"`I could not show him a better confirmation that I was anointed for the ministry,
than I had already done.`"
In the evening, after it was dark, he and many other Friends came; but my landlord,
the old Friend and I, went aside, and I showed him what he so much desired to see;
he read it, being much pleased with it, and knowing several Friends that had signed it,
inquired after them.
We went to our friends again, who were much increased in number,
and we had a heavenly season, being thoroughly baptized together;
we parted in great love and sweetness, and the old Friend was exceedingly kind.

From there I went into Gloucestershire, and visited part of that county,
and by Tewkesbury to Cheltenham, Gloucester, Painswick, Nailsworth and Tedbury.
I had several good opportunities; and one young woman was convinced at Tedbury,
who became a very good Friend.

From there I went into Wiltshire and Hampshire, as far as Ringwood,
and to Pool and Weymouth; called at Wareham and Corfe, and had a meeting at each place,
but nothing worthy noting at either of them: so I travelled to Bridport, Lyme, Membury,
Chard and Crewkern, and back to Somerton, Puddimore, Masson to a funeral,
and to Yeovil on first-day; thus having visited Somersetshire,
I went into Devonshire as far as Exeter; then turned up towards Taunton,
taking meetings in my way towards Bristol.

I stayed in Bristol, and visited meetings about the city nearly five weeks,
and from there I found my mind drawn to visit Wales.
I took the Quarterly Meeting of Plereford in my way, which was held annually at Amelly,
and there I met with my dear friend Isaac Alexander.
We were glad to see each other, as well as to hear each other, which when we did,
it appeared to me that Isaac was improved considerably, and he said the same of me,
observing that I preached the practical doctrine of the Gospel he thought,
more than he did; for his preaching was very much in comparisons and allegories,
which he apprehended were not so plain and easy to the understandings of the vulgar,
as what I had to say.
We had now an opportunity of opening our minds to each other,
which was of great service to us both, having several meetings together,
and we had drawings for the Yearly Meeting at Llanidlos in Wales.
This opportunity seemed very agreeable to us; there were sundry Friends of note,
Benjamin Bangs and others out of Cheshire; the people came in abundance,
and at times were very rude, but in the main it was a serviceable meeting.
After that I visited Wales, appointing from the Yearly Meeting several meetings,
as far as was thought proper at once; and a good old Friend, Philip Leonard,
offered to be my companion, which was of great service to me.
I was very poor and low at most meetings in that journey,
as but few of the people could understand what I said in some places:
but Philip stood up after I had done, and in part interpreted what I had said,
but I did not feel quite easy in my mind.

Isaac went to Bristol Yearly Meeting,
and was very zealous against unnecessary fashions and superfluities in both sexes,
insomuch that some thought, in his words against them, he exceeded the bounds of modesty:
but he might plead the example of the prophet Isaiah in that respect.
The chief objection to him was, concerning his prophesying a great mortality,
which the Lord was about to bring as a judgment upon the people,
for their pride and wickedness;
which he thought it his duty to deliver in their Yearly Meeting,
as a warning for all to mind their ways, lest, being taken unprepared,
their loss should be irreparable.
This he did in such strong and positive terms,
that Friends were afraid he was too much exalted in himself:
upon which some of the elders thought proper to converse with and examine him,
concerning this extraordinary message which he had delivered:
but what he said to them not being satisfactory,
they advised him to proceed no further on his journey, but to return home;
which he did under great trouble, and was there received in much love and tenderness,
and appeared in his gift very excellently, and grew in Divine wisdom and power,
being of great service in the ministry wherever he came.
Having a concern to visit the churches abroad,
and acquainting some of our elders therewith, they thought it not proper for him to go,
until something was done to satisfy Friends at Bristol, and upon their inquiry of Isaac,
he gave them a single and honest account how it was with him at that time,
respecting his concern: so Friends took it in hand, and wrote to Bristol,
neither justifying nor condemning him,
but recommended charity and tenderness towards him.
And from Bristol, Friends answered, that "`with open arms they could receive him,
believing him to be a sincere young man, who intended very well:
and they were glad he took their admonition right,
and had owned it had been of service to him.`"
Thus ended this affair, and Isaac said,
"`he could not think hardly of his brethren in doing what they did,
though he could not then see that he had missed his way in delivering that prophecy.
Thus showing forth a lively instance of a warm zeal,
tempered with a due regard to the sense and advice of his brethren and elders,
and the unity of the church, which doubtless tended to his own comfort and preservation.

When I heard of it, I took it so much to heart, it was almost too much for me,
and a concern came upon me to go to London with the like message, but with this caution;
first to advise with some faithful brethren before I delivered it: and I wrote to Isaac,
to let him know it, which gave him great ease.
Accordingly I went to London, and got several brethren together, namely: James Dickinson,
James Bowstead, Peter Fearon, Benjamin Bangs, Robert Haydock, and some others,
and gave them a plain and honest account how it came upon me,
which was not till after I heard my dear companion was returned home from Bristol;
adding, that I had acquainted Isaac how it was with me,
that he might know my sympathy with him.
The Friends seeing what he had written, found there was a strong sympathy between us,
and very justly supposed that to be the moving, if not only,
cause of the concern I was under,
and very tenderly advised me to keep it in my own breast,
till I found how the Lord would order it; for, if he was the author,
I should find more of it; if not, it would die.
But if I found it grew upon me, I should let any of them know it,
and they would consider what steps to take in a matter of so great consequence,
as going forth in a prophecy of that nature.
The fatherly kindness they showed me was very affecting to me,
one or other of them making it their business to visit me every day; and as they said,
I found the concern went off, and I became easy without publishing it.

I had several very acceptable opportunities in London,
during the time of the Yearly Meeting,
and afterwards visited Friends towards Leeds in Yorkshire,
and in my way there had very agreeable service in the counties of Leicester and Nottingham,
and at other places.

From Leeds I went to the Yearly Meeting at York, which was very large,
and many public Friends; but I was hid, as it were,
and made very little appearance at that meeting.

From there I travelled homeward, visiting Friends as I went,
and was gladly received by them.
I found my ministry very acceptable; and as it increased upon me,
I was very humble and low in mind,
knowing my strength and safety from temptation consisted therein.

I was now in a strait what course to take to get a little money,
my linen and woollen clothes both needing to be repaired.
I met with a young man newly set up in his trade, with whom I proposed to work,
and he was ready to comply with my offer, supposing it would be a means to improve him.
So we agreed, and I began with him, and found it answered much better than harvest-work,
so that I soon stored myself with a little cash, and worked hard all that summer,
and in the fall of the year prepared myself for a
journey with my good old friend Joseph Baines.

We set out the latter end of the sixth month, and visited some parts of Yorkshire,
and so into Lincolnshire, Suffolk and Norfolk, and we did very well together;
only I was afraid that Friends took so much notice of me, he would be uneasy;
but he was so entirely innocent, and had so much of the Lamb in him, that he never did,
that I could find, show any uneasiness, more than to give me a caution with a smile;
"`Sammy,`" said he, for I was mostly called so,
"`Friends admire you so much you have need to take care you do
not grow proud;`" and indeed the caution was very seasonable,
as well as serviceable to me; which I saw and acknowledged.
This Joseph was, it might be said, an Israelite indeed, as meek as a lamb,
not great in the ministry, but very acceptable, especially among other people,
having a meek, quiet, easy delivery, mostly in Scripture phrases,
with which he was well furnished,
repeating them with very little or no comment upon them, which some admired very much;
and he had great service at funerals,
being in a peculiar manner qualified for such occasions:
but receiving an account of some troubles in his family,
it brought a very great uneasiness upon him, and he returned home.

I visited most of the meetings over again, and returned into Huntingtonshire,
Northamptonshire, and so towards Dorsetshire, and Somersetshire,
visiting as I went through part of Oxfordshire.
I had many meetings, sometimes fourteen in a week, and generally to satisfaction.
In almost every parish where a Friend lived, we had a meeting,
besides which some offered their houses, who were not Friends, which we embraced.

I came through part of Hampshire and Warwickshire, and back again to Hampshire,
visiting Friends, and had many meetings in places where none had been, and the people,
who were not Friends, were much inclined to have meetings at their houses in many places,
and would desire Friends to conduct me to their houses.
Although I was entirely unknown to most,
yet there was a very great willingness to receive the doctrine of Christ;
and I found afterwards, by accounts I received from Friends some were convinced.
The teachers of the national way, and dissenters also, were much disturbed,
and threatened what they would do, and that they would come and dispute;
some of them came several times, and got out of sight,
where they could hear and not be seen; but never any gave me the least disturbance;
though some would say I was a cheat, a Jesuit in disguise; others,
that I was brought up for the pulpit, and for some misdemeanour suspended;
and so they varied, according to their imaginations.
But I was very easy in my service, and found my heart very much enlarged;
some of the people took me to have a good share of learning, which,
although it was false, served for a defence against some busy fellows,
who thought they could dispute about religion and doctrine;
which I always endeavoured to avoid as much as possible,
seldom finding any advantage by such work,
but that it mostly ended in cavilling and a strife of words.

I went through part of Dorsetshire, and at Sherborne an old Friend was sick,
and not expected to get over that illness,
and it came into my mind he would die of that sickness,
and that I must be at his funeral, and preach with my Bible in my hand.
This made me shrink, fearing it was the fruit of imagination, but I kept it to myself,
and had many meetings about those parts.
A young woman, who afterwards became my wife,
had strong hold of my affections and I acquainted her parents therewith,
and had liberty from them to lay it before their daughter, which I did.
At the same time a concern was upon me to visit America
before I entered into the state of wedlock,
which I also gave her to understand; for I had reasoned in my own mind,
that it might be better to let it rest until my return, if I lived.
But in answer to that, it appeared,
that I might have some prospects there that would be a snare to me,
and by this prior engagement I might be freed from all temptations of that kind.
For if it was known there that I was already engaged,
it would command silence on that account.
On this consideration I made suit to her,
and she received it with such modesty and sweetness as were very engaging.
She had an uncle, on whom she had some dependance, who seemed much averse to it,
and would have his niece left at liberty,
that if any suitable offer was made in my absence she might embrace it;
which I very readily complied with.
He was then pleased, only he would have me leave it under my hand,
which I was very ready to do; and to stand bound myself, and leave her at liberty.
To this she objected, as unreasonable on her part to desire such a thing from me.
We parted, and I went to Street, Glastonbury, Burnham, Sidcot, Clareham and Bristol,
having let slip out of my memory the old Friend`'s sickness at Sherborne.
I had not been many hours in Bristol before a messenger
came to desire Benjamin Coole to attend the funeral,
and Benjamin came to me to Brice Webb`'s, where I lodged, and told me how it was,
and desired me to go.
I pleaded many excuses; first, my horse was not fit, with other objections,
which were all removed.

I went to Bruton next day, being the seventh-day of the week,
and was at that small meeting on first-day.
The funeral was on second-day, which was exceedingly large,
John Beere from Weymouth being there, had something to say, but not much.
Then as it was with me, I pulled my Bible out of my pocket, and opened it;
upon which the people gave more attention than they had done before,
and I had a very acceptable time,
often in the course of my matter referring to the text for proof,
and giving an ample testimony of the value we put upon the Scriptures;
earnestly pressing the careful reading of them, and advising to consider what they read,
and to seek the Lord by prayer, for assistance and power,
that they might practice what they read, which was the ultimate end of reading,
as well as of hearing preaching, for without practice, it would avail but little;
with other advice to the same effect.
There being sundry teachers of several societies, one of them, a Baptist,
took hold of me after meeting was ended, and desired some conversation with me.
I looked at him earnestly,
and desired to know if he had an objection against any part of what I had said?
"`If you do,`" said I, speaking with an audible voice, that stopped many of the company,
"`this is the most proper place,`" the people being present;
for they thronged about us very much.
This made him confess, that what he had heard was sound, and according to Scripture,
being very well proved from the text;
but he desired some private discourse between ourselves at my quarters,
if I would permit it.
I told him he might; I quartered at Richard Fry`'s; and Richard being present,
told him he should be welcome to come to his house, and so we parted.
When I came to Richard`'s, he said we should hear no more of him,
for that in his discourses among his hearers,
he had spoken many very unhandsome things against the Quakers,
endeavouring to unchristian them, and prove them heathens in denying the ordinances,
a common plea used by all our adversaries.
But this man carried the matter farther than some others did, by adding,
that we denied the Scriptures,
and also would not allow of a Bible in any of our meetings,
nor did our preachers use a Bible to prove anything
therefrom that we preached to the people,
with more to the same purport; and as many of his hearers were there,
my appearing with a Bible, and referring to the text for proof, no doubt,
put him and them upon a thought what had been preached by him, among them,
concerning the Quakers,
which now appeared to be a manifest untruth by what
they had both seen and heard that day.
As Richard Fry thought, so it proved; he did not come near me,
and Truth was exalted above lies and falsehood.

I returned to Bristol well contented, being filled with peace and consolation.
At my return I gave my friends Benjamin Coole and some others, a relation of my conduct,
and Benjamin was much pleased that I went there,
and repeated what he had said before to persuade me to go, adding,
he was pretty much assured it was my place to go;
but that if he had known that it was in my mind to preach with the book in my hand,
although in the sequel it proved right,
he should have been afraid there was more of imagination than revelation in it.
It would rather have backened him, than been any argument for him to press my going,
as he had found some mistakes committed from such sights,
which proved to be but imaginations.
He gave me very suitable advice,
to take care how I too easily embraced such things for truth, without a due trial,
and that it was not displeasing to heaven to try the spirit from which such things proceeded.

I stayed in and about Bristol three weeks, visiting the meetings round the city,
but on first-days I was mostly in the city, and it being the winter fair,
meetings were very large.
At the third-day meeting in the fair week, there was a man out of Wiltshire, a Separate,
named Arthur Ismead, who stood up to preach, and was speaking of the light:
he put forth a question about bringing our deeds to the light; adding,
"`do I bring my deeds to the light?`"
A worthy elder, named Charles Harford, answered, "`No, you do not: if you did,
you would not do as you do.`"
I sat all this time under a very great concern, and the word was in me like fire;
so I stood up, and with a strong and powerful voice began to preach, he crying out,
that he had not done.
I took no account of that, but went on, and he soon sat down and fell asleep,
and we had a blessed, edifying meeting that day, and Truth was exalted above error.
After this meeting I was clear of the city, and visited some parts of Gloucestershire,
Worcestershire, Derbyshire, Cheshire and Lancashire.

In many places I had very large, open, quiet meetings,
and when I found myself high and full, I expected low times again,
for I very seldom was drawn forth in doctrine, and enlarged more than common,
but Maplebeck would come in my way,
and the uncommon temptation and trial I underwent after that meeting.
I reached home about the latter end of the first month,
and stayed with my dear friend Robert Chambers part of that summer,
helping him and his brother-in-law, John Moore, at Gale,
mowing more days this year than I ever did in one before.
John Bowstead and Peter Fearon had a meeting appointed for them at a place called Goose-green,
between Kendal and Milthrop; to which meeting there was a very great resort;
and being desired to attend it, I did, and in the beginning of the meeting,
I spoke something of the universal love of God to mankind.
After which a Friend went on with the same subject,
and inferred from the text something more than it would bear.
A young man who taught a school at Beatham, a small parish in that neighbourhood,
took him up after the meeting was over; and having the advantage of the argument,
endeavoured to bear the Friend down.
I was gone to see the horses got ready for our return,
but being called got with difficulty into the house, which was much crowded,
the meeting being held in the open ground without the house;
and when I got in and heard them, I soon found where the pinch was;
the Friend had said what the text would not bear him out in,
in quoting Obadiah the tenth verse,
compared with Romans the ninth chapter and eleventh verse.
I observed that he went too far in expression when I first heard it;
and repeating the words more than twice, the young man had them very plain.
I waited some time, and then desired liberty of the young man to ask him a question,
the answering of which might bring the argument to a point; adding,
not that I thought myself so capable to maintain that argument as my friend was.
He gave me leave, and my question was,
"`Whether he believed it consistent with Divine wisdom and mercy,
to punish men for such faults, as by his argument they were ordained to be guilty of,
and which because of that ordination they could not avoid?`"
He soon very frankly gave answer, "`he did not believe it.`"
I then asked him, "`Why he argued against his own faith and judgment?`"
For although he took advantage of my friend`'s words,
not being so well guarded as they should have been,
yet that was no just ground to argue against his own judgment.
Thus this argument dropped, and then he took up baptism;
but soon finding himself not able to support what he undertook to prove by the text,
namely: infant baptism, he confessed that he was not qualified to maintain his argument,
and therefore requested that we would favour him
to confer on that subject on Wednesday next,
in the room where he taught school, with the minister of their parish; adding,
it might be of service both to him and others.
My friends were very much for it, and I was not against it,
provided they would go and assist:
for I looked on myself very unequal to such a task as this was likely to be.
However, after some discourse between ourselves, I consented,
on condition that John Jepson, the schoolmaster of Kendal, would be my second;
he being well acquainted with, and understanding both the Greek and Latin Testament,
might help me against being imposed upon by any false gloss
or interpretation put upon the text to prove their arguments.

We told the young man we would endeavour to answer his request,
by being with him on fourth-day by nine in the morning:
he was glad to be discharged for the present,
for I had not seen one sweat more freely than he did, being in a very great agony,
he could not forbear shaking as he stood by the table:
we parted for this time very good friends.
But I grew uneasy, fearing how it would end,
and blamed my friends for bringing me into this scrape, and not assisting me in it,
but leaving me to dispute with I knew not who; but all I got was,
that they doubted not but I should be assisted to come off well,
of which I was very doubtful, and it hindered me of some hours sleep.

When the time came, my friend John Jepson and two more went with me.
We came pretty early, rather before than after the time appointed;
and the young man had got his room, and two elbow chairs ready,
for the parson and myself.
I was not willing to sit in either, being younger than friend Jepson;
but to avoid words about it, I sat down in one.
The young man acquainted the parson we were come, and he came to us, scraping and bowing,
and the more we supposed, because he saw we did not answer him in the same way.
After he sat down, previous to entering on what we met about, he would needs have it,
that I challenged a dispute with him; to which I could not agree.
But referring myself to the young man,
I desired that he would inform his neighbour of the true cause of our coming there,
which he did very handsomely, to the following effect: "`Sir,
meeting last sabbath-day with this gentleman,
we fell into a conference about infant baptism,
supposing that I was able from Scripture to prove that practice; but on trial,
finding myself not able to hold the argument, I shut it up.
Therefore, believing you, sir, to be more able to defend the practice of our church,
than I am,
I desired this gentleman to favour me so much as
to come and confer with you on this subject,
in my hearing, that I might have this matter set in a true light.
I beg your pardon, sir,
hoping that this modest request to the gentleman is not offensive to you,
and I will assure you, it is a great pleasure to me.`"

Thus having made his apology, the priest being a hasty, passionate man, began;
"`You Quakers are not fit to be disputed with, because you deny the Scriptures,
the ordinances of baptism and the Supper of our Lord.`"

I addressed myself to the young man, to inform the parson that infant baptism, so called,
was the present point to be considered; which he did in a few words, and very well,
but it was to no purpose.
The priest would go on in his own way, calling us heretics, schismatics, heathens,
and what not, bestowing freely such reflections upon us as came into his head;
and having gone on in this rambling way for some time, with unbecoming language,
I requested that he would hear me without interruption, as I had him.
I then put him in mind of his old age, he having a comely personage,
and fine white locks, and that he had more experience, it might with reason be supposed,
than we young men had; and supposing that you may be right,
and that we may be in an error, yet for all this, in my opinion,
you must be wrong in your conduct towards us, in being so liberal to give us hard names,
and yet show no reason for doing so.
Here I was broken in upon with a kind of violence,
"`That all the disciples and apostles had a commission to teach all nations,
'`baptizing them in the name of the Father, Son,
and Holy Spirit.`' Do you confute this or own it?`"
I urged, "`no water is named in the text; and besides, that text should be rendered,
'`into the name`' of the Father, Son,`" etc.

Here the young man, and my friend Jepson, searched both the Latin and Greek,
agreeing that it was more proper to render it "`into
the name,`" than "`in the name,`" etc.
Then if that was right, as it was my opinion it was, it was plain to me,
that the materials of that baptism could not be elementary water, therefore,
I could see nothing in this text to prove the practice of sprinkling infants,
or infant baptism.
Here I was interrupted with great warmth again: the parson urging, that "`the disciples,
primitive ministers, and apostles, all had a commission in Matthew xxviii.,
which by succession was to continue to the end of the world:
and this baptism was with water,
for the apostles could not baptize with the Holy Spirit.`"
In answer I said, "`When Peter, at the house of Cornelius, began to speak,
the Holy Spirit fell on them, as on us at the beginning,`" said Peter;
from which it is plain, that teaching by direction of the Spirit being prior to baptism,
the baptism of the Holy Spirit was the consequence of such teaching.
But this did not please the parson; but he in answer said,
"`That undoubtedly the commission in Matthew xxviii.
was water, it could be nothing else: What, are you wiser than all our forefathers,
who have understood, ever since the first ministers,
this text to mean no other than water, and accordingly have so practised?`"
I queried, if he thought the text meant outward, elementary water?
He said he did.
I desired to know his reason for so believing.
He answered,
"`The practice of the apostles in pursuance of that commission which all had.`"
I then queried, if he thought Paul was included in that commission?
He granted that he was, "`and by virtue of his commission he baptized many.`"
But I desired they would turn to the text, 1 Cor. 1:17,
where the apostle plainly says, "`Christ sent him not to baptize,
but to preach the Gospel;`" and in the foregoing verses he thanks God,
"`he baptized no more,`" etc.
Besides, allowing that they did baptize with, or more properly in, water,
yet this argues nothing in proof of sprinkling,
nor is there any precept or precedent for it in all the Bible.
At this the parson stood up in a passion, told us we were no Christians,
nor fit to be conversed with as such, and left us in a rage without any ceremony.

The young man acknowledged that the minister, as he styled him,
was not able to defend his own practice from Scripture,
and desired we would lend him some books treating on that subject and others,
in which we differed from them and other dissenters in point of religion.
We agreed to let him have William Penn`'s Key, Robert Barclay`'s Apology,
and some others, upon applying himself for them to John Jepson, his brother schoolmaster.
He was thoroughly convinced, and likely to make a good man; he had several enemies,
among whom the parson was not the least: but he shortly after this sickened and died.

I was very diligent in following harvestwork, both at mowing and reaping,
and diligently observing my gift, to attend such meetings as I was inclined to;
and I found that I grew in my gift, as I could discern myself.
But I would check myself for such thoughts,
seeing them by no means proper to have a place in my heart, lest that humility,
which is the ornament of every Gospel minister,
should be departed from through self-love and conceit,
by which I might be brought to have a better opinion
of myself than any of my neighbours had;
which, if given way to,
would eat out all that respect my brethren and the church had for me;
and by this foolish pride and conceit, the hearts of Friends would be shut against me,
and I should lose my place and interest in them.

I had one journey more to make into Scotland, before my going,
or at least intending to go, into America, of which in its place.
