== Chapter II.

[.chapter-subtitle--blurb]
An account of my journey into Scotland, in the work of the ministry,
begun the 11th of the eighth month, 1701.

I had for my companion in this journey, Isaac Thompson,
a young man who had a good gift in the ministry.
We visited meetings in our way to Carlisle,
finding our understandings much enlarged in the opening of Divine truths,
and our service grew upon us, and we went on with boldness and cheerful minds,
meeting in our way, with our dear and worthy friend James Dickinson,
who was intending a visit into Ireland.
In our journey from the border to Dumfries,
we had very profitable conversation of good service to us both, because we,
by reason of youth and lack of experience, were often very weak,
and doubting whether we were right or not in the work; so that this dear friend,
by his tender and fatherly care and advice to us, was of great encouragement,
in letting us know how weak and poor he often found himself;
which so answered my condition, that it was as marrow to my bones.

When we came to Dumfries, after we had taken some refreshment at our inn,
James said to us, "`Lads, I find a concern to go into the street, will you go with me?
For he thought it might only be to show himself,
and was desirous that we might all go together, being five in number.
So we walked forth, and the inhabitants gazed upon us,
for the Quakers were seldom seen in that town; and several came after us,
and James lifted up his voice like a trumpet among the people,
who were very quiet and attentive.
When he was clear, we retired back to our inn, and several followed us,
who were very rude and wicked, but were not permitted to hurt us.
We had sweet comfort and refreshment one in another at our quarters.
Next morning we took leave and parted, he went for Portpatrick,
and we visited the meetings, though very small, until we came to Hamilton,
where we were finely refreshed with a small handful of living Friends; and so to Glasgow,
where the people were rude, but something better than in times past,
not being so uncivil to us in the streets.

We went from there to Kinneel, Lithgow, and so over the water on our journey northward,
taking Boroughstowness and Ury in our way to Aberdeen Quarterly Meeting,
where we found Friends in a sweet frame of spirit, being in dear unity one with another.
We had meetings with them to good satisfaction, and had some also further north,
as at Inverary, Killmuck, etc.
We then came back to Ury by Aberdeen, taking our journey to Edinburgh,
visiting the small meetings,
and some other places which we inclined to visit in our way there.
We had but one little meeting there, and then went to Kelso,
where we stayed two meetings on the first-day of the week,
and in the evening Friends laid before us the desire they had for our going to Jedburg,
a town about seven miles from them, and not much out of our way to England.
We considered the matter, but not the exercise that might attend us in going there;
so next morning we went, and when we came to the town, Samuel Robinson being our guide,
the landlord at the inn would not give us entertainment.

We went to another inn, and the landlord took us in,
telling us how indecently the minister had railed against the Quakers the day before,
asserting they were the devil`'s servants,
and that by his assistance they did in their preaching what was done;
with very many vile words;
but observing one of his hearers taking what he had said in short-hand, he called out,
charging him not to write what he spoke at random against the Quakers;
with much more to the same effect.
We called for some refreshment, but my mind was under so much concern,
I could neither eat nor drink.
We desired to pay for what we had, and gave the landlord charge of our horses and bags,
whereby he suspected that we were going to preach: he took me by the hand,
and begged that we would not go into the street, but preach in his house,
and he would have his family together, and they would hear us.
I looked steadily upon the poor man, who trembled very much, telling him,
"`we thought it our place and duty to preach to the inhabitants of the town;
and do you think,`" said I to him, "`we shall be clear in the sight of God,
whom we both fear and serve, by preaching to you and your family,
what we are required to preach to the people in the town?`"
The poor man I found was smitten in himself, and his countenance altered greatly,
but he made this reply, "`Is this the case, sir?`"
I said it was.
"`Then,`" said he, "`go, and God preserve and bless you,
but I fear the mob will pull down my house for letting you have entertainment,
and kill you for your good will.`"
I bid him not fear, for he whom we served was above the devil,
and that not a hair of our heads should be hurt without his permission.
He then seemed willing to let us go, and followed at a distance to see our treatment.

The chief street was very broad, with a considerable ascent,
and near the top of the ascent was a place made to cry things on, to which we walked,
where we paused a little, but I had nothing to do there at that time.
Returning back to the market-cross, which was at the foot of the hill,
and had an ascent of three or four steps, and a place to sit on at the top,
we sat down;
but we had not sat long before a man came to
us with a bunch of large keys in his hand,
and took me by the hand and said, I must go into the Tolbooth, meaning the prison;
I asked him for what?
He said for preaching.
I told him we had not preached.
"`Ay! but`" quoth he, "`the provost,`" meaning the mayor,
"`has ordered me to put you in the Tolbooth.`"
"`For what?
"`I again replied.
"`I tell you for preaching.`"
I told him, I did not know whether we should preach or not;
but it was soon enough to make prisoners of us when we did preach.
"`Ay!`" says he, "`I ken very weel that you will preach by your looks.`"
Thus we argued the matter, he endeavouring to pull me up, and I to keep my place;
and when he found I was not easily moved, he turned to my companion,
who likewise was unwilling to be confined, and then he went to Samuel Robinson,
our guide, who was easily prevailed on to go, and the easier,
for that he had been there but the week before with two Friends, namely:
John Thompson and Thomas Braithwaite, both of our county of Westmoreland.

By this time we had a large assembly,
and Samuel Robinson supposing we should have a better
conveniency to preach to them in the prison,
as the Friends afore-named had the week before, we were conducted there,
just by the cross where we held the parley, and put in at the door.
But Samuel Robinson soon saw his mistake,
for the week before the windows of the prison were all open,
nothing but the iron grates in the way, the windows being very large for the sake of air,
but now all were made dark, and strongly fastened up with boards.
We had been but a short time there, before a messenger came to offer us liberty,
on condition we would depart the town without preaching;
but we could make no such agreement with them, and so we told the messenger.
A little after he was gone, I wrote the following lines to the provost.

[.embedded-content-document.letter]
--

It is in my mind to write these few lines to you, the provost of this town of Jedburg,
to let you understand that our coming within your
liberties is not to disturb the peace of your town,
nor to preach false doctrine or heresy, as is by your teachers maliciously suggested,
whose interest it is, as they suppose, to make the people believe it,
but in obedience to our Lord Jesus Christ, whose servants we are,
for he has bought us with his most precious blood; and we are no more our own,
but his who has bought us, whose power is an unlimited power,
and all other power is limited by him.
His power is not to be limited by any other power;
therefore we his servants dare not limit ourselves, or promise any man we will do this,
or we will do that, but commit our cause to him, as the Lord`'s servants did of old,
knowing, that if we please him he can deliver us, but if not,
we can make no promise to any man on this account,
because we ourselves know not what he has for us to do;
and therefore we endeavour to stand clear from all engagements,
ready to do what he requires at our hands.

I must tell you,
that the manner of our imprisonment looks very rigid
and uncommon in these times of liberty,
so far below a Christian that it is hardly humane,
that we should be here detained as evil doers, before we are examined,
or any breach of law appears against us.
Does your Scotch law judge a man before it hears him?
If so it is very unjust indeed, and looks very hard,
that the king`'s subjects may not have the liberty to walk in your streets as elsewhere,
which was all we did,
besides sitting down on the market-cross in a thoughtful sense of our duty to God,
not opening our mouths but to him who violently forced us into confinement;
nor do we know that we should have spoken to the people in the way of preaching at all.
This is the work of our Master, and we must wait his will and time,
to know both when and how to do it;
therefore if you think to keep us until we promise you or any of your officers,
not to preach in your streets, it will be long that we must abide here.

I desire you to take the matter into Christian consideration,
to do as you desire to be done unto,
and give yourself liberty to think for what end the
magistrate`'s sword is put into your hand,
that you may use it right,
lest you should be found one of those who turn justice backwards,
so that equity cannot enter.

[.signed-section-closing]
This is from one that wishes your welfare and salvation.

[.signed-section-signature]
Samuel Bownas.

[.signed-section-context-close]
Jedburg Tollbooth, 18th of Ninth month, 1701.

--

When I had written this, it was very hard to persuade anyone to carry it to the provost,
for now they were so affrighted about having anything to say or do with us,
that they dared not appear to talk with us; and whether he had it or not,
I cannot be certain.

The next day there was a country gentleman came into the town,
and sent his servant to invite us to his house, to which we replied,
"`We knew not yet when we should have our liberty;
but desired our thanks might be returned to his master, for that kind invitation.`"
He replied, we should soon be at liberty, for his master was gone to the provost;
knowing they had no pretence to keep us there.
Accordingly in less than two hours after, we were set at liberty,
and went to our inn to refresh ourselves.
The town was very full of country people, it being market day,
and we went to the market cross,
which was so much surrounded with people selling their ware,
that there was no room for us, without great damage to them.
We therefore, after a short pause, walked up the street to the place before named,
and the street and balconies were filled with people, with the sashes and casements open,
and crowded with spectators, some computed the number to be above five thousand,
but such guesses at numbers are uncertain.

There I stood up, being above the people, both by the advantage of the ground,
and the place where I stood, and opened my mouth,
being full of the power and spirit of grace, saying, "`Fear the Lord,
and keep his commandments,`" who by his servants said,
"`I will put my law in their minds, and write it in their hearts,
and I will be to them a God, and they shall be to me a people.`"
Now if you are obedient to this law, you will do well,
and thereby become the people of God; but if disobedient,
you will lie under his wrath and judgments.
With more, distinguishing between the happiness of those that obey,
and the unhappiness of the disobedient.

I stepped down, in expectation that my companion might say somewhat,
but he was willing to be gone; and I was concerned to step up again, and kneeling down,
was fervently drawn forth in prayer; but after I had begun,
two men came and took me by my arms, and led me down the street praying,
and by the time we came at the foot of the ascent, I had done praying.
After this I took a view of the people, who showed great respect indeed;
but I was conveyed to the prison door, where was a sentry of two soldiers,
who heard what I said to the officers that brought me there, to this effect:
"`That the day before I was forced there against my will, and contrary to law,
but that I would not go there again, without being first examined by the provost,
or by their priest and elders of their church, or other chief officers in their town,
and if then it appeared that I had broken any law, or done aught worthy of imprisonment,
having a court order setting forth my crime, I would willingly suffer,
and not refuse going there; but without such an examination I refused to go there again,
unless forced to it by violence, and that I hoped they would not be guilty of.`"

At this one of the soldiers, taking his musket by the small end,
and advancing the butt said, "`his countryman had spoken right,
and what he said was according to law and justice, and ought to be observed as such;
and therefore if you will take him before the provost for examination, you may;
but if not, touch him that dare.
At this bold speech they both left me,
and I was advanced above the people about six or seven steps, and turning about to them,
there being a little square before the door,
surrounded with the guard chamber on one side, the Tolbooth on the other,
and a wall facing the street about four feet high,
I had a very good opportunity to speak to them, which I did,
about a quarter or near half an hour, and they were very quiet and civil.
When I had done, and acknowledged the soldier`'s kindness and civility towards me,
who said "`It was his duty to do it,`" I came down the steps,
the people crowding very close to see as well as hear me, but they divided soon,
making a lane for my passage, showing me considerable respect in their way.
Some said, "`You have done them, sir, you have done them,
sir;`" meaning thereby I had got the victory.
All was very quiet, save that one or more would have forced a horse over us,
but was prevented by the rest.
Not the least unhandsomeness appeared among them save that.
Retiring to our inn, I was full of peace and comfort.

By this time the day was much spent, and concluding to stay that night,
we ordered some refreshment to be got for us, for I found myself in need of it.
It was soon got ready, and we invited our host to share with us, who willingly did so,
showing his good liking to what had been said; adding,
he never saw the people so struck and give so good attention;
nor did ever he see so large a multitude who heard
so intelligibly down to the very foot of the hill,
which was, as he supposed, not much less than two hundred yards in length, and,
by computation, I took the street to be upwards of thirty yards wide,
and all that space much crowded.
I gave him a hint of his fear,
putting him in mind that our duty in preaching to that multitude,
could not possibly be discharged by preaching to him and his family,
and he acknowledged it was right in us to do as we did.

By this time the evening closed in,
and some gentlemen sent word that they would gladly pay us a visit,
if we would permit it, and the landlord, I saw, earnestly desired we would.
He had a very large room, into which we went, and they soon came to us,
and quickly fell into conversation, for they are very full of talk about religion,
and very tenacious in their opinions upon it.
The first article of dispute was,
about "`the rule of faith and practice;`" and this was argued, pro and con,
nearly half an hour, between them and our guide, Samuel Robinson,
who was a very sensible religious young man, and had a good share of learning also;
but I found they made nothing of it.
Our opponents would endeavour, in their way,
to make out the Scriptures to be the only rule of faith,
and the Spirit we professed to be guided by, to be subordinate to the text.
I hitherto had said nothing, but now desired a few words by way of question,
the answering of which might bring this dispute to a point.
I said I thought not to take the argument from my friend Robinson,
whom I took to be more capable to support it than I. All were very willing to hear me;
and I began to state the difference between us thus; "`We all agree,
that the Scriptures are a rule of faith and practice; do we not?`"
This was granted.
"`The difference lies here, if I take it right, we say it is a rule; you say,
it is the only rule; this is the point in dispute, is it not?`"
this was likewise granted.
Then I proceeded thus; "`allowing what you say to be true,
it must be considered that all instrumental rules are made,
whether they relate to spiritual or temporal affairs,
and must be contrived and adapted to answer the end for which they are made.`"
This was allowed also.
"`And as the text is a rule made, contrived and adapted for spiritual affairs,
who made it so?
since the text could not make itself.`"
Here was a long pause; at last one replied,
"`Holy men wrote as they were moved by the Holy Spirit.`"
Here was a long pause again; "`and,`" said I, "`is this your mind?`"
"`It is the plain words of the text,`" said another: "`Granting this,
then it must by your concession be allowed,
that the Spirit gave forth or made the Scriptures, by the medium of holy men;
therefore the Spirit gave forth the text: now judge you, whether a rule made,
or the author who made that rule, be subordinate?`"
There was a pause for a little while, and one of the company said, "`You are done,
you are done,`" meaning they had lost the victory,
"`the Scriptures must be subordinate to the Spirit that gave them forth.`"
I replied thus, "`We believe concerning the text, that it is a rule,
and the best external rule we have; but that the Spirit,
which gave it us by the medium of holy men,
is the principal rule of faith and practice.`"

Thus this debate ended, and they started another about baptism; but that was soon ended.
Our friend Robinson, was an over match for them by far about it.
Then they had a few words about the bread and wine; which held but little time,
for they allowed these ceremonies to be external parts of religion.
Then they came to preaching, and stated the question thus;
"`We know how our own teachers come by their ministry,
and by what authority they preach,`" meaning their learning,
and laying on the hands of the presbytery at their ordination, etc.,
"`but we want to know, how your preachers come by their ministry,
and by what authority they preach?`"
Here our friend reasoned with them some time, but they either could not,
or would not be convinced with his words; so he told the company plainly,
"`that he never did preach, and therefore would leave it to those who did,
to give account how they came by it.`"
I was, all the time that they bandied this affair, under a great concern,
fearing how we might come off;
but when Samuel Robinson laid the matter so justly and fairly at our door,
there was so considerable a space of silence, that they expected nothing from us,
but began other discourse, till I could no longer withhold;
and bespeaking their silence and attention, was willing to relate to them,
how I came by my ministry; to which they listened with close attention.
Then I premised, as an introduction before I came to the matter itself,
that "`although in the thread of my discourse,
something might appear liable to an objection,
I entreated the favour of them all to hear me out,
as what I might say afterwards would perhaps solve their objections,
without giving me or themselves any interruption;`" to which, with one voice,
they all assented, as a reasonable and just request, and I proceeded as follows:

My father was a cordwainer, who lived by his trade of making shoes,
and died before I was a month old,
leaving my mother a small patrimony of about four pounds a year, to keep herself, me,
and one son more, who was about seven years old when my father died.
My mother gave me a religious education in this same way.
When I was fit to go to school, I was sent there until I was ten or eleven years old,
and then was taken from school and put to keep sheep: my earnings, though very small,
giving some assistance to my mother, who had bound my brother an apprentice.
I was kept close to attend the flock when needed,
and afterwards put an apprentice to a blacksmith, still going to our own meetings,
but did not understand the rudiments of the religion I was trained up in,
but was addicted to the pleasures of the times.
When I went to meeting, I knew not how to employ my thoughts, and often, yes, very often,
the greatest part of the meeting, for lack of a proper employment of thought,
I spent in sleeping; for the preaching, which was pretty much, I did not understand.
Thus two or three years of my apprenticeship I spent
with very little sense of God or religion.

But so it fell out, that a young woman came to visit our meeting, and in her preaching,
seemed to direct her words to me, which were to this effect;
"`A Quaker by tradition--you go from the meeting as you come to it;
and come to it as you went from it, having no profit by doing so;
but what will you do in the end thereof?`"
These words were so suited to my then state, that I was pricked to the very heart,
crying out in secret, "`Lord!
How shall I do to mend it?
I would willingly do it if I knew how:`" A voice in my breast replied, "`Look unto me,
and you shall find help.`"
From that time forward I found it true,
that what is to be known of God and of true religion, is revealed within;
and relying on the Lord,
who began thus to reveal his power in me and let me see
that I must depend on him for strength and salvation,
the Scriptures seemed to be unsealed, and made clear to my understanding; such as,
"`being born from above,`" and that which is to be known of God is made manifest in us;
and also that text which says, "`The kingdom of God is within.`"
The Lord opened my understanding by his Spirit,
to see the proper qualification and call of true ministers,
that it was not external but internal, and the heart must first be sanctified,
before the Divine anointing could be expected.
Thus for some time I went on in my religious duties with great success,
and I found I gained much in spiritual and Divine knowledge.

As I was going to meeting on that day commonly called Sunday, it came into my mind,
that if I was watchful and obedient, carefully minding to keep my place,
and to follow that guide I was now acquainted with, I should be made a teacher of others.
I proceeded on my way to meeting, and being sat down therein,
in a short time I felt the power of the Spirit very strong upon me,
to speak a few sentences.
But oh! the reasoning and excuses I formed in my weak mind,
that I might be spared from this work some time longer;
and the weight seemed to be taken from me for that time.
The trouble and uneasiness which I afterwards went through, made me enter into covenant,
that if ever the like offer was made me, I would give up to the heavenly vision.
The trouble of my mind affected my countenance so much,
that it gave my master reason to examine me, how it was: I gave him a candid account,
adding my fear that my offence was so great, I should be rejected as a cast-away.
But he comforted me, with urging various examples of the like kind, for my encouragement,
no way doubting but that at the next meeting the same concern would come upon me,
to which he advised me to give up, with a sympathizing spirit of love,
in comfortable exhortations confirmed by Scripture examples: and as he had said,
before I had sat in the next meeting an hour and a half, the same concern came upon me,
and I had now to deliver the same words with the
same authority as I did when in that meeting,
"`Fear not them which kill the body, but are not able to kill the soul:
but rather fear him who is able to destroy both body and soul in hell.--I say fear him,
who will terribly shake the earth,
that all which is movable may be shaken and removed out of the way;
and that which is immovable may stand.`"
This was the first appearance I made in public, as a preacher.
By this time I found, that the power of the Gospel was over them,
by their wiping of their eyes;
and I was assisted to go on with strength of argument and demonstration; adding,
that then I had nearly three years of my time to serve,
which I did with great faithfulness to my master; preaching a little at times,
but not very frequently, yet to the great satisfaction of my brethren.

Before my time was expired I found a concern upon me to travel abroad as a minister;
and I acquainted my master therewith, who had been as a father to me.
He told me, before I went on that errand, I must acquaint the elders therewith,
and lay it before the Monthly Meeting, setting forth the service thereof,
to take care of our poor, and to deal with offenders,
who were a scandal by their ill conduct to their profession,
and sundry other matters cognizable in those meetings, that they might judge,
whether my concern was right, and give me a letter of recommendation or certificate,
to signify their unity and satisfaction therein; which I did accordingly:
and with some very suitable advice to my then present infant state as a minister,
they gave me a certificate or a letter of recommendation, and signed it in the meeting,
as is usual in such cases.
I accomplished that journey, and was, at my return, called upon to give account thereof,
and to deliver up my certificate.

After which, in a short time, I had another journey before me, and by our discipline,
or church government, was obliged to go to the same meeting for a fresh certificate,
which was readily granted; and the brethren rejoiced at my improvement,
advising me to render the honour thereof where due.
At my return, I was obliged to attend the said meeting,
and give account of my travels as before.
This practice among us is judged needful,
lest anyone should swerve from their first foundation,
and undertake to preach without a right commission,
and so impose upon Friends who know them not.

In a little time I was concerned to take another journey,
and laid before the said meeting my concern, as above said, and had a certificate.
At my return, I gave account as before, and delivered my certificate:
after which I had a concern to visit this nation in this very journey,
and laid my concern before the said meeting, had a certificate readily granted me,
and pulling it out of my pocket-book, said, here it is.
At which, one of them took it, and, at the desire of the rest read it;
and it was returned me with a profound silence.
I proceeded to add, that I had visited all that kingdom,
where I found drawings in my spirit to go, and this, so far as I yet see,
is the last place; and now I must leave you to judge,
whether it is not reasonable for you to conclude,
at least that I think myself constrained by an Almighty power,
else how could I have exposed myself to such an unruly
mob as I have preached to this day?
Here I stopped; and one in the company asked,
if all our preachers came by their ministry this same way?
To which I replied, I could not give account how another man might receive his ministry,
but I have given you a faithful and candid account how I received mine.

My companion was full of matter to relate,
by giving them an account how he came by his ministry, but let in a fear,
that what he might add, would hurt the cause.
One of the company said, it is enough that we have heard,
and so he was very handsomely excused.

The night, by the time this was over, being far spent,
it being some time past the middle, a reckoning was called,
and they would not allow us to pay any part thereof,
but took leave of us with great affection; and the country gentleman,
who was assisting to our liberty, gave us a very kind invitation to his house,
which we received very thankfully; but being engaged in our minds for England,
had not freedom to go with him: so we parted in a very loving and friendly manner.
We being now left to ourselves, I had an opportunity to reflect on what had passed,
and to examine my whole conduct all that day; a practice I frequently used,
after a more than common day`'s service;
and indeed after every opportunity of an enlargement in my gift,
by experience finding the best instructor in my own bosom,
to show where I hit the matter or missed it.
In considering why I began so low as my father,
setting forth my manner of education and trade,
which seemed to have no relation to my call to the ministry,
I saw the reason thereof to be, that they might not think my ministry to have,
in the least, any dependance upon literature;
a qualification much depended on for the work of the ministry among them,
and some of them will not take any notice of any other sort: if a man,
for they will not admit a woman to have any part in this work,
be never so Divinely fitted by the Spirit, yet if he lack human learning,
it is all nothing with them.
Thus the wisdom of truth, which I did not see so plainly at first,
appeared to my understanding very clearly:
and on a close and narrow inspection into this day`'s work, I found inward peace,
a joy spring in my heart that I could not set forth by words.
My companion had more ease and true content than I feared he could have,
by reason of his not coming up in his service,
to let the company know how he came by his ministry, and by what authority he preached.

I have been more particular in the relation of this
day`'s work than I otherwise should have been,
as containing in it such signal marks of Providence; first,
that we should be detained in hold, just till the people from the country were come in;
and then set at liberty to say what the Lord gave us.
And thirdly,
that we had so seasonable an opportunity to explain our practice as to the ministry,
namely: the conduct of the Society towards them;
and likewise the service of our Monthly Meetings respecting the poor, marriages,
admonishing offenders, making up differences,
granting of certificates to such as saw cause to
remove themselves from one Monthly Meeting to another,
as well as to ministers.
Their showing so much kindness, and raising no objection to anything said on these heads,
plainly demonstrated their good liking and satisfaction therewith.

The next morning we set out for England,
and by the evening got among Friends in the border,
within the compass of Sowport meeting, and had some meetings, as at the border, Scotby,
Carlisle, and some others.
I came to my old master Samuel Parrot`'s, having no place to retire to as home,
but sometimes I was at Sedgwick, and sometimes quartered with my friend Robert Chambers,
and sometimes at Kendal, and at Gateside, at honest William Simpson`'s,
where I occasionally helped them in their business, he being a blacksmith.
I was now preparing myself for a journey into America, and was nearly ready;
and I had an opportunity to take my leave of the neighbouring meetings, as Dent,
Garsdale, Sedberg, Grayrigg, Kendal, Preston, with several others thereabouts.
That at Preston was the most memorable and solid,
the sense whereof continued with me all over America, at times.

I went from there to Yelland,
and many Friends came to that meeting from other places to take leave of me,
so that it was a very large and living meeting;
and I parted with my brethren in great love and unity.
I then came by Wray, Bentham, Settle and Airton;
that great and good man William Ellis being then living, and full of power,
having great and solid experience concerning the work of the ministry,
he was very edifying to me, by the wholesome counsel he gave.
James Wilson was with me, who was not at that time a public minister,
yet of great service in visiting families,
being closely engaged in spirit for maintaining good order and discipline;
and we being both very young in these things,
this worthy friend gave such advice to us both,
with respect to a faithful coming up in our services, that we could with good reason say,
that his words were like apples of gold in pictures of silver;
for a long time after the sense and virtue of them dwelt on my mind,
to my great advantage.
We stayed with him one night, and had a small meeting,
in which the preference and value I had for him,
together with an awe that was upon my spirit concerning
his great services and experience as a minister,
took such a place in my mind, that I was silent before him.
Next day we took our leave, and he brought us on our way a little,
heartily praying at parting, that I might be preserved in my place,
and return with safety.

James Wilson came with me as far as Leeds, where we parted,
and I went through Nottinghamshire and Leicestershire, visiting meetings,
where some time before I met with great trials and afflictions, and some were convinced:
my mind was strongly engaged to see them in my way,
and I had good satisfaction in that visit.

Having done this, I went by the way of Bitchin and Hertford, visiting meetings,
finding encouragement to go on:
but I still expected that I should be stopped by the Morning Meeting,
for lack of a companion.
I came to London the latter end of the tenth month, 1701,
being by letters advised that the ships would sail in a week`'s time, or very shortly;
but a war breaking out between England and France,
an embargo was laid on all shipping for two months,
so that there was no expectation of getting off.
I stayed in London about three weeks, visiting all the meetings in and about the city,
which gave the brethren a thorough taste of my service.
Some of my best friends advised,
that I should not lay my concern for America before the meeting,
until the General or Monthly Meeting of ministers did come round,
and in that time my service as a minister would be generally known.
I readily complied; and when the time came,
I went in great fear to lay my concern before that meeting,
being still apprehensive I should not be permitted to proceed,
for lack of a suitable companion; but as no objection arose,
they perused the certificates I had from the Monthly and Quarterly Meetings,
and did well approve thereof; and a minute was made,
appointing some Friends to prepare a certificate against the next meeting;
which was accordingly done, brought there, and signed.

All things now being clear for my going by the first opportunity,
it was thought proper to look for a ship,
which by the assistance of some Friends was done, but no likelihood of going quickly,
by reason of the embargo.

I had a desire to visit the west, in particular Dorset, Somerset, Bristol and Wilts,
but was at a loss for a horse, having sold my own soon after I came to London.
The Friend to whom I sold him, offered that I should have him for that journey,
which I accepted, and set out,
having in company a young man who had been bred at college, whose name was Samuel Crisp;^
footnote:[See Letters and Extracts from a Treatise Written By Samuel Crisp.]
a meek spirited youth, and rightly convinced.
When we got forty or fifty miles from London, he had strong inclinations to go back.
I made a kind of a running visit; and when I was at Bristol,
my friends there were exceedingly kind, and would willingly have had me gone from there;
but my prior engagement at London would not permit it.

I stayed there two weeks at least, and taking my leave,
Friends brought me on my way to Bath, Bradford, etc.
They returned, and I went on for London, and quartering at an inn at Hungerford,
not being easy to take any more meetings till I came to London,
I fell in company with a couple of tradesmen, who, when we sat down to supper,
complimented each other about which should crave a blessing.
At last they pulled off their hats, and one of them did it in some sort;
but my sitting with my hat on was such an offence,
that they began to reprove me very sharply.
I said but very little for some time until they had spent their reproach upon me,
and then I spoke to this effect, "`That the appearance they made,
just before supper was brought to the table, was so very void of grace in their hearts,
that I could not think it my place to pull off my hat to their formal prayer:
and besides, as soon as the words were out of their mouths and over,
it appeared to me that they were the same,
and I saw by their conduct that they did not understand the nature of true prayer,
which is to be performed both with the spirit and understanding;
and if you had not lacked both,
you could not pass such silly compliments on each other about it.`"
I was now very quiet, and they said no more to me.
But as soon as supper was over, and the reckoning paid, they left me with free consent,
for our company was unsuitable.

Next day I went towards London by Newbury, where I stopped at a funeral,
and so to Reading, and by Maidenhead to the city,
but found the embargo not yet taken off.
It being now pretty near the middle of the first month,
I visited some parts of Hertfordshire,
having my dear friend John Tompkins part of the time, and Samuel Crisp,
who was a sweet companion, having received the knowledge of the truth the right way.

About a week or two in the second month, orders were given the merchants to get ready,
and a convoy was to go with them: but for all this,
it was the latter end of the third month before we got off;
so I had an opportunity to visit the greatest part of Kent.
After we sailed from the Downs, we were put into Portsmouth harbour by contrary winds,
and lay there two or three weeks, which was very tiresome.
But all this time I never considered the danger of being taken by the French;
it did not so much as enter into my mind, until I came into Philadelphia,
where hearing that Thomas Story, Richard Groves and others, were taken some time before,
and carried into Martinico, a French island, I thought of it more closely.

I left England in the third month, 1702, about the time of the Yearly Meeting,
with peace of mind,
and wrote a few lines to be sent to the meeting of ministers in Kendal, or elsewhere,
in Westmoreland, my native place; which I here insert,
being the first fruits of that kind to my brethren.

[.embedded-content-document.epistle]
--

[.letter-heading]
To the Meeting of Ministers at Kendal, in Westmoreland.

[.salutation]
My dearly beloved brethren and sisters,

In that love which in time past we have enjoyed together, do I heartily salute you,
having in mind some few things to impart, as counsel and caution to us all,
including myself therein.

We who apprehend ourselves called into this public station of preaching,
ought closely to wait on our guide, to put us forth in the work.
And dear friends, I see great need for us carefully to mind our openings,
and go on as we are led by the Spirit; for if we over-run our guide,
we shall be confused, not knowing where, or how to conclude:
but if we begin and go on with the Spirit, we shall conclude so,
that all who are truly spiritual will sensibly feel that we are right:
then will our ministry edify those who hear it.

Dear friends, let us be singly and in sincerity devoted to the will of God,
whether to preach or be silent; for if we are not sensible of such a resignation,
we may set ourselves at work, when we should be quiet,
and so bring an uneasiness upon our friends, and a burden upon ourselves.
This conduct will shut up Friends`' hearts against our service and ministry.
And my dear friends, every time you appear in the ministry, when it is over,
examine yourselves narrowly, whether you have kept in your places, and to your guide;
and consider, whether you have not used superfluous words,
that render the matter disagreeable,
or such tones or gestures as do not become the work we are about, always remembering,
that the true ministers preach not themselves, but Christ Jesus our Lord.
Let us bear this in mind, that neither arts, parts, strength of memory,
nor former experiences will, without the sanctification of the Spirit,
do for us to depend upon.
Let us therefore, I entreat you, keep to the living fountain, the spring of eternal life,
opened by our Lord Jesus Christ in our hearts.

I also desire that you would not neglect your day`'s work,
in visiting the dark corners of the counties about you:
but be mindful of your service therein, as the Lord shall make way for it.

The things above written have been on my mind to communicate to you, my dear friends,
with desires that the God and Father of our Lord Jesus Christ may be with your spirits.
Amen.
Hoping also, that I shall not be forgotten by you,
in your nearest approaches to the throne of grace,
in your supplications to the God of the spirits of all flesh;
remembering me that I may be preserved by sea, and in the wilderness,
through the many and various exercises and baptisms,
that I may be permitted to undergo for the service sake;
and that I may be preserved in humility and self-denial, under the power of the cross,
the most beautiful ornaments a minister can ever be clothed with;
that if it please Him we should meet again, our joy may be full in the Holy Spirit,
which is the fervent prayer of your exercised friend and brother,

[.signed-section-signature]
Samuel Bownas.

--

This was written in the second month, 1702, and left with my friend John Tompkins,
not to send it until he heard I was gone off.
