== Chapter IV

I was now at liberty, after having been a prisoner three-hundred and forty-two days;
but not having freedom to go away, I stayed sometime, visiting every corner of the island,
and had very large and open meetings.
The people were thoroughly alarmed, and I found by experience,
that my long imprisonment had made me more known and regarded,
so that they flocked in great numbers where I was,
and Friends were careful that they should have notice.
They appointed a meeting for me at a place called Cowneck, at one Jacob Doughty`'s,
there not having been any at that place before;
and as I lay in bed at my dear friend John Rodman`'s, at the bay side, the night before,
I dreamed that an honest Friend was fishing in a large stone cistern,
with a crooked pin for his hook, a small switch stick for his rod,
and a piece of thread for his line; and George Fox came and told me,
that there were three fishes in that place,
and desired me to take the tackling of the Friend,
for that he lacked skill to handle the matter: accordingly,
I thought the Friend gave me the rod, and the first time I threw in I caught a fish:
George Fox bid me try again, for there were two more in that place; I did,
and took up another: he bid me cast in my hook once more; I did, and took the third: now,
said George, there is no more there.
This dream was taken from me as if I had not dreamed at all.
The next day we went to the meeting, and were a little late,
as the tide and high fresh-water obliged us to ride the furthest way,
and when we came into meeting a Friend was preaching on universal grace;
but in a little time he left off, and my heart being full of the matter, I look it up,
and we had a blessed powerful meeting, and all ended well.

I returned with my friend Rodman to his house,
and in our way my dream came fresh into my memory,
and that evening I told it to my friend Rodman,
and gave him a description of George Fox`'s features and bulk, as he appeared to me;
and he said I had a very just and right apprehension of him.
He had been much with George Fox when he was in Barbados,
and was well acquainted with him; adding,
this remarkable dream shows some good done there this day.

After I was clear of Long Island, it being with me as if I had just set out from home,
I found a necessity to convene the elders, and lay before them my concern,
as I did when I came from home;
and in a tender and fatherly way they took care to examine what I might be in need of,
both with respect to linen, woollen, pocket money and a horse;
for as yet I had not bought one, never finding freedom so to do; but Friends,
to their praise be it spoken, assisted me from stage to stage.
When I was in prison I saw I had no need of a horse,
and admired the kindness of Providence in restraining me from having one till needed;
and I had money plenty by the trade of shoe making, so that I needed none,
nor did I lack any necessaries for the journey but a companion.
Several Friends offered themselves very freely to travel with me:
but my dear friend Samuel Bowne had a concern to visit the eastern parts of New England,
who had a fine gift, but not very large; and I was very glad of his company.
We set forward in the beginning of the twelfth month, and the winter not being broken up,
we rode on the ice into Connecticut colony, over some broad rivers,
New London being the largest, but we had no meetings for nearly two hundred miles.
The people being mostly rigid Presbyterians,
counted it a great crime to be at a Quaker`'s meeting, especially on the sabbath-day,
as they term the first-day of the week.
But coming into Narraganset, we were among Friends again.
We went for Rhode Island, and there Friends were very numerous, and we had large meetings.
There was a marriage of a young man, whose name was Richardson,
with a daughter of Thomas Rodman, a man of the first rank in the island,
so that we had the governor, Samuel Cranston,
and most of the chief men in the government at the marriage,
and we had a precious living time, which gave me great encouragement.
The governor was very kind, and queried with me about my imprisonment,
he being a great lover of Friends, but not a professed one himself.

From Rhode Island we went towards Hampton and Dover, having but few meetings,
as we purposed to return to the Yearly Meeting in Rhode Island.

When we came to Dover we had a pretty large meeting, but were both silent;
at which I was somewhat amazed, it being new to me.
Another meeting was appointed next day, some little distance from Dover,
which was much larger; my companion said something, but very little,
and was uneasy that he said anything.
I was quite shut up; and after meeting I was exceedingly comforted,
being filled with Divine sweetness and heavenly joy,
that I was preserved and did not force myself to offer.
They appointed another meeting the day following, some distance off,
at which I found myself quite shut up, and held back as it were from saying anything,
and my companion was also silent, who after meeting looked upon me very innocently,
saying, "`Samuel, what do you think these people will say,
that we should come so far to appoint meetings among them, and have nothing to say?`"
It just then came livingly into my mind to reply, Fear not, have faith,
nothing doubting but we shall have enough to say before we leave them.

Our next meeting was to be in the centre of the meetings which we had attended before,
in a large house, but not big enough for the company by far,
and the country was all alarmed, so that it was a very large meeting indeed;
and it being a time of war with the Indians,
the people brought such weapons as they had to meeting,
so that when we came to the meeting-house, I was surprised to see so many fire-arms,
and other instruments of war, standing against the meeting-house wall.
However, I was before told, that it was the custom of other people to do so;
and I found that those fire-arms and warlike weapons, belonged to other people,
not to Friends who were come to meeting.
The meeting was very quiet; and we sat a long time in silence,
which put me on examining my conduct, and looking back to see how it was with me;
but finding no uneasiness for anything I had done before, to cause me to be thus shut up,
I came to this conclusion and resignation, that I was but a servant,
and could of myself do nothing;
secretly praying that the Lord would give me patience not to be uneasy,
if he had nothing for me to do, and if he had, there I was, ready and willing to do it.
Thus I settled down diligently waiting for Divine direction.
In a little time a word came with life, and I stood up with it, to the effect following;
"`The Lord`'s time is the best time, and let us not grow uneasy to wait for it;
for when he opens none can shut,
and when he shuts none can open;`" enlarging on this subject a little more.
We had a very glorious meeting,
in which I was largely opened in sundry branches of the doctrine of Christ;
and I had not seen very often greater tenderness than was at that time among the people;
for the war with the Indians had humbled them to such a degree,
that truth had a very great reach upon them indeed, and the meeting ended well.

Immediately I found an uncommon and weighty concern
to request the ministers to come together,
which they very readily complied with, and they were a considerable number,
but not all thoroughly baptized into the work.
My companion was very prettily opened, and we had a very suitable service among them,
and saw clearly the reason why we were so shut up in silence;
some of them were got into an extreme in preaching and praying,
and would continue meetings to an unseasonable length,
likewise preaching and praying at table;
which gave great uneasiness to some sensible Friends among them,
but they could not redress it till after this opportunity.
They themselves saw they were wrong in doing as they had done,
and got out of this extreme, which was a degree of ranterism,
being attended with a spirit of opposition against
the order of Friends in Monthly and Quarterly Meetings.

Having finished our service, we returned back to Hampton, and had several meetings,
and so to Rhode Island Yearly Meeting, which was very large and to good satisfaction.

From there I went by sea to several islands, as Martha`'s Vineyard, Nantucket,
and some others.
In Nantucket I had great satisfaction, for the people, not joined with Friends,
were moderate Baptists, and came generally to meetings, their preacher also with them,
who after meeting raised some objections against us,
which he had gathered from our adversaries`' books,
and that which he pitched upon chiefly, was about prayer,
that we did not pray to God in the name of Christ, but in our own names.
I told him we looked upon it to be our duty to pray to God in Christ`'s name,
and as his name is understood to be his power,
we dared not presume to pray to the Father,
but as the wisdom and Spirit of Christ gave us utterance.
He said it was Gospel truth in its primitive purity.

The governor sent for me, and we had an opportunity to confer about our principles,
and he seemed much pleased with what I had to say.
Having finished my service I returned to Rhode Island,
and found some were contriving to have me taken up, by informing the governor against me,
as though I was a transgressor, by preaching, as they said,
against baptism and the supper of the Lord, as they call the bread and wine.
But the governor being at the meeting himself where this supposed offence was given,
quickly saw that the arguments used against the present practice of the English church,
as well as of Presbyterians and Baptists, had so much Scripture and reason on their side,
that it was vain to attempt to confute them;
he therefore thought it their wisest way to let the matter alone.

After this I made another trip to the eastward, my dear companion being returned,
and in my way back to Dover, visited meetings as they came in course;
and also the meetings where I had been before, and had sat in silence in some of them,
but I had now large and good service and great satisfaction among them, the more so,
as they now saw it their places not to preach in every meeting,
but to wait for the constraint of the Divine word before they spoke.

From there I went to Strawberry Bank, a haven where much shipping resort for masts;
and when clear of those parts returned to Hampton, Haverhill, Exeter,
and other towns where meetings had not been kept, and among them to Newbury.
A man who lived in that place, being newly convinced,
was very desirous of a meeting at his house, which I consented to;
and when the time came, his wife not being pleased that we came to hold a meeting,
would not permit us to enter the house, but kept the doors locked against us, being,
as was said, advised to it by some of their teachers.
I took a turn round the house,
and happened to have some conference with her at the window, first assuring her,
that we had no design to put her husband to any charge,
but only to let us have house-room for about two hours to hold a meeting, adding,
that it illy became a wife to keep her husband out of his house at such a time;
promising her, that if she would let her husband in,
not one of our people should come in with him.
By reasoning the case with her, after a little while,
she opened the door and would have us to go in, but I had not freedom.

A place to hold the meeting was then got ready, being a large building like a barn,
where the Friend and his men built boats for shipping, that being his calling,
and we sat down, being a few Friends, and in a little time many people came,
among whom, as it was said, were six preachers.
After some time a young woman stood up who had a good gift,
but the people behaved very rudely, so that it put her out of countenance,
and she sat down.
Then stood up Lydia Norton, a famous minister, none more so of that country,
who had an excellent gift, and knew how to conduct herself in it;
but all this did not avail, the people grew worse and worse in their behaviour.
Lydia having a very strong manly voice, extended it very loud, but to no purpose,
for the people were as loud as she, calling for a dram,
and sporting themselves in their folly, so she sat down.
A young man, called Joshua Puddington, then stood up; and the people behaved worse,
raking up his former faults, and calling for a can of flip,
for he could drink as well as they; he having been a companion with them in fishing,
they made very free with him, so he shut up.
By this time the meeting was exceedingly numerous, and continued enlarging very much.
It came into my mind, to stand up and take out my Bible, which I did,
for I always travelled with one in those days,
finding a considerable service in it at times.
I opened it, and put my finger in it, as though I would take my text,
but I said nothing for some considerable time, till all was quiet.
The people continued in great confusion for a while, till some of them observed my book;
then they began to quiet and to still one another, urging as a reason for it,
that I had the word of God in my hand, such a great regard they paid to my Bible.

In a little time all was quiet and still: then I opened my mouth and said,
I am an Englishman; and enumerated the many lands and places I had travelled in,
but had never met with any people of such a behaviour as these were;
referring to them to advise me what account I must give
of the people of Newbury at my return into England.
A comely, gentleman-like man said, in excuse for the behaviour of the people,
"`As for women`'s preaching we hold it unlawful, because St. Paul has forbid it,
therefore we think it not proper to give them a hearing: and as for the man,
we know him perhaps better than you, and cannot think him qualified for that undertaking;
but you seem to be a gentleman of sense, and we will hear you.`"
I replied, that as for women`'s preaching, it is a disputable point from Paul`'s words,
yet nevertheless, if any of you, after this meeting is over,
are willing to hear what I have to say in favour of it,
I shall be willing to give you the best account I can, why I think it is lawful;
and if any of you can show better reasons against it, I shall as willingly hear them.
And as for the young man, I grant you may, as he is a neighbour,
have had a better knowledge of his former conduct in life, than I can pretend to;
but allowing that he may, in time past, have been loose,
that argues not against giving him a hearing: for how know you, but that as Saul did,
he might condemn his past life and give you an example, by his present conduct,
to reform,
for which reasons you ought to have heard with patience what he had to say to you.
The same gentleman replied, "`I said very right, they ought to have heard him:
but I pray you speak what you have to say freely;
and I charge all present to make no disturbance or interruption; if they do,
in the queen`'s name I will commit them.`"
By these words I found he was in the commission of the peace; and then I began,
with saying, that religion without righteousness was useless,
and could not profit those who possessed it.

And going on,
I came in the course of my service to recite the great improvement
true religion made in the minds of those who lived in it,
by giving them power over their lusts and passions; repeating that text in James 1:26,
"`If any man among you seem to be religious, and bridles not his tongue,
but deceives his own heart, this man`'s religion is vain.`"
One out of the throng said, "`Sir, you impose upon us, there is no such text.`"
I made a full stop, and turned to it; and many Bibles then appeared.
I repeated chapter and verse, and they turned to it.
Then I asked them, if they had it?
They replied, they had.
Then I read both the twenty-sixth and twenty-seventh verses,
and asked if it was so in their Bibles; they answered it was.
I then desired them to consider, whether I that repeated the text,
or he that said there was no such text, was most in the right.
I went on with my opening, carefully minding my guide;
and in the course of the doctrine I had in my view, I came to treat of faith,
and distinguished between true and false faith, showing,
that notwithstanding we might give our assent to
the truth of what was called the apostle`'s creed,
or any other made and drawn up by men,
and might be zealous to dispute and contend for the truth of these creeds,
in the wording of them; yet for all that, if we did not lead Christian lives,
we were still but unbelievers; "`for faith without works is dead,`" as the text tells us.
At these last words one cried out, "`you impose upon us, there is no such text.`"
I immediately stopped and turned to it, and quoted it, and all who had Bibles made search.
There being a profound silence, I read the text, asking, if it was so in their books?
They all replied, it was.
I made the same remark as before; and then I went on,
distinguishing between true and false faith, plainly demonstrating from Scripture,
that faith was very different from what many took it to be.
Truth was eminently preached that day,
and there was a considerable tenderness among the people, and the meeting ended well.

When I came out, the gentleman came to me, and I acknowledged his kindness towards us;
and it suddenly came before me to speak with a loud voice in the street, and to desire,
that if anyone was at a loss, and did not understand any part of what I had said,
or thought I had spoken anything not agreeing to Scripture,
I would then desire them to let me know it,
and not misrepresent anything I had said when I was gone.
The gentleman made answer on behalf of the people thus; "`None can have any objection,
for I never heard the word better preached in my time.`"
I told them I was ready to let them know my reasons, why I thought women,
who were properly and duly qualified, might preach lawfully,
on condition I might have their reasons to the contrary.

The gentleman, who undertook still to speak on behalf of the company,
who stayed to hear and see, said,
"`There is none here will undertake to dispute with you upon this,
or any other point of religion:
but I desire you will favour me with a promise to have another meeting here,
and I will get some of the best writers the country will afford,
to take down your sermon.`"
But he little knew that this was no great inducement to my coming there again: however,
he pressed it very close, which I excused in the best manner I could;
as not knowing that I should or should not:
and after earnestly pressing me to go to his house to refresh myself,
which I likewise desired to be excused in, as we had given expectation to go to our inn,
and could not stay much longer, because night would come upon us,
we parted in good respect and harmony to all appearance;
and my heart was filled with thankfulness,
and comfort that we got over that day`'s work so well.

Being clear of these parts I returned, visiting the meetings of Friends,
and other places; in particular Cape Ann, where I met with great opposition;
the case was thus:

At Cape Ann sundry Friends were desirous of a meeting, and more so,
because several young men, who were Friends, resided there while they built a ship.
Accordingly I went and several Friends with me.
We got there early on a seventh-day, and gave notice of a meeting,
which was to good satisfaction, and being a new thing, it was very large.
The people desired another, which was granted; and between meetings,
some gave their preacher notice, who had but a small congregation that day,
advising him to look after his flock, it being his duty.
Accordingly he came before the meeting ended, with several of his elders,
and was very noisy.
First, he would prove water baptism, from the text, to be an ordinance of Christ.
I replied; what form of water baptism would he prove so?
To which he answered evasively, not being willing to be tied to one more than another.
But after some further pros and cons,
he was by his own people pressed to vindicate his own practice, which was sprinkling.
Then he said, that was plainly proved by our Saviour`'s words,
"`Let the little children come unto me,`" etc.
I showed him his mistake; and that without perverting the text,
it could not be applied to sprinkling infants,
but referred to the state of innocency that such should experience,
to be like little children in their minds, free from all vice and wickedness,
before they were prepared for the kingdom of heaven,
which sprinkling with elementary water could not do for them.
I opened more at large the state of the new birth and regeneration;
in doing which he would often break in upon me, but his own people cried shame,
for the interruption he gave, adding, when I had done he should be heard.
But he was so much out about the proof of sprinkling infants by our Saviour`'s words,
that I found he was very weary of the dispute, and willing to drop it,
and would go upon perfection.
I urged him to clear up baptism first, as we were upon it,
but he urged that both he and his people were satisfied about it.
I then asked why he began upon it?
To show us our errors, he replied.
So finding nothing was like to come of it, but tumult and noise, we pressed it no further.

Then he charged us with being in an error about perfection.
I desired to know wherein, which he was very unwilling to show.
One of his hearers reproved him very sharply,
for making so many charges of supposed errors, and proving nothing; adding,
that it did not suit his station as a minister, whose work it was, or ought to be,
to set people light, and to show them wherein they were wrong,
and not to heap up charges of errors, without showing any proof that they were so,
which could by no means be the way to convince and inform those in error.
At this pertinent rebuke he left us, some, though very few, going with him.
I then desired the people to sit down, and be still; with which they readily complied;
and after a short pause, it was with me briefly to speak to each point, explaining,
as well as I could, in so short a time,
the doctrine of outward baptism to be but a figure of the inward,
as outward circumcision was of the inward, that is, of the heart;
and likewise setting forth the new birth and regeneration
in as clear a light as time would permit;
with perfection and election and reprobation; all which,
though but very briefly touched upon, took up a considerable time,
so that the night was considerably above half spent.
When I had done, the people were exceedingly quiet and civil,
and declared their satisfaction, wishing their minister had stayed,
for he could not have gainsayed what was spoken to each point.
A few of them stayed a short time after, desiring they might have more such meetings,
and we parted in much love and sweetness;
in particular the elder who reprehended the minister, as he called him, said,
"`Religion could never prosper,
so long as it was made a trade to get bread by;`" and he seemed convinced,
that both the doctrine and practice of their people were inconsistent
with primitive religion and our Saviour`'s doctrine.
Thus we closed our conference and took leave.

From there I returned towards Rhode Island, taking my leave,
not expecting to see them again this journey.

I went from Rhode Island to Block Island, where were a few Friends,
but much hurt by lewd company, such as privateers-men and the like,
but all the inhabitants came to meeting, and were very sober and willing to hear.
One Ebenezer Slocum, a fine minister, was with me in this island,
and we had three or four meetings among them.
I returned to Rhode Island again, and was at two large meetings with Friends,
and took my solemn leave.
I had a meeting in Conanicut,
at which were many Friends from both Rhode Island and Narraganset;
a fine solid meeting it was.
Then I went to Narraganset, and had two or three meetings,
and took my leave and came to New London, and so for Long Island,
and at the east end of it had some meetings,
where both Friends and others were glad of my coming.
I had many meetings in several places, and there was great flocking to meetings,
and very great openness among the people in those parts.
A Friend told me that George Keith had proposed,
as a means to prevent the growth of Quakerism, as he called it,
the making of a law to restrain Friends from travelling, save to their own meetings;
for he said,
it was the travelling preachers that kept the Quakers so strongly in countenance.
This was thought by some hot bigots to be a likely
way to put a stop to the increase of the Quakers,
who had infected almost the whole country;
but by people of moderation and sense it was hissed at.
There was a very large meeting at Westbury on the plain, called a Yearly Meeting,
to which most of the Friends of the island,
and many of the better sort of the west end of it came,
it being known that I should take my leave there; and I was very much opened,
in setting forth the difference between the true and false ministers,
and the true and false worship; and there being some of Keith`'s friends,
they threatened to have me taken up again; but I found that Truth was over them,
and they could do no more than show their teeth--they could not bite.

After this meeting I left the island,
and went into the Jerseys by Staten Island to Woodbridge, Shrewsbury, Crosswicks,
and to Egg-harbour, visiting Friends, and so back to Philadelphia to the Yearly Meeting,
which was very large, and I had good satisfaction in being there.
Here sundry of my dear friends from Long Island met me, in particular,
my dear friend Samuel Bowne and his worthy wife, who was a mother in Israel;
with this good woman I left fifteen pounds to defray some
charges my good friends had been at about my imprisonment,
for chamber rent, and a present they made the keeper,
which I was unwilling to have them pay, having money plenty,
that I earned in prison by shoe-making.
But my dear friends would not permit it, but returned it to me by Samuel Bowne,
who used many arguments, that it did not look well for them to allow it,
and would be a reproach on them,
and look as though I did not count them worthy to treat me as a minister;
so rather than bring an uneasiness upon my brethren, I took it again.

From Philadelphia I accompanied my friends on their way home, about thirty miles,
as far as Crosswicks, visiting that meeting and Burlington,
took my leave there and came to the Falls meeting,
and visited all the meetings on that side of the river,
down through the Welsh towns to Philadelphia.
Taking my leave there also, I went to Concord and Chester,
visiting meetings towards Maryland: a Welsh Friend, named Ellis Pugh,
who proposed to go over sea with me to visit his friends in Wales, was now with me,
and we came into Maryland, and took our passage home with a Friend,
whose name was Daniel Maud, but he could not be ready to sail under two months;
so my companion returned to his family, and I visited Virginia and Carolina,
and had good satisfaction.

I took my leave and returned to the ship, and found my dear friend Ellis Pugh,
labouring among Friends in Maryland.
In a little time the ship fell down the bay, where the fleet made up, waiting for convoy,
and in a few weeks the fleet came together, being very large;
but many ships had taken so great damage by staying so long in the country,
that they could not bear the sea, and several foundered, and some put back to unload,
and have their ships repaired.
We had a long passage, but arrived safe, landing at Portsmouth, in the tenth month, 1706,
visited a small meeting at Portsmouth, and took coach for London,
where I stayed to visit the meetings in the city,
and afterwards went down to Wiltshire Quarterly Meeting,
where was some uneasiness among Friends, but happily reconciled.

I then went into Somersetshire to visit my friend,
to whom I was under an engagement of marriage as before hinted,
where I remained a few weeks, and visited meetings in that neighbourhood,
and so went for Bristol, where I stayed a week or ten days,
then went pretty directly into the north, which I called my home,
and glad I was to be among my old friends again.

Having visited the meetings in our own county, and delivered up my certificate,
giving an account of my travels,
at the next Monthly Meeting I acquainted Friends with my intended marriage,
having a few lines from under my intended wife`'s hand, as likewise from her parents,
showing all their consent.
And I desired a certificate from the meeting, and persons were appointed,
as is usual in the like case, to make inquiry of my clearness.
In the interim the Quarterly Meeting for Cumberland happened to be at Carlisle,
where I went.
The meeting was exceedingly large, and I had great satisfaction in being there.
I visited a few meetings in Cumberland, but was limited for time,
being obliged to be at the next Monthly Meeting to
have my certificate to present in Somersetshire,
in order to proceed towards my marriage.

By this time the spring was advanced,
and my worthy friend James Wilson offered his company to go to my marriage;
accordingly we set forward, and took in our way the Yearly Meeting at Middlewich,
which was very large, and several weighty Friends were there:
I had great satisfaction and comfort in being there.
We took meetings as they suited, in our way;
and I found my companion under a great concern to speak something in meetings,
but very backward and reluctant to give up to it.
I gave him what encouragement I could; and in Tewksbury meeting,
after some struggle in himself, he stood up, and appeared very much to his own,
and Friends`' comfort, and so in every meeting after till we came to Bristol;
and indeed he appeared more like an elder in the work than a babe.
At Bristol he did not get through what he had before him to his liking,
and sat down under great discouragement, but I cheered him up as well as I could,
by giving him an account of my experiences;
and when we came to the little country meetings again, he did finely,
and gathered strength and experience in the work.

We came to my intended father-in-law`'s house, and went to their Monthly Meeting,
where I and my friend proposed our intended marriage, which was taken notice of.
Bristol Yearly Meeting coming on, we went there, and met our worthy friend Thomas Camm,
who intended to be at our marriage.
After the Yearly Meeting was over at Bristol,
Thomas Camm took a meeting or two in the way, but my friend James and I returned back,
in order for me to get clear of the Monthly Meeting,
and likewise to provide ourselves necessaries for the wedding,
which was to be accomplished the week following, at a meeting on purpose at Puddimore,
and it was a very large meeting, several public Friends besides Thomas Camm being there.

The Yearly Meeting at London coming on, I stayed but a few days with my wife;
I would have had her gone with me, but her mother was taken ill of a feverish disorder,
and was very weak, for which reason she was not easy to go;
so I was obliged to leave her to nurse her mother, who in a few days grew much better.
I had a sweet opportunity with the family, and one or two other Friends in her chamber,
and the spirit of prayer came on James, and he was drawn forth very largely,
and very devoutly.
After which, not without considerable reluctance, we parted for a short time,
and James and I set out for London, and that meeting was very large,
and Friends there were willing I should give some account of my travels,
which I was much afraid of; but being called upon in the meeting, I did it,
and came off better than I expected; Friends expressing their approbation of it.

As soon as the meeting was over, dear James and I had a heavy parting;
but as I was going to my wife, that helped to cheer my heart a little.
I came directly home without taking any meeting, having my dear friend James Salter,
and others who had been at the Yearly Meeting, in company.
I stayed with my dear wife, and went very little abroad for more than twelve months,
having very great comfort and satisfaction in my married state,
my wife being a true sympathizer with me in the exercises which I often was under,
of one kind or another.
Sometimes I feared how we should go on in the world, and she would often say,
if we get but little, we will spend less; and if we save a little out of our gettings,
we shall do well enough, I am not at all fearful of it, neither would I have you to be.
I was jealous that my ministry was not so living as it had been before I was married;
and making my trouble and uneasiness about it known to my wife,
she would endeavour to dissuade me from such thoughts, adding,
there was no reason for it; so that I found her to be a help-mate indeed.

Finding a concern to visit Ireland, I acquainted her therewith,
and she gave me up so freely and cheerfully, that it was like a cordial to me;
saying she expected I would often leave her,
and that she had resolved in herself before marriage,
she would never hinder my ministry if she could possibly avoid it,
and she hoped the Lord would strengthen her, and make that easy to her.

About the fifth month, 1708, I applied to the Monthly Meeting for a certificate,
which I obtained, and then took shipping at Minehead, and landed at Cork,
where I stayed two or three meetings to good satisfaction.
I then went to Charleville and Limerick,
visiting the meetings along that side of the nation to Coleraine,
and I found very hard work in many places, and in some meetings was quite shut up;
but where the people who did not profess with us came in plentifully, it was not so,
there being an open door.
That worthy Friend, and heavenly-minded, meek, and divine preacher, Gilbert Thompson,
was there at the same time; and when we conversed about it, I found he was much as I was,
shut up and found it very hard work in some places to get forward;
and as he was in experience and age much my superior,
I asked what he thought might be the reason,
why it seemed more dead among Friends in this nation now, than in some other places?
He gave this as a reason,
"`That the professors of truth in that nation were very strict and exact in some things,
and placed much in outward appearance,
but too much neglected the reformation and change of the mind,
and having the inside thoroughly cleansed from pride and iniquity;
for you know,`" said he,
"`the leaven of the Pharisees was always hurtful to the life of religion in all shapes.`"
Yet nevertheless we found a brave living people in that nation,
and great encouragement to visit fresh places.

I came from Coleraine to Lurgan, Mount-Allen, and sundry small meetings thereabout,
as Hillsborough, Lisbon, Raffer Island, and so to Drogheda,
Friends having a meeting house in that town, but few came to meeting,
there being no Friends in the town except two men.

From there I went for Dublin, then visited the meetings towards Wicklow, Waterford,
and so to Cork, and had a large meeting at Kinsale,
it being the first meeting in the meeting house that Friends had built there.
Friends in that kingdom are highly to be commended,
in not sparing charge for accommodating meetings,
either by building or hiring places for that service.

By this time the Half-yearly Meeting at Dublin came on,
but nothing very remarkable happened there.
I took my leave of Friends, and when clear, I left the city,
and my dear friend Joseph Gill, accompanied me about three weeks.
He did not then appear as a minister in meetings,
but was under great exercise and the influence of Divine goodness,
which I was satisfied would be manifested by his
coming forth in the ministry in due time,
which accordingly came to pass; for in a few weeks after his return,
he appeared very acceptably in the ministry, and became a serviceable man in the work.

After we parted I went for Cork, and took shipping for home,
but the wind not favouring us for almost three weeks, gave me some uneasiness,
because I had written to my wife, that I intended coming sooner.
I heard afterwards that some of our neighbours had reported,
that I with the ship was taken into France; but my poor wife bore up bravely under it.
When the wind sprung up fair, the master set sail,
and we were but just got clear of the river before it veered against us;
so the master proposed to fetch Waterford,
and thought it would be better to do so than go back to Cork.
We all agreed, and got there by the close of the evening, being seventh-day;
I stayed the first-day meeting, which was very much to satisfaction,
and I was opened in the excellency of the Gospel.
On second-day we set sail again, and got into Minehead in about forty-eight hours,
and I posted home by Bridgewater,
and met with a hearty and kind welcome from all our family, more especially my dear wife,
having spent in Ireland somewhat more than eighteen weeks.
It soon got abroad that I was come home, and many Friends,
from several neighbouring meetings, came to visit me,
and we had great comfort in one another.

I had now nothing to do but visit the meetings around me, which were pretty numerous:
yet one thing came closely upon me, which was,
to put myself into some business to get bread.
Some proposed one way, some another.
London and Bristol were both mentioned, but I could not see my way to either of them;
and what I should do in the country, being ignorant of farming, I saw not yet.
At last it was proposed that I might with a little
charge put up a conveniency to make a little malt,
in which, when an apprentice, I had some experience, being then used to it.
I accordingly did, but my stock was very small, and some kind friends lent me some money.
I found it to answer better than I expected, so that I was encouraged to proceed;
and in about three years time I found it answered very well,
so that I went on with pleasure, and took great care,
and was very diligent in my business,
and in attending all meetings that I could reach in a morning`'s ride,
as I found a concern so to do.
The comfort and happiness I enjoyed was great,
for I could entertain my friends with a lodging and other necessaries in a plain way,
which was very agreeable to us both; and most Friends who came,
took a bed with me one or two nights, as best suited their conveniency in their journey.

In a little time a storm arose:
the parson of the parish having had nothing from our family for thirteen years and upwards,
for his small tithes, and other church dues, as he styled them,
got a summons for me to meet him before the justice;
but before the time came I wrote him a few lines to know his demand,
and he wrote me a long letter in answer, to which I replied.
All which are annexed.

The time came,
and some other Friends were convened by other priests
from other parishes at the same time.
When I was called, there were two justices, Edward Phillips, Esq., of Montague,
and Harben, Esq., of Newton.
Phillips was very rough and boisterous in words, and Harben altogether as mild,
using many arguments to persuade me to pay the demand myself,
or allow some other person to pay it,
being very earnest that I should allow him to pay it for me,
and he would not desire to have it all together;
supposing I might not so well spare what the parson demanded at once.
I told him I was very much obliged to him for his kind offer,
believing his intention was to serve me, but I could by no means accept it,
without injury to my own mind, it being a matter that concerned my conscience,
which I desired to keep void of offence towards God.
He took me into another room, and was very earnest to have it made up; urging,
"`it was so much in arrears, that it was beyond their power to end it,
and it must be put into the exchequer, and that would be very chargeable,
which,`" says he, "`must fall upon you at last.`"
I told him that I could do nothing to make it up; and having conferred some time,
we went in again, and he spoke to the effect following,
"`That he was very sorry he could not serve us,
as we were both his neighbours and friends,`" meaning the parson and me,
and told the parson "`it would be uneasy to us both;
and would have us end it between ourselves.
I said, if it were a matter of just debt that I was satisfied was my neighbour`'s due,
I should soon end it with neighbour Ray,
and be as willing to pay as he was to receive it; but as it was not of that nature,
I could by no means do it.
So I was dismissed, and in a little time served with an exchequer process;
and in a few months after, in the next term, I was taken up in my way for Bristol,
where I was going about my business, and put into jail.
But when the parson had got me there he was very uneasy indeed,
so that he could not take his rest, and told his attorney, "`If he lost all his claim,
he could by no means keep me there,
for he had no rest or quietness of mind night nor day.`"
Accordingly the attorney came to the keeper in less than ten days time,
desiring him to let me go home to look after my business; which I did,
and in a few days went my journey to Bristol; and when I had done my business there,
took a little turn into Wiltshire, and spent about two weeks in visiting meetings,
and so returned home.

I informed my friends at the Meeting for Sufferings in London, how it stood;
who advised me, that the parson could not proceed further,
as he had taken me up and put me into jail: so I heard no more of it all that winter;
but in the spring a distant relation of our family came to my wife when I was from home,
and desired her to lend him ten pounds, for he was going to a fair,
being a considerable grazier.
She had no thoughts about the parson`'s demands, that being a much larger sum,
and he being a dissenter, and having done me the like favour, she lent it him,
and he gave her his note accordingly.
My wife, when I came home, told me what she had done, and I said it was very well,
mistrusting nothing of any trick in the matter;
but as he came in my absence to borrow it,
so in like manner he came in pretence to pay it,
addressing himself to my wife to this effect; "`Dear cousin,
if you can help me to that note, I had best pay it; you know I borrowed it of you,
and shall pay it to you.`"
So she very innocently brought his note, and he tore it immediately;
and putting his hand into his pocket, took out and threw down to her,
the parson`'s receipt for the fen pounds, in full of all demands for tithes to that time.
My poor wife was under a very great surprise, urging,
it would be a very great uneasiness to me.
"`Your husband,`" said he, "`is we allow, a man of sense,
but in this he is a stubborn fool; and I would have paid it out of my own pocket,
rather than he should have ruined you and himself,
which this exchequer suit would soon have done, if it had gone on;
for his original demand is fourteen pounds and upwards,
and he has been at forty or fifty shillings charge already,
and you must have paid that and ten times more if it had gone on,
which now I have cleared for ten pounds; I think you are exceedingly well off.`"
"`Ay but,`" said she, "`we look at inward peace more than all that,
and I shall be blamed for being privy to the contrivance,
and beget a jealousy in my husband about other affairs.`"
"`Oh! my dear cousin, trouble not yourself about that,`" said he, "`for I can clear you,
that you are as innocent of it as a new born babe:
and I know I could not have brought it about with your husband,
for he would have started so many questions,
that I could not possibly have brought it about any other way,
than by ploughing with his heifer.`"

When my wife told me of it, which was not presently, it troubled me,
to have my testimony thus evaded by this undermining trick, which was,
in the man who did it, designed for our good no doubt,
and the note that he gave for the money being destroyed,
I had nothing to show under his hand for the money, and what to do in it I was at a loss.
I thought it best to convene the elders, and let them know how it stood,
and to be advised how I might clear my testimony, and my dear wife and self,
from having any hand in this deceitful trick; which I accordingly did,
and they were satisfied we were clear of the contrivance,
but did not know what to do to satisfy others about it;
one Friend was for suing him who had thus tricked me for the ten pounds.
But others thought such an act would do more hurt than good,
and thought it by no means advisable to act any further,
than to go to my kinsman and let him know, that what he had done in the case,
though by him intended for a kindness, yet it had the contrary effect on our minds,
so that although he intended to serve us, it proved a disservice,
and to request that he would never serve us so again.
In due time my wife and I took an opportunity, and discoursed the matter over with him;
and he to excuse it, said, he little thought we would take it so much amiss as we had,
having, as he thought, no reason for it,
and wondered our friends should be so stubborn as to contend against law;
and he could not bear to think we should be served as Mr. Bantom and Mr. Tilley were;
and indeed, if it were again to do, I should do the same,
said he.--Robert Bantom and William Tilley were two
very great sufferers by exchequer process,
both very honest sincere Friends.
Thus was this affair ended.
The first letter I wrote the parson, with the parson`'s answer, and my reply,
are annexed:

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Bownas to William Ray

[.signed-section-context-open]
Lymington, the 15th of the Fourth month, June, 1712.

[.salutation]
Neighbour Ray,

Since you are pleased to proceed against me by justice`'s warrant,
I desire you would be pleased to let me know what you demand; else,
how shall I be able to make my defence?
I think your people this year and last were very unreasonable in their taking,
having both years, modestly computed, taken above one eighth part of my hay:
and Brook`'s never, as I am informed, paid any in kind till you came into the parish;
but now for nine pence the three acres,
you have taken every year hay worth eight or nine shillings per annum at least.
As for arguments between us, for or against, I suppose them needless,
but I take it very hard to be so treated from a man of your pretensions.
I believe you would not, if in my case, like such treatment.
Not that I murmur or repine because my goods are taken away on this account,
being persuaded that it is my duty actively to refuse
a compliance with the laws that command tithes;
and if I must, as I have already done, suffer the spoiling of my goods,
I hope passively to submit and bear it.
This I conclude with desires of good for you and yours every way.

[.signed-section-signature]
Samuel Bownas.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ray to Samuel Bownas

[.signed-section-context-open]
At the Parsonage-house, July 24th, 1712

[.salutation]
Sir,

I have been above thirteen years in the parish,
and have not given the family any disturbance,
though the arrears which are due to me are considerable;
so that you have no reason to complain of hard usage from me,
but rather to thank me for my kindness, in bearing this injustice so long.

You do not think, when you go to law with one another,
or with some of those who differ from you, that you spoil their goods,
when you put them to charges, that you may force them to do you justice.
And why, pray you, should it be thought a spoiling of your goods,
when we do nothing more than you do yourselves, when you think you are wronged; that is,
endeavour to recover our own?
For I demand nothing of you but what I know to be mine before I receive it.

You might as well make an entry upon our glebe lands, or upon anything else we possess,
as to seize upon the tithes, to which you have no more title than to the other,
unless you have bought them, as I am sure you have not.

For every body who understands these things will tell you,
that when such lands as are tithe free, are sold or let,
they are for that reason valued at a higher price,
and the lord or seller makes the tenant or purchaser pay for the tithe,
as well as for the rest of the estate: and that on the other hand,
there is a proportionable abatement made to the purchasers and
tenants of such lands as are liable to the payment of tithes.
And there is very good reason for it,
because in that case the tithes being no part of the landlord`'s property,
he cannot make them over to another, or demand a price for that which he has not sold;
and those who rent or purchase his estate,
can claim no title by virtue of any conveyance or grant of his,
but only to what he had a right to dispose of himself; so that if you will needs,
in this matter, pretend conscience,
you ought not to occupy any land but what is tithe-free.

But if you think that this would be very grievous and inconvenient, you ought,
when you occupy tithe-land, to permit us quietly to enjoy our tithes,
which are a part of our freehold;
and to which we have the same title as we have to our glebe,
wherein you claim no propriety, as indeed you have no manner of title to the tithe.
If you have, be pleased to show it, and let us know from whom you had it.
And if you have none, as I know you have not,
do not go to pretend conscience for invading your neighbour`'s property.

For my part I do not see any reason why you should
not actively comply with the law for payment of tithes,
as well as with that for taxes,
as your friends have done over all the kingdom ever since the revolution;
and some of them have been collectors,
though the title of the act of parliament did plainly show,
that the tax was for carrying on a war against France with vigour: and yet your friends,
even those who have been of greatest reputation among you,
and the champions of your cause, have declared as much against the lawfulness of all war,
as they have done against the payment of tithes,
and sometimes have carried the matter so high,
as to refuse the payment of money demanded of them for that purpose;
as Robert Barclay in his Apology tells us,
"`they suffered because they would not pay for drums and colours,
and other military furniture.`"
And this they did in the time of peace, when the militia met only to make a raree-show,
and had at the place of rendezvous no other enemies to skirmish with but butterflies.
Nevertheless, since the war against France began,
your friends have given the same active obedience to the laws for payment of taxes,
as their fellow subjects have done; and I hope you, for the future,
will do for the payment of tithes, which, according to your avowed principles,
is as lawful as the payment of taxes for carrying on a war with vigour.

It is a vain thing to pretend conscience to excuse oppression or covetousness,
for it must be one or other of these which makes
any man take possession of what is not his own,
but his neighbour`'s.

If we lived by the alms-basket and could claim nothing but what we might expect
from the benevolence of those from whom we make any demand of this nature,
we could not blame you so much: but the case is otherwise;
for we desire none of your benevolence, and we know the tithe is no part of your estate,
and that you can claim no right to it, either by donation or purchase.
Therefore do not go to call that your own which is not;
and being you disclaim all violence against, or oppression of,
men upon the account of their conscience,
we may reasonably expect so much tenderness from you, that you would not oppress us,
because we differ from you, and that you would not, under a pretence of conscience,
seize upon our estates, and then make an outcry against us,
when we desire the assistance of the civil magistrate,
for recovering any part of our properties or freeholds,
as often as you unjustly invade them.
Surely we might look for more equity from you, being we are members of that church,
which in other respects permits you the free exercise of your religion,
and has confirmed the same by the late act of indulgence, agreed upon by the bishops,
lords, and commons of our communion.
An instance of such moderation as was never shown to our
church by any other sect who had us under their power,
whether Papists, or some violent and fierce Protestant dissenters,
who perhaps would handle us as roughly as our predecessors were by them,
if God should again permit us to fall under their merciless hands.

You say, you take it hard to be so treated by a man of my pretensions,
and if it was from some of the same cloth, you would think it was like themselves.
But why should it be thought inconsistent with my pretensions,
to demand what I know to be my own?
And why may I not say the same to you,
that I take it hard to be so treated by a man of your pretensions, who profess,
that violence against those who differ from you,
merely upon the account of their conscience, is unwarrantable; and yet,
contrary to this your profession, you seize upon that which is mine,
mine by as good a right as you have to your own estate;
for you cannot say that you have purchased the tithes,
or that any who had a title to dispose of them did make them over to you;
and yet for all that, you pretend conscience for the disturbance you give me,
for no other reason, but because I am of a different communion from you.
If this was done by some who maintain that violence
against men of another persuasion is meritorious,
and that heretics ought not to be allowed to live, I should think it was like themselves;
though from you I might expect other things.
But let that be as it will, I desire nothing from you but the profits of my own estate,
which you unjustly withhold from me; and I am resolved,
whatever you think or say about the matter, that I will have my right.
However, if you are willing to live peaceably, I shall be as moderate as you can expect,
and for that reason have referred this business to Mr. Smith,
whom I have authorised to do as he thinks fit; and am, sir,

[.signed-section-closing]
Your friend and well-wisher,

[.signed-section-signature]
William Ray.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Bownas to William Ray

[.signed-section-context-open]
Lymington, the 10th of the Sixth month, August, 1712.

[.salutation]
Neighbour Ray,

Since you have advanced some arguments for your taking tithes,
I have somewhat to offer in answer thereto, for my refusal.

[.numbered-group]
====

[.numbered]
1st. You are pleased to write,
"`I ought to thank you for bearing with this injustice so long;`"
but I take the refusal of paying tithes to be no injustice.
Therefore, etc.

[.numbered]
2nd. You say, "`when I go to law with another, or some that differ from me,
I do not think it spoiling of their goods;`" which
I do not take to be a parallel case with this;
for, first, if I go to law with any man, it shall be for some just debt owing to me,
for which he, whom I so go to law with, shall have received some valuable consideration;
but from you I have received none for the tithe of my increase;
therefore it is not a parallel case.

[.numbered]
3rd. He with whom I go to law shall have no just plea of conscience,
because if I can have no plain demonstration that he had of me
a valuable consideration for which I make my demands upon him,
I will not go to law at all; therefore it is not a parallel case.

[.numbered]
4th. If on such a foundation I go to law, and force my adverse party to justice by law,
I conclude with you, it is not spoiling of his goods.
But to go to law, and by it take away people`'s goods,
without such a valuable consideration as above, is spoiling of goods in my opinion,
with a witness.

====

You write me, "`I may as well seize of the glebe-lands, or upon anything else we possess,
as upon the tithes.`"
Under favour, I am of another mind; because I have no title to show for your glebe lands,
or anything else you enjoy: but for my land, the whole I take to be mine,
without any reserve or exception whatsoever, as the writings that give me my title to it,
do sufficiently set forth and declare; and I have given for it a valuable consideration,
which you never did for the tenth part thereof: therefore,
I am sure I have more right to it than you can pretend to, in justice, equity and reason;
because I have bought, without reserve, the whole,
and manured the same at my own cost and charge; but you have bought no part thereof,
nor been at any charge about improving it, that I know of.

You further write, "`that every body that understands these things, will tell me,
when such lands as are tithe-free are sold, for that reason they are valued higher.`"
What argument is that for the lawfulness of tithes, according to the Gospel?
I conceive none at all.

The next is, that "`if I occupy tithe-lands,
I ought quietly to permit you to enjoy the tithes:`" that is the matter in dispute,
which shall in its place be spoken to.

Now I am come to your argument about taxes,
wherein you endeavour to make us inconsistent with ourselves,
in actively complying with the law for taxes,
but refusing a compliance with the law for tithes,
endeavouring thereby to lay tithes and taxes upon one foundation.
In this also I differ from you; for I understand taxes to be paid as a civil debt,
tribute or custom, to Caesar:
but tithes are paid as a religious act to God and holy church,
as in its place shall be further shown.

Indeed our Saviour said, "`Render unto Caesar, the things that are Caesar`'s;
and unto God,
the things that are God`'s.`" Now if we must render to Caesar the things that are Caesar`'s,
and unto God the things that are God`'s, then it remains to be proved,
that tithes are Caesar`'s due, before they be demanded as his right.

But here is the grand objection of inconsistency;
that because we have suffered for refusing to pay towards the militia for drums,
and colours, etc., and yet actively comply with the law of taxes,
which is to carry on a war with vigor, etc.,
insisting on R. Barclay`'s words to strengthen the objection.
We are still of the same mind with R. Barclay,
that "`wars and fightings are inconsistent with Gospel principles;
and when it is brought so near to us,
that by law we are obliged to act both in person and estate,
we in this case choose rather passively to suffer, than actively to comply,
for conscience-sake.`"
And this is still our case, and a suffering we lie under, with respect to the militia,
in many places, being careful to walk by the rule of Christ`'s doctrine.
Yet we do not hereby think ourselves inconsistent
in actively complying with the law of taxes,
in rendering to Caesar the things that are Caesar`'s,
and he may do therewith what pleases him, we may not direct him; therefore,
to use your own familiar simile,
I take this argument of taxes to have no more weight in it, in relation to tithes,
it being no parallel case,
than the enemies that the militia met with in their rendezvous, at their raree-show.

You write,
that "`it is a vain thing to pretend conscience to excuse oppression or covetousness.`"
I am entirely of your mind;
so that where any man pretends to refuse the payment of tithes out of covetousness,
believing at the same time in his conscience they are justly due; it is a pity,
if that be his only excuse, that he should not pay smartly for it:
but beware of mistaking, by supposing the refusal to be from covetousness,
when it is really conscience.

You add, "`if you lived by the alms-basket,`" etc., which indeed I think you ought to do,
if your own hands cannot sufficiently administer to your own needs;
for a forced maintenance is not consistent with the Gospel ministry;
and that you know right well, having often confessed it in my house.
You add, "`tithes is no part of my estate, either by donation or purchase.`"
But I say as above, I have purchased the whole,
without any reserve or exception of tithes.
But in your own country, North Britain, I have been informed,
tithes are excepted in deeds and conveyances,
so that they have some colour to use such an argument,
but I can see no foundation for such an argument in this country.
You advises me not to call that my own, which is not; I say, it is my own,
because I have, without reserve, purchased the whole, as witness my writings:
besides all that, at my own charge I have manured and improved it.

Your next paragraph is already answered.

I acknowledge you a member of that church, or society,
who have granted us the indulgence we now enjoy in the exercise of our religion;
for which,
I with the rest of my brethren ought to be truly thankful to God and the government.
But I must tell you, some of your brethren, not of the meanest rank in your church, have,
like battering rams, endeavoured to break that chain of indulgence, we now enjoy,
but Providence has hitherto prevented them, and I hope ever will,
unless God should see fit to try his church,
to discover thereby the truly religious from the hypocrites.

You seems angry, and to resent it, that I should take it ill or hard,
to be so treated by a man of your pretensions; but the reason why I wrote so, is this;
because I have more than once heard, that my neighbour Ray has said in our house,
that it was a matter of conscience to him,
to force a maintenance from such as for the sake of conscience could not pay him,
using that text, "`Whose ox have I taken, or whom have I defrauded?
Which I have sometimes spoken of to others,
and it gained great credit and good thoughts concerning my neighbour Ray,
and for that reason, and no other, I took such treatment hard.
But however, if your conscience be altered,
it will give reason for my thoughts concerning you also to change.

I shall give you my reasons, why I cannot actively comply with the law for paying tithes,
and answer your last paragraph in the conclusion of this.

I was in my youth very thoughtful, touching the nature and design of religion,
and conscious to myself, that an implicit faith, with a blind obedience,
might not be sufficient to bring me to the end intended by it.
I observed many under great sufferings for refusing to pay tithes,
and that their plea for it was conscience; but many more I found did pay,
and they thought they did right, at least made no scruple of conscience in doing it.
This contradiction in practice made me willing to look into it myself,
that what I did herein might not be for imitation`'s sake on either side,
but that I might act on a principle of faith, knowing, "`what is not of faith is sin.`"
These reasons put me on examining and trying for myself.

I now assure you, that it is not out of stubbornness, ill-humour, or covetousness,
but purely on a principle of conscience, for these reasons following,
that I can neither pay nor receive tithes.

[.numbered-group]
====

[.numbered]
1st. The dedication of them is grossly superstitious,
and I think protested against by most,
unless such as love to suck the sweets of other men`'s labour,
being dedicated and given by king Ethelwolf, about 855, to God and St. Mary,
for the redemption of his own soul, with the souls of his ancestors;
in the consideration whereof,
the clergy were to sing a certain number of masses for the king and his nobles.

[.numbered]
2nd. It is already granted by me,
that we must render to Caesar the things that are Caesar`'s,
and unto God the things that are God`'s. And I promise you,
I shall be both ready and willing to pay the tenth of my increase unto God,
when I am satisfied he requires it of me; or unto them he shall appoint,
when I am satisfied he has appointed them, as he did the tribe of Levi;
but for me to pay tithe to a man, claiming it as a minister of God,
when I know that no such thing is required of me,
tithe being no Gospel maintenance that I can understand, it might justly be said unto me,
"`Who has required this of your hands?`"
Yet, if tithe be compelled from me by a human law, I cannot help that,
nor resist the force of that demand by argument from Scripture; therefore,
being persuaded that God requires of me no such thing as the payment of tithes,
but that I am called to protest against all superstition and idolatry,
and the law of tithes plainly appearing to me to be such, I cannot,
with a safe conscience, actively comply therewith,
but choose rather to please God than man,
although it may be to my disadvantage in this world,
yet by so doing I hope for future gain.

[.numbered]
3rd. And again, tithes are required to be paid as a religious act:
"`to God and holy church;`" and I am persuaded that God requires no such thing,
therefore I cannot pay them with a safe conscience,
being a Protestant against that which I call popery, not in word and tongue only,
but in deed and truth also.

[.numbered]
Lastly. Tithes are not required by the Gospel, that I can understand.
If you can make it out, please to do it, for it is clear to me,
that Christ came to finish and put an end to that law which required tithes,
as well as to the priesthood supported by them;
therefore to continue in the practice of tithing, is in effect,
"`denying that Christ is come in the flesh to put an end to them,`"
according to Scripture and the practice of former times;
for which reason I think an active compliance with the law for tithes is sin,
and in my opinion, he that pays and he that receives,
are equally culpable in God`'s sight; for which cause we can neither receive nor pay,
as this deed of settlement will prove,
and more instances of the like kind might be produced from sundry parts of the nation;
a plain demonstration, that as we cannot pay tithes, neither can we receive them,
when they are as legal a property to us as they are to you.

====

I could say more, but what is said may perhaps be tedious, and thought impertinent,
therefore for the present this shall suffice.

To conclude you are pleased to give me your resolution, namely:
to have what you call your right; and if I could think it was so too,
we should soon reconcile this matter.

You add,
"`If I am willing to live peaceably,`" (I desire no other than
a peaceable living,) "`you will be as moderate as I can expect.`"
But it seems an odd way of showing your moderation, to employ an attorney; for you add,
"`for that purpose you have referred the matter to Mr. Smith,
to do as he thinks fit,`" and that may not perhaps be the best way to show your moderation;
however, be that as it will, I must tell you, that what I cannot directly pay,
for the reasons aforesaid, I cannot order or allow another indirectly to pay for me;
for although I might bribe my conscience, as the chief priests did the soldiers,
and lull it asleep in such hypocrisy, yet an awakening time will come,
when every thought, with every secret thing, will be brought to light,
and appear as it is.

This with due respects from him who shall always
be ready and willing to serve you and yours,
in anything I can with a safe conscience, and in any office of love may command

[.signed-section-closing]
Your friend and neighbour,

[.signed-section-signature]
Samuel Bownas.

--

These letters were exchanged between us some weeks before I was made a prisoner,
and whether they might soften him or not, I dare not say;
but he was very uneasy while I was in prison, and, as I was informed,
told his attorney and his wife, if he lost his debt, he could not keep me there.

This storm being blown over I enjoyed quietness,
save that I was persecuted for church-rates, small tithes, etc.,
for the parson would not let his dues, as he called them, run on again in arrears,
but would take it in kind every year, so he never had me before a justice again,
but if he could not have it in one thing, would take another.
I now had nothing but my business that lay upon me,
save the attendance of meetings for worship and discipline, with marriages and burials,
which took up pretty much of my time,
there being but few to attend such services in the country:
so that I had sometimes long journeys on those occasions.
