== Chapter V.

[.chapter-subtitle--blurb]
An account of my visiting Devonshire and Cornwall.

On the 21st of the eighth month, 1715, I set out from home, and visited Taunton,
Wellington, Milverton, Spiceland, Collumpton, and Topsham,
where the Quarterly Meeting for Devonshire was held at that time:
I was at three meetings there to good satisfaction, and then at Sticklepath,
and Launceston, where I had a very large and good meeting.
From there to Port Isaac and Falmouth, visiting Friends to Penryn.
The Quarterly Meeting was held at Falmouth, and I had very agreeable service.
Then to Penryn, Market-Jew and Penzance, and back to Falmouth.
From there to Austel, Tregony, Looe and Liscard, Germains, Plymouth,
Kingsbridge and Totness; and had meetings at all these places,
some of which were very large and well; at Exeter likewise; and from that to Chard,
and so home.
In this small journey I had about thirty-eight meetings,
and travelled about three hundred and fifty miles.

In a year or two after this, my wife was taken with a lingering disorder,
for recovering her out of which, I applied myself to several doctors, but all in vain,
for she continued wasting more than two years and eight months,
growing weaker quickly a few weeks before she died, which was in the eighth month, 1719.
She died in a sweet frame, often saying nothing troubled her,
but that she was so easily deceived about the parson`'s tithe,
which being done in ignorance, not designedly, she was the more easy about it.

I was now in a strait what course to take, being in considerable business,
which I kept on that winter, and in the spring put it off to my servant,
and let what little estate I had to him, putting off all business,
and went the next summer into the north, to visit my friends.
I went to the Yearly Meetings at Bristol and London, as they came in course,
and travelled from London through Hertfordshire,
Leicestershire and Nottinghamshire to Leeds,
visiting the meetings of Friends as I passed along.
I was at several very large, open meetings in my way to the Yearly Meeting at York,
which was large, and attended by a great number of ministers of both sexes.
I had no time till the last meeting, and that was far spent before I began,
but then I took my time pretty thoroughly,
being opened very largely in the distinguishing between true and false religion,
setting them as it were side by side,
that they might judge for themselves of both the worship and the ministry,
with their different effects upon the minds of men and women in regulating our passions,
and reforming our minds.
I opened pretty fully the danger that ministers were in,
to preach from the letter instead of the Spirit;
and that our former openings and experiences alone were not to be depended upon,
but our safest and best support in that work, was the immediate ability of the Spirit,
opening our understandings in matter suitable to every state,
that our words might be fitly spoken, then they would carry their own evidence,
and be serviceable to the hearers.
I was very large and particular on these heads; there being several clergymen,
and teachers of other societies,
but I did not hear of any objection made to the doctrine.
Some of our friends thought,
what I had to say about the ministry would have been
better delivered in the meeting of ministers;
but that could not have answered so well, as to the teachers of other societies,
who might need instruction in these things, perhaps more than our own people did.
This was a high day, and I found in myself afterwards great satisfaction and peace.

I now visited Friends towards Kendal, and through part of Cumberland and Northumberland,
into Scotland, having for my companion a young man from Sedberg,
whose name was John Blamore.
I found Friends in that nation very much decreased in number, above one half,
and some meetings quite dropped, unless when a Friend came to visit them.

I spent about six weeks in that nation, but nothing extraordinary happened:
I then returned into Cumberland, visiting most of the meetings in that county.
Our friends at Cockermouth had appointed a meeting to be the day after the fair,
at the time called Michaelmas,
and it being in the hottest time of the opposition the Parsons gave to Friends;
Job Parsons and his brother being at that fair on their business,
gave out that they would be at the meeting the next day,
which gave an alarm to both town and country people, so that it was a very large meeting.
Job and I had been very friendly before he fell into these ranting fits,
and some Friends thought he would show me more respect than he had done to some others,
having been heard at times to speak in my favour.
But James Dickenson being present, whom they had abused very much, said,
"`I should be pleased to see a friendly meeting between Job and my friend,
but I little expect it.`"
The meeting came on, and was very large, and very open and quiet,
neither Job nor his brother came, being otherwise employed,
having business with some country men in the fair,
they went to an alehouse to settle their affairs, and differed so much about them,
that from words they proceeded to blows, and this fray held the time of the meeting,
so that we were free from their disturbance, and a sweet, comfortable,
quiet meeting we had, to great satisfaction.

I visited the rest of the meetings in that part of the county,
and so into Westmoreland again, visiting all the meetings in that county,
and through the Dales to Richmond, and York Quarterly Meeting in the winter,
which was very large, considering the season of the year.
I had many satisfactory times among Friends,
both in meetings of business and among the ministers,
in very freely showing my dear brethren and sisters, in the openings of Divine life,
the experience and knowledge I had attained to in the work of the Gospel,
finding my spirit much enlarged in setting it forth.
The last meeting I was at in York, was on the first-day in the evening by candle light,
and the crowd in the house was so great, that the candles would hardly burn,
and some went quite out.
The lack of room was very troublesome,
and made the meeting not so edifying as if the company had been less.

From there I went to Bridlington, Oustwick and Northcave,
visiting meetings till I came to Bradford and Leeds:
I had some very large open meetings in those parts, as at Brighouse, Highfiats,
Sheffield, etc.

I travelled to Nottingham, and had some meetings in that county, and so on to Leicester,
and had several small meetings thereabout,
and some who were convinced in my first travelling there, were glad to see me,
and I them, as we claimed kindred in the truth.

I now made a short visit in my way to London, which I visited thoroughly,
stayed in the city four weeks, and had very good satisfaction.
Returning through part of Berkshire, I had two very large meetings at Reading,
and so into Dorsetshire, having no meetings after Reading till I came there,
and so to the Quarterly Meeting in Somersetshire, which was held at Glastonbury,
and very large indeed.
Then visited meetings to and fro, and attended several funerals,
both before and after the Yearly Meeting at Bristol, which was very large.
From that meeting I went towards London, visiting Friends in my way there,
and after Yearly Meeting was over I returned to Ringwood
to the Quarterly Meeting for Hampshire,
and to Pool Yearly Meeting.
This summer, before the Yearly Meeting at London,
I had made my addresses to the widow Nichols, leaving the matter to her consideration,
and now I renewed the suit.

In the eighth month, in company with other Friends,
I went to solicit the parliament for an amendment of the affirmation,
in which undertaking we were favoured with success,
which was of very great advantage to the Society,
and the good effects of it soon appeared.

I returned home in the spring, and then proceeded in my addresses,
and we were married in the second month, 1722,
and went to London Yearly Meeting together, which was held to very great comfort.
I returned directly home with my wife, and being in a coach,
had no opportunity of visiting meetings either going or coming.
On my return home, I applied myself to assist my wife in her business, attending General,
Monthly and other meetings on public occasions, for three years.
I had a concern to visit America once more,
which my poor wife could not at first with ease consent to,
although I had laid it before her when I first made my addresses to her,
yet when it came to be put in practice, was not easily got over.
But afterwards she gave me freely up to go with my son-in-law;
and I got ready and went off,
before it was thought of by almost any body but the Friends of our own neighbourhood.
However, that it might not look like stealing away,
I wrote to some of my chosen friends at London, in the north, Bristol,
and elsewhere through this nation, and to some few in Ireland,
being willing to advise them where to meet me with letters in that country.
My wife brought me on my way to Pool, at which place, before I went off,
I received answers to some of my letters.
