== Chapter VI.

[.chapter-subtitle--blurb]
An account of my travels in America the second time, being in 1726,
and in the fiftieth year of my age.

I left my home the 22nd day of the tenth month, 1726, being accompanied by my dear wife,
a kinsman, and a son-in-law, to Pool, to take shipping there with my son-in-law,
Josiah Nicholson, but the ship was not quite ready; and when it was ready,
the wind being against us, were obliged to stay there about five weeks,
during which I had several satisfactory opportunities among Friends and others.

All being ready, and the wind fair, we set sail out of Stutland bay,
the 24th of the eleventh month, with a fair wind and pleasant weather,
which carried us a considerable distance off the land; but it held only three days,
and we had very contrary hard winds after that, which made me very sick,
and other ways out of order, so that I almost despaired of my life for a few days,
but had great comfort and peace of mind, being satisfied I was in my place,
and the way of my duty.
I recovered as the weather grew better, and the sea quieter,
but we had a very long and tedious passage, being eleven weeks and two days upon the sea;
and on the 14th of the second month, 1727, we landed at Hampton, in Virginia.
That evening I got a passage in a Pool ship up to Sleepy-hole,
and about the eleventh hour arrived at Robert Jordan`'s, being very weary,
yet glad that I was got to so good a place, where I had a hearty welcome,
and felt great peace and comfort.
This was on the seventh-day of the week,
and next morning I went to a funeral about twenty miles,
which was a long journey on my first arrival;
and considering the inhabitants are but thin,
there was a great concourse of people on the occasion, and I had a pretty open time,
although not quite recovered from my weakness;
as the motion of the sea was very much in my head,
so that I had a great dizziness and swimming, which caused me to reel like a drunkard;
as is common in the like case.

That night I went with my friend Robert Jordan to an inn,
near the place where his son Robert was a prisoner, who was a goodly youth,
and had a very serviceable ministry.
His father and I stayed with him all the next day,
and in the evening went to lodge at his house, his poor wife being alone;
and although her husband was confined, she was cheerful.
We had a meeting in the prison to good satisfaction,
many people came to it and were orderly.

I then had a meeting at the western branch of Nansemond river,
and was at the funeral of a young man who was very much lamented.

I went that night towards Chuckatuck, where I had a fine, comfortable opportunity,
and on the road I had some discourse with an ancient Friend,
concerning the health of the country,
we supposing people did not live so long in Virginia as in Europe.
This Friend told me, the first man-child born in the province, of English parents,
lived eighty years, and that many since had lived considerably longer;
so that it is not the climate,
but the intemperance of the people that shortens their days,
for experience made it appear,
that temperate people lived much the same time as they do in Europe.
This first-born son of the province was a remarkable man,
it was said that he was disaffected to the then government,
and had uttered some treasonable expressions against it, and for that cause was tried,
and found guilty, being condemned to die for that crime: but when it was made appear,
that he was the first male-child born in the province, of the English nation,
it was resolved that he should be pardoned.
Thus he was preserved from that untimely end, to run out nature`'s race,
which was eighty years.

I went after this meeting to visit Robert Jordan, Jr., the prisoner,
and the next day was at a funeral, the people being very humble,
by reason of a great mortality,
so that preaching the Gospel had a very great reach upon them,
and several were convinced.
Next day I went to Levy-neck, had a meeting,
and went to Surrey meetinghouse to a funeral, having been at four in about two weeks.
After this I took a turn round again to Levy-neck, otherwise Pagan Creek,
and had a meeting.
From there to a meeting at Raskers-neck,
and so round till the Quarterly Meeting was at hand; and then came to Robert Jordan`'s,
to lodge.
Next day at the meeting I met Joshua Fielding, a Friend of London,
who had visited the islands and South Carolina,
and had travelled by land to North Carolina, about five hundred miles,
in about three weeks, mostly alone, which was a difficult and hazardous attempt.
Some thought it too great an undertaking, and seemed to blame him for it,
but he got safely through, though he had no provision but what he carried with him,
and met with about four or five houses or plantations
in all that five hundred miles travel,
which obliged him to lodge in the woods frequently; but having a small pocket compass,
that was his guide, when the sun and stars were hid from him.
I have since heard, that some others have travelled over this same ground,
with less hardship, plantations and settlements being placed at proper distances,
and a road marked out by the government;
and now they may accomplish this journey without so frequently lying in the woods,
as when this Friend came from there.
I was at the Quarterly Meeting, which held the seventh and firstday,
and the weather being very hot, made it a little tedious to bear,
there being a great crowd of people, but the meetings ended well,
and were of good service.

From there I went to Levy-neck,
and visited all the meetings up to Curl`'s on the banks of James`' river,
and had an open good meeting there, though small, then to Gerard Ellison`'s,
and had a large and open meeting; from there to Rappahannock Ferry,
travelling sixty miles that day: I lodged at a poor widow`'s house,
not a Friend by profession, but exceedingly kind.
I had something to say in prayer before the meal, with which she was greatly affected,
and broken into tears, with some others of the family.
When we left her in the morning, she would not take anything for our entertainment,
but desired that she might be favoured with such guests often.
I gave her children something, and we left her in much love and tenderness.
I travelled towards Maryland, about seventy miles, and had but one meeting on the way,
where William Duff lived, who was at that time a very tender and serviceable man.
The Yearly Meeting in Maryland now came on, which held four days, namely:
three for worship, and one for business.
Many people resort to it, and transact a deal of trade one with another,
so that it is a kind of market, or change,
where the captains of ships and the planters meet and settle their affairs;
and this draws abundance of people of the best rank to it;
being in that called the Whitsunweek.

After this meeting I visited the province on that side of the bay,
and was at some places where meetings had not been,
missing no place till I came up to the head of the bay.
Then I ferried over the Susquehanna to Nottingham in Pennsylvania.
Some Friends came from there into Maryland to meet me,
and conduct me over that large ferry, which was attended with much danger,
it being a wide and very rough sea,
and I seemed in more danger than I was upon the ocean in the greatest storm we met with,
but through mercy we all got safe over,
although with hard labour and great care and difficulty.

The first meeting I had in that province was at Nottingham,
and I had two in that township.
Then visited the meetings as they came in course, at New-Garden, London Grove, Kennet,
Concord, Chester, Springfield, and so to Philadelphia.
A great number of Friends came out of Philadelphia to meet me,
which gave me great uneasiness,
fearing I should never be enabled to answer the high expectations raised by such conduct;
and it were better to forbear such doings, for it is rather a hurt than a help.
Those meetings were very large, several of them amounting to fifteen hundred,
and some more, and mostly of a young generation.
Very few of the elders who twenty years before were serviceable, zealous men,
were now living;
and many of the rising youth came up in the form more than in the power and life,
that their predecessors were in; nevertheless,
there was a fine living people among them, and they were in a thriving good way,
several young ministers being very hopeful, both men and women.

I was at three meetings in Philadelphia, exceedingly large,
more like Yearly Meetings than common first-day meetings;
after which I stayed but two nights,
being in haste to reach a Yearly or Quarterly Meeting,
near three hundred miles further north, at Newport on Rhode Island.
I travelled from there to Burlington, Crosswicks, Stonybrook and Woodbridge,
and had meetings at all those places.
I attended a Yearly Meeting, as they called it, at Newtown, Long Island,
on the first-day of the week; it was very large of both Friends and other people.
There I found several of my former friends, John Rodman, Hugh Cowperthwaite,
Samuel Bowne, and others,
who had been of great comfort and support to me in my imprisonment on the island,
and we were truly glad to see and enjoy each other in the truth of the Gospel.

From there I took my journey through Connecticut, nearly two hundred miles,
to Rhode Island, and visited the meetings at Seconnet, Acoakset, Dartmouth,
and back to the island, and so to the Quarterly Meeting at Newport,
which was very large and continued three days.
I was largely drawn forth to the elders and ministers, there being many of them,
and had very good satisfaction in all their meetings.
I went back to a Monthly Meeting at Dartmouth, which was very large;
but a narrowness of spirit did hurt among them, and produced some uneasiness,
which I endeavoured to remove.
It was chiefly occasioned by a young man being too much in the fashion, although plain,
compared with some others;
yet some thought this reason sufficient to refuse his proposal of marriage among them,
although well recommended from the Monthly Meeting where he was a member.
I showed them, that as he was so well recommended by certificate,
they could not reject his proposal according to our discipline.
The meeting, after we had some further conference about it, let the young people proceed,
and matters grew easy,
and that cloud of difference dispersed which was likely to hurt both Monthly Meetings.

I went about five miles to Joseph Russel`'s,
in order to take shipping for the island of Nantucket.
We met with some difficulty in the passage,
and were obliged to put into the island called Martha`'s Vineyard,
but had no meeting there.
We landed at Nantucket on the sixth-day of the week, and notice being given,
the next day we had a very large meeting in the forenoon,
and on the first-day it was much greater, especially in the afternoon,
the inhabitants generally inclining to Friends,
and there was great love and unity among them.
I desired a select meeting of the elders,
to whom I had something in particular relating to discipline and the ministry,
which was of good service and well accepted.
I stayed two meetings more, and visited some families, and then took shipping back again,
was two nights on board, and being in an open boat, and the weather very hot,
it was tedious.

Several persons of the island came with us, and we landed at John Russel`'s;
and from there, having Nathaniel Starbuck with me,
went to a small meeting called Seepecan, and so to Suckenaset.
Here a man gave some uneasiness, by raising objections about the Divine light,
as not being universal, rendering the doctrine, as he would expound it, against reason,
urging that the natural consequence of it was to hold forth
as many Christs as people who were enlightened by him.
To which I answered, by alluding to the natural sun,
which enlightens the earth and every dwelling, so that we frequently say,
when the rays of light from the sun come into the room, the sun shines into it;
yet the sun is not therefore divided,
but it is the same sun that enlightens the house here, that does another elsewhere:
Even so is the light of Christ:
he is the true light that enlightens every man coming into the world.
Thus expounding and illustrating the doctrine of the Divine light, the people,
who were but a few, seemed much affected therewith.
I had also in my doctrine that day shown the kingdom of God or of heaven to be within,
and that it was equally universal with the light of Christ.
At this he cavilled likewise, but made nothing of it,
for I set forth what the kingdom in this place meant, and how it ought to be understood;
plainly showing, that by the kingdom of heaven was meant the Divine Seed in the heart,
otherwise called the grace of God, which,
as every one makes it the rule of their actions, in both moral and religious conduct,
teaches us our duty to God and one another,
by which we are brought under the government of Christ,
and thereby made partakers of that peace which may
be justly termed the kingdom of heaven within.
The objections made by this forward man, though weak and impertinent,
gave opportunity to explain the doctrine of the Gospel more clearly,
and although such objectors seldom end in any good to themselves,
yet good often comes out of their objections.

From there I travelled to Sandwich, Yarmouth, Scituate,
and then to a meeting where Michael Wanton lived, and so for Boston,
visiting the meetings to Lynn, Marblehead and Salem.
I came to Newbury, the town which I mentioned in my first journey,
but there were very few Friends here now, not above nine or ten in all.
The people had notice, but the room was very small, and the priest came,
and did all he could to hinder the people from coming in,
and made a very great noise concerning the danger of our principles and doctrines.
I endeavoured to press him to show wherein; but he evaded that as much as he could,
and charged in general; but being closely pressed,
at last he pitched upon our denying the Scriptures, baptism and the supper,
and the resurrection of the body.
I bid him hold, and first prove that we denied the Scriptures, and so the rest in order,
as they came in course.
I asserted that we owned the Scripture; and he said we did not:
and I demanded proof of him, otherwise he must be concluded a false accuser.
He went about it, but could make nothing of it.
When he had said what he could, I told him,
his accusation relating to the Scriptures must be false, for it was publicly known,
that both in our preaching, and also in our writings,
frequent recourse was had to the text, to prove our doctrine,
and this must be a plain demonstration and proof, that we owned the Scriptures.
The people allowed this to be right: and he coming off so lame at first,
would proceed no further in that public manner, but would have me go to his house,
and talk these matters over in his closet.
I told him his meetinghouse was more proper for such a conference than his closet,
and there I would meet him when he pleased.
I had heard he treated the doctrines held by us, very unhandsomely in his pulpit,
where he knew none dare to oppose him, and if he would clear these things up,
I should be pleased with an opportunity to hear him
do it in as public a way as he had defamed us,
either to make proof of his charges, or retract them;
but he would not permit any such things.
He had charged Friends with denying the Scriptures, Christ, the resurrection of the body,
and that we pretended to revelation now, although, as he said,
it was ceased some generations since.
He being a hot, weak man, just set up in his trade,
endeavoured to ingratiate himself in this way into the minds of the people,
but he lost ground by it, so that he could make nothing but noise and tumult;
and I was told that some of his own people blamed
him much for the interruption he gave me,
and for endeavouring to hinder the people from coming to hear for themselves.

From there I went to Amesbury, etc., and to Hampton Monthly Meeting,
which held but one day.
I was concerned to stir up Friends to keep a faithful record of all their sufferings,
to be made use of as occasion might require,
the priests`' hearers making spoil of Friends`' goods to support their false ministry,
with which some people were so uneasy and oppressed,
that complaints in almost every township appeared against them.

From there I came to Dover Monthly Meeting: they were very raw,
and managed their affairs but indifferently,
chiefly occasioned by the lack of some better hands
to write and keep their books in order.
I was likewise concerned here to put them upon recording their sufferings,
and in a way to do it;
for they were sufferers not only on account of the hireling preachers,
to maintain them in their pride and idleness, but also for not bearing arms,
which was likewise pretty heavy upon them in some towns;
in others their neighbours were moderate, and made not much ado about them.
Some complied so far as to pay their quota about bearing arms,
who would not pay a doit to the parson,
they seeing very clearly that they were wrong and preached themselves and for themselves.
We had an agreeable time in conference,
and there was great sincerity and innocency among them.
I was at their first-day meeting, which was very large, and to great satisfaction.

After meeting,
finding that some misunderstanding was among them about the building of a meetinghouse,
we persuaded them to peace and love, in which we were successful.
We appointed a meeting to be held there, which was attended by all, or the greatest part,
of Friends of that Monthly Meeting, and a comfortable opportunity we had,
and they seemed all very easy and reconciled one to another.

From there I went to Strawberry-bank, other wise Portsmouth,
but it proved an unsuitable time, because all the country was come together,
the military part especially, with all their arms and accoutrements of war,
to proclaim king George the II., news being come there three weeks before,
that his father died on his way to Hanover,
and also on account of the peace that was concluded with the Indians.
Notwithstanding the vast crowd and hurry, we had a very quiet, though but small meeting;
and notice being whispered that there was to be a marriage at Dover, on a day appointed,
many in curiosity came to it,
and the people seemed much pleased with our way of marrying,
few of them having been at any before.
All ended quietly, without any dispute.

We had another meeting at the new meetinghouse,
after which I found a concern to desire an opportunity with the ministers and elders,
which was very readily granted;
and I was engaged to request and advise both the ministers and elders,
to endeavour to keep in the unity of the spirit among themselves,
that they might be good examples to the flock, over which they were to watch,
and to be ready and willing to administer good counsel,
which the apostle calls "`feeding of the flock;`"
and recommends to the elders as their business:
also that ministers look well to their gifts,
carefully avoiding either to abridge or enlarge in their
ministry beyond the true opening of life in themselves,
labouring with diligence and humility to evince the
truth of their words by their own conduct,
that no blemish or spot might appear among them,
nor any just ground to reproach them with teaching
others what they did not practice themselves,
being careful that their words and actions might be agreeable;
which would give authority to their ministry, and attract respect from their hearers.

From there I went to visit the widow Hanson,
who had been taken into captivity by the Indians,
an account of which I took from her own mouth, being in substance as follows:

"`Eleven naked Indians came with violence upon the family,
and killed two of the children just as they entered the house,
two other little boys being at play behind the house, when they heard the noise;
came running in great surprise,
the younger of whom could not be prevailed with to moderate his grief,
whereupon one of the Indians with a tomahawk struck
him on the head and killed the poor child,
to rid themselves of the noise, and to prevent their being discovered,
and to strike the greater terror upon those in the house.
Then they rifled the house of what they thought proper to carry away.
They took the poor woman, who had lain in but two weeks,
along with them by force and violence, with her little infant, and two daughters,
one son, and a servant maid.
It being in the afternoon,
the Indians were in a great hurry to force them away as far as they could that night,
for fear of being pursued and the prisoners retaken.
Thus they travelled for twenty days, passing through many lakes and rivers;
notwithstanding which they took no cold, but their health was preserved.`"
The incredible and severe trials which the poor captives went through,
during their captivity, I cannot here describe to the full,
in all which they were remarkably favoured by Providence, enduring hard labour,
though they were driven to very great straits for lack of provisions,
being necessitated to eat old bear and beaver skin match-coats,
first singeing the hair off.
After my return to Europe,
I saw at Dublin a relation of this extraordinary affair in a printed narrative,
which was brought over by a Friend from America.

Being easy to leave these parts for the present, I returned towards Hampton,
but in the way had a comfortable meeting at a town called Stratham, and to Newbury,
the place where the priest had given us so much disturbance;
but although he had notice of the meeting, he came not, and but a very few of his people;
it was a small meeting, yet peaceable.
I returned to Lynn, where was a Yearly Meeting, which was very large,
and I had good service in it.
Then to Salem, it being their Yearly Meeting for worship,
and Quarterly Meeting for discipline, which was exceedingly large;
they had a meeting of ministers and elders,
in which I was much enlarged in advice to both.
Then came on the Quarterly Meeting, in which, for lack of better writers and method,
they were somewhat deficient in their business, whereby it became tedious to themselves.
I endeavoured to put them in a better method, which they took very kindly.
After this was ended, a parting-meeting of worship came on, which was very large,
and was attended by abundance of Presbyterians and other people.
I was very much drawn forth into various branches of doctrine,
and the meeting ended well; no cavil or dispute arising, to which they are liable.
I was informed, that what I had delivered was taken down in writing, but I never saw it,
though a Friend had sight of it,
and the writer said he did it with a view to have
it printed by subscription and get something by it.

Not finding myself clear, I returned back with Friends to Haverhill,
and next day had a comfortable little meeting; from there to Hampton and Dover,
where was a Yearly Meeting:
they having in almost every place once a year a General Meeting,
which they call a Yearly Meeting,
and by this popular title abundance more people come together,
in expectation of something extraordinary to be met with; it held two days,
and was to very good content.
Next day I had a meeting at Kitteryside,
in an old meetinghouse that the Presbyterians had erected,
but not being in a convenient place for them, had left it.
Many people, both Friends and others came, and before it was quite gathered,
the priest with a large company came in, and immediately began to pray,
continuing a long time: but as soon as he had done,
I spoke to the people with some authority, which seemed to daunt the priest,
who it was thought intended to have taken up all the time himself, and to have put us by;
if he had succeeded, they would have gloried and triumphed much,
but they were disappointed.
In the course of my ministry,
I insisted on the danger of neglecting the work of our salvation, speaking cautiously,
that such an omission might be irreparable.
The priest replying, said, "`that should be expressed will be irreparable.
I desired him not to disturb us, for we did not him; and repeating my words over again,
with this addition, I dare not speak conclusively of the mercy of God,
who is able by Christ to save us at the hour of death.
After this he was silent, only writing when he thought he had any room to cavil,
but he was soon weary, for I was very strong both in power and doctrine,
and great tenderness was among the people, which was strange to him,
and Scripture came very aptly to confirm my doctrine.
The priest growing weary would stay no longer, but walked off,
inviting the people to go with him, but very few went.
We had a very good, serviceable opportunity, and the meeting ended very quietly and well.

Next day I went to Portsmouth, having been there before at an improper time,
but now we had an excellent meeting.
I was at the new meetinghouse, about which they had had some uneasiness;
we had a meeting to very good satisfaction, and Friends appeared well reconciled.
I went once more to visit the widow Hanson at Knox-marsh, and from there to Stratham,
having had a meeting there two or three weeks before,
and the people were then very much affected.
But the priest hearing of it, was very uneasy, and went among his hearers,
begging and praying them not to converse with the Quakers, if they could avoid it,
so that but few came.
Among them was a man in drink, who cavilled and would pretend to a disputation,
but he was so much in liquor that he rambled in his discourse, and knew not what he said;
he went away in a rage, cursing as he went along.
I came to Hampton and Amesbury and had meetings at both places; from there to Newbury,
and had a meeting; to which the priest was again invited, but he did not come near us.

Next day I was at their Monthly Meeting, which was but dull,
and then went up in the woods, to a new place, where there were many people,
and we had a good meeting.
Next day I was at a marriage, which was held in a Presbyterian meeting place,
a very commodious, handsome house, and would contain nearly two thousand people,
as some said.
It was as full as it could well contain, and the meeting was very easy and quiet:
several teachers from the neighbouring towns were there,
and I was doubtful of some jangling and dispute, but all went off very well.
I was largely opened to set forth the service of our Monthly Meetings,
with respect to taking care of the poor, deciding differences,
and taking cognizance of marriages; at which the people seemed pleased,
wondering that they had no such order among them; this was a high day, and ended well.

Next day I went to Lynn, had meetings at fresh places about Lynn, Marblehead, Salem,
and in several little villages towards Boston,
and taking my leave of Friends in that part of the country, I came to Boston,
and had two meetings there.
Then I went to Mendam, Providence and Swansey, or Wickapinsett, and had meetings;
and then to Scituate Yearly Meeting, which held two days, but nothing happened uncommon,
save that the parting meeting at Pembroke was very large, open, and to good satisfaction.
I had a small meeting at Hanover and Freetown, and so back to Wickapinsett again,
and then to Rhode Island Quarterly Meeting.
On the first day I had something to say to the ministers
and elders about the discipline of the church,
warning them to look diligently to the flock; and letting them know,
that the apostacy was partly occasioned through the
ministers and elders neglecting their duty, etc.
Next day was the meeting of ministers and elders, and I was very much drawn forth to both.
Then I had a meeting at Providence middle meetinghouse, which was small, but pretty well.

Then I went to Leicester, and had a sweet good time with a few seeking people,
and in the evening I had a long conference with a young woman about the sabbath,
the sacraments, so called, and some other points; in all which she seemed very tender,
and in a good frame.
I told her, I would not treat her as a disputant, in an adverse temper,
but as a sister and friend in the same faith in degree;
but she complained much of the bondage of her education, and lamented her case.

From there I went to Oxford, where was no meeting settled, nor any Friend in that place;
the priests did all that in them lay to hinder the people from coming to hear Friends,
when any came among them, if they knew it; however, we had a good opportunity.
From there to a meeting in a great house, not far from Seth Aldrich`'s, which was a fine,
full, and comfortable meeting.
Then to the upper meetinghouse, and so to Moshantatuck, and to Warwick,
and had meetings in those places.
I was desired to stay to attend a dispute.
One Hugh Adams, a priest, had challenged Friends,
he having undertaken to prove infant-sprinkling from Scripture,
to be an ordinance of Christ.
But in the proof he came off very lamely, Samuel Aldrich,
an excellent and ingenious disputant,
was by appointment to manage the argument on Friends`' side, and none else:
but such arguments as the priest brought for their
sprinkling were entirely new to the audience;
one was, the spray of the Red Sea, when the children of Israel went through it,
by the strength of the wind, sprinkled the children--infants, as well as old people;
and as the apostle said, "`They were all baptized in the cloud, and in the sea.`"
This was full proof of the point for infant-sprinkling, he said.
But Samuel made an excellent short discourse on the text, very much to the purpose,
and he had so much the ascendant in the argument on every branch,
that the priest lost ground, and several of his brethren being there,
were much ashamed of him.

I returned back to Rhode Island, and to Acoakset Yearly Meeting;
and then to Dartmouth Yearly Meeting, both which were very large,
and that evening was a meeting of ministers,
wherein I had much to say on several subjects proper to them.
Next day being the Yearly Meeting, it was very large,
there being a great resort of people many miles round.
It held three days, and ended to the satisfaction of most.
This evening, as I was going to bed, about ten at night, there was an earthquake,
which made a noise like the driving of carts or wagons on an uneven causeway;
it continued about two minutes, to the great surprise of the people.
It was felt about fifteen hundred miles, as was after computed,
and was thought by calculation to be not quite three hours in going that space.

From there I went into the island,
and took a last farewell of my friends in that part of the country,
having made a thorough visit among them.
The weather by this time grew very cold, it being the beginning of the ninth month;
however, I proceeded through Connecticut, to Greenwich Monthly Meeting.

From there Seth Aldrich, John Casey, John Earle and Peleg Spencer, accompanied me,
and we travelled into the Presbyterian country.
At a town called Preston, we had a small meeting,
and hearing of a funeral about three miles off, went there.
The people, who, as we apprehended were Baptists, seemed much surprised,
and our not joining a young man who prayed among them, made them look more shyly on us.
The poor man seemed in confusion, but when he had done,
we had a fine opportunity to good satisfaction.
Then we took our journey towards New London,
and on the way had a small opportunity with some Presbyterians;
such of them who were bigotted, were hard to speak to about the inward work,
they could not receive it.
From there to New London on Gratton side, to one James Smith`'s,
who was one of Rogers`' Baptists, but his wife was convinced,
and they were under great persecution both of body and goods.
I had a meeting at John Rogers`' on New London side,
and he objected against the universality of the light that saves, and about baptism.
He had much to say for the continuance of water baptism,
but at the same time would allow, that there was no real spiritual benefit in it;
and he asserted, that that Divine light which condemns for evil,
was but the tree of knowledge, and not saving; but Christ`'s light which saves,
was another thing; endeavouring hereby to divide between the light that condemns,
and that which saves, making them different from each other.
I took the Bible, and turning to the first chapter of John the evangelist, showed him,
that the light there spoken of, as the divinity of Christ the Saviour of the world,
was the same that condemned the disobedient, and justified the righteous;
it was not divided in itself, nor was it two, but one and the same in all:
and though the operation of this Divine light differed, that difference, it was plain,
was not in the light itself, but in the different objects on which it operated;
for example, the same heat of the sun that softens wax, will harden clay;
but this argues not two different qualities in the heat of the sun,
though the effect of its heat is different on wax and clay.
Although this, and but few other allegories will hold throughout, yet the people saw,
that his notion of two different lights, one saving, the other condemning,
has no foundation in the text.
Then as to baptism, he divided the institution of it into three parts; first, from John;
secondly, from the apostles practising it; and thirdly, from Matt. 28:19. I told him,
as he had already allowed that there was no real
spiritual advantage in outward water baptism,
his imaginary division of the institution fell of course;
for it was against reason to suppose, that anything ordained or instituted by Christ,
to be used in his church by believers, could be of no real service.
But you allow that baptism with water is of no real service,
therefore it is no institution of Christ: to conclude this head,
we may with the apostle say, that the outward ceremonies, as baptism, etc.,
will do no good to believers, but he only is a Christian, who is one inwardly,
and baptism is that of the heart, which is really serviceable and saving.
Thus we ended this conference: he was full of words, and confused in his notions.

I had then another meeting at Gratton;
after which we had an evening meeting at John Wood`'s,
which was the best we had among that people,
where some objections were made against public prayer, but were soon removed.
Afterwards at Colchester and Hebron we had good meetings among the people,
though it was very difficult to get a place to meet in at the former:
but a man of resolution offered a place, and there being a town-meeting that day,
we had a large company, who were very sober, no cavilling or disputes.
We came to Seabrook and Killingsworth and had meetings among the people who
had separated themselves from the Presbyterians and inclined to the Baptists,
who were getting into a lifeless form of singing,
and expounding in their own way and carnal manner,
which was likely to be a snare to their hurt.
We appointed another meeting among them, which was but small: all my friends,
save John Casey and John Earle, had left me.
We now set out for New York, but had no meeting till we came to Rye,
which was about eighty-one miles.
I was glad and comforted to be among Friends again, having been so long from them,
they being much more agreeable to me than other people.
From there I went to Mamaroneck, and over the ferry to Flushing,
it being their Quarterly Meeting, which held three days.

The meeting of ministers and elders was of good service,
among them were some young ministers; and at this Quarterly Meeting we had a solid time,
a large appearance of young Friends of both sexes being there.
After this I went with Joshua Fielding on his way to the eastward; and on returning,
I went to visit a Friend who was much afflicted with lowness of spirits,
and in a despairing way.
Although he had from his youth been a very sober and orderly man;
but Providence having favoured him with considerable substance,
he imagined he transgressed in having everything too fashionable and too rich,
and did not serve his Maker with his substance as he ought to do;
which was a great load upon him.

From there I visited Westbury on the plain: from there to Sequalogue, Huntington,
and Oyster bay, and had good and very full meetings.
At Matinicock and Hempstead, I had but middling times, though very large meetings.
I was rather more shut up than I had been for some time before,
and being desired to go and give the poor despairing Friend another visit, I went,
and found him much out of order, which made it unpleasant to be with him.
At Hempstead and Jamaica,
the place where I had been so long a prisoner twenty years before,
I had meetings but the latter was very small for lack of due notice.
Then to Flushing Monthly Meeting, which was much to my comfort,
not having had so good a meeting for some weeks before.
I here received some letters from Friends at the eastward,
which gave me agreeable accounts of the effects my labours had had,
by inclining some to come to our meetings, who did not before.
In several places where I had meetings,
there was a prospect of some coming nearer to the truth and joining the Society;
informing me also of the great earthquake before noted, which at Newbury, Haverhill,
Amesbury, and places adjacent,
continued at times for fourteen days and was felt
a long way on the banks of the Merrimack river.
The account was confirmed by many who declared themselves
afraid to remain in their houses during the several shocks,
which returned every twenty-four hours, and continued about three minutes.
The inhabitants blamed themselves much for their pride and luxury,
taking this to be a judgment upon them for those things.

I then went back to visit Westbury, Hempstead, Rockway,
and had meetings in all those places, and to Jamaica again,
where we had a large open meeting, and my old neighbours,
among whom I had been a prisoner in my first journey,
came generally and were glad to see me, as I was to see them,
and we had a comfortable opportunity together.
After this I visited Newtown, Flushing, and the Kilns by Newtown, having a large meeting;
and so to New York, where I had an evening meeting, not very large.
From there to the Narrows over Staten Island, and to Woodbridge, where I had a meeting,
and about three miles distant an evening meeting.
Then to Shrewsbury to their week-day meeting, which was very serviceable.
I then went to Middletown, where the Baptists lent us their meetinghouse to meet in,
although they had given the priest leave to preach there that same day,
so that the priest and his hearers came some time before our meeting was ended,
and enlarged it very much, no cavil or dispute happened, but all ended quiet and well.
At Freehold, we had a meeting in the courthouse to good purpose;
although the people were of an ignorant sort, who made no profession of any religion,
yet some of them were very well pleased with that opportunity.

I was next at meetings at Allentown and Crosswicks,
and went to visit a Friend who sometimes appeared in public,
and respecting whose ministry there was a difference in sentiment,
some approving and others disapproving;
and the young man had taken offence at those who did not like him.
We got some of the most disaffected together, and by conferring with them,
the young man and those who were dissatisfied came to a better understanding,
which was to satisfaction.
From there I went to Stonybrook, and Allentown, and Crosswicks again,
to the new meetinghouse, and to Mountholly, and had meetings at them all to content.
I was also at Haddonfield meeting, Woodbury-creek, Pilesgrove, Alloway`'s-creek,
and Cohansey; but the weather being excessively sharp with the extremity of frost,
the meetings were small.

From there to Salem, and had a very large open meeting there, and to Haddonfield,
and Philadelphia, travelling over Delaware river upon the ice above a mile,
and came to their week-day meeting, which was very small,
by reason of the exceeding sharpness of the weather.
The hardness of the frost in those parts is almost incredible:
a man could scarcely bear any part of his skin uncovered, for fear of being frozen.
I stayed in town over first-day, and from there to Frankford, Germantown,
Abington and Horsham, and so back to Philadelphia, and stayed their meeting of ministers,
and was at three meetings on first-day, which were very large and good,
especially the first and last.
Then I visited Haverford, Radnor, Newtown, Goshen,
and the Quarterly Meeting for the county of Chester, held at Providence,
which was very large, especially the meeting of ministers and elders,
the greatest part of the ministers in the province, and several from Jersey being there;
and I was very much enlarged in counsel and advice to them.
In the meeting of business I was drawn to show the qualifications of a true elder,
and the excellency of right government in the church,
which must first be known in our own minds;
for such who have not the government of their own spirits,
are not fit to undertake the government of others.
After this I had a meeting at Middletown, and so to Providence General Meeting,
but I had very little to say in either of these.
I went to Darby, and had a small meeting, and so to Philadelphia,
and had a brave meeting,
insomuch that I was filled with admiration at so
uncommon a supply of new doctrine every day,
which gave me cause to be more and more humble;
and when some Friends would speak in favour of such an opportunity,
or branch of doctrine, it would give me a shock,
lest by any of these unwary commendations,
I should take to myself that honour which was due to the Father of spirits,
and so fall into robbery unaware.

I went to Plymouth, North Wales, Buckingham, Wrightstown, the Falls,
Neshamony and Bristol, and had a satisfactory opportunity at each place,
though some were more agreeable than others, and they were very full meetings,
the season considered.
From Bristol I went to Burlington, and was at their meeting of ministers and elders,
but had nothing to say.
I stayed the first-day meeting, which was very large and serviceable;
it was the Quarterly Meeting time, and the meeting of ministers and elders,
and I having had such remarkable times among the
ministers occasioned these meetings to be very large.
At this meeting I was divinely opened with fresh matter,
setting forth the service of a spiritual ministry,
which was free from all contrivance and forecast of the creature,
in preparing itself either with former openings, or beautiful collections of texts,
or sayings from books or writings, all which gatherings would bring death,
and could be no other in the best and most favourable construction,
though well looked on by some, than the ministry of the letter,
under pretence of the ministry of the spirit, which is a deception of the highest nature.

Then I came into Pennsylvania to Wrightstown, was at their meeting of ministers,
and had a very agreeable time with them,
wherein was shown the danger of murmuring at the seeming
weakness of our gifts and giving way to a degree of dejection,
and neglect to exercise ourselves in them,
showing that every gift of the ministry was of service,
though but small in comparison of others, and had a great beauty in it,
and that we ought by no means to slight and neglect it,
but to be thankful that the Father of spirits has given us a gift, though but small.
And on the other hand, to exhort such as had a more elegant ministry,
not to value themselves upon their gifts, but in humility and with thankful hearts,
to render the honour and praise where due,
not looking with an eye of contempt on their supposed inferior brethren and sisters,
but in love preferring each other to themselves, considering, that plain diet,
handled by persons who have clean hands and clean garments,
though it be but mean to look at, yet the cleanliness of their hands and garments,
as also of the diet, renders it very agreeable and acceptable to the hungry,
and for others we need not be careful.
A Friend pleasantly said, after meeting, at his table, "`I might freely eat,
his wife was a cleanly house-wife,`" being willing to improve the simile to her advantage,
she having something to say, though but little, as a minister,
and her husband thought she did not give way to her gift as she ought.

Next day the Quarterly Meeting was held in the same place, which was pretty large,
and I was drawn to set the degrees of elders, as well as their different services,
in a proper light,
under the similitude of the various instruments made use of in erecting a building,
and that every instrument or tool had its proper service,
and every builder was to use them at a proper time, and not otherwise.
From there I went over the river to the Jersey side to a meeting, which was large,
and back to Neshamony again, and to Byberry, Abington, Horsham, North Wales,
and the great Swamp, and had some service and satisfaction in all these places.
I went to North Wales to a funeral, and to Perkiomen, where I had a small meeting,
and in coming from there had an evening meeting at a Friend`'s house,
whose name was John Jacobs, and from there to a funeral at Plymouth,
where was a great company, and a very good meeting.

I was at the Half-yearly meting of ministers and elders at Philadelphia,
to which sundry Friends came from Long Island.
I was largely opened to recommend a steadfast conduct with justice
and a single eye to Truth and its honour at all times;
and to set forth the service of elders and pillars in the church,
showing how a pillar standing upright would bear a great weight,
but if it leaned to either side, it would bend,
and perhaps break before it was set upright again;
warning both ministers and elders against party taking, and party making,
advising them as careful watchmen to guard the flock,
as those who must be accountable for their trust;
in particular not to dip into differences, the ministers especially,
either in the church or private families, but to stand clear,
that they might have a place with both parties, to advise and counsel,
and so they might be of service in reconciling those who were at variance.
I had a concern to caution the ministers, in their travels,
not to meddle with differences, so as rashly to say, this is right, or that is wrong,
but to mind their own service,
guarding against receiving any complaints of Friends`' unfaithfulness before a meeting,
which I had found very hurtful to me; for such information without a careful watch,
may influence the mind to follow it rather than the true gift.
I had also to caution the ministers, in their travels,
not to be hard to please with their entertainment,
but to show themselves easy and contented with such as poor Friends could let them have,
and to guard against carrying stories and tales from one place to another;
and that as soon as their service was done, to retire home again;
for some by staying too long after their service was ended, had hurt themselves,
and been an uneasiness to the church.
I had likewise to caution against appearing too often or too long in our own meetings,
but that the ministers should wait in their gifts for the Spirit to put them forth;
and carefully mind their openings, and not go beyond bounds, for if we do,
we shall lose our interest in the minds of Friends, and our service will be lost:
always guarding against seeking after praise,
or saying anything in commendation of our own doings,
neither to be uneasy when we have nothing to say.
Likewise to take care at large meetings, not to be forward or too long,
because a mistake committed in such a meeting did
much more hurt than it might do in smaller meetings.
I also touched upon the great duty of prayer,
requesting all to guard against running into many words without understanding,
but carefully to mind the spirit, that they might pray with it,
and with understanding also.

Next day the Half-yearly Meeting began, being the first-day of the week:
I was largely opened to show the difference between the true and false church,
setting them side by side, that they might judge for themselves.
I stayed all that week in town, the meeting not ending till fourth-day.
I was at the first and third-day meetings following, and so took my leave.

From there I came to Darby, Springfield, Merion, Chester, Chichester,
Christiana-creek and Newcastle, and had tolerably good meetings.
Friends being acquainted that I was now taking my leave of the country,
the meetings were very large, and several of them to good satisfaction,
much openness and brokenness appearing.
From there I went to George`'s creek.
Duck-creek, Motherkill, Hoarkill, Coldspring, and so back to Motherkill and Duckcreek:
and had pretty good satisfaction in these meetings.
The Friends in these parts were seldom visited, and but very few ministers among them.
The priests, both Church and Presbyterians, attempted to do something,
but the people being poor and the pension small, they gave out for lack of payment.

I was at the Half-yearly Meeting at Chester in Maryland,
but the weather being very unseasonable, made it small; it continued two days,
and the last meeting was the largest and best.
From there to Cecil, and to Gilbert Faulkner`'s, and John Tibbet`'s, and Duck-creek,
where I had good opportunities,
and took my leave after having one small meeting about nine miles distant,
and so went for the Quarterly Meeting in Maryland, at Third-havencreek,
which was held in the great house; a good meeting,
but I found some difficulties and misunderstandings among them which did much hurt.
Next was at a Monthly Meeting in the same place,
where the uneasiness appeared more plain, but endeavours were used to reconcile matters,
and put a stop to the uneasiness.

From there to the bay-side, Tuckahoe, Marshy-creek, Choptank,
and had meetings in all these places, also to Francequaking, Chickcomaco, Nanticoke,
and over Vienna ferry to Mulberry-grove, where I had small but comfortable meetings,
and at the widow Gale`'s at Monay, at Annuamessicks, at John Curtis`',
and at Thomas Crippin`'s, there being no meetinghouses in these places.
One captain Drummond desired a meeting in his house, which I assented to,
and it was to good content.
He was a judge of the court, and a very sensible man.
I went from there and had a very good meeting at Edward Mifflin`'s, who was a fine,
zealous elder.
He carried me over the bay in his boat, about twenty leagues, to Nansemond;
we landed at old Robert Jordan`'s, and were at their week-day meeting.
From there I went towards Carolina,
Joseph Jordan accompanying me on my way to Nathan Newby`'s.

Next day I went to Pascotank, and had a fine open meeting, which was very large,
for the inhabitants mostly came to meetings when they expected a preacher,
and often at other times.
I visited a young man in the neighbourhood, a valuable minister, but in declining health;
we had a comfortable time with him, he being in a good frame of mind to die.
From there to Little river and to Perquiman`'s booth,
to the upper and lower meetinghouse, and had very large meetings.
Gabriel Newby accompanied me towards Virginia back again;
the first meetings we had were at the Westernbranch, Pagan-creek,
and at Samuel Savory`'s; we had a comfortable time at the last place.
Then to Swan`'s-point, and over James`'river to Williamsburg,
and had a small meeting at each of these last places: Joseph Jordan being with me,
we paid the governor a visit,
and interceded for his favour on the behalf of some Friends
put in prison on account of refusing to bear arms;
he was very kind,
promising to do what lay in his power for them and our people in general,
and in a little time the Friends were set at liberty.

We then went to Skimino to the widow Bates`'s, and were at a Yearly Meeting at her house,
which was pretty large and open.
From there to Black-creek, and to Curl`'s, and had tolerably good meetings.
We had a meeting of ministers and elders;
though there were but few ministers in those parts,
but we had a suitable opportunity to good satisfaction; and indeed it not often fell out,
that in such meetings I was without matter adapted to their states.
Next day was the public-meeting, and the following day I was at Wainoak,
which were large and well, and Joseph Jordan had excellent service in the last,
but I had very little to say.
Then to the Swamp, and to Grassy-swamp, Cedar-creek and Dover, and had fine meetings,
people being very ready to attend them.
I went back over the river to Robert Hunnicutt`'s, Lemuel Hargrave`'s, Somerton,
and to Nathan Newby`'s; in all which places I had meetings,
and some of them very large and open.
From there into Carolina to their Quarterly Meeting,
and had a meeting at James Griffith`'s house.
From there to Little river on the seventh-day of the week,
and first of the Quarterly Meeting: the meeting was very large;
I took my leave of Friends, and we had a baptizing time together.
I returned back to Virginia, and was at Nansemond meeting,
and had a large edifying meeting at a Friend`'s house.
Then I came to the Branch, and Chuckatuck, to their Monthly Meeting,
but Robert Jordan had all the time, that being his last meeting,
he being about to embark for England, in the same ship with me to visit Friends.
A meeting was appointed at Arnold Wilkinson`'s, which was small,
after which I went to Robert Jordan`'s, having been made exceedingly welcome,
and had several good opportunities in the family.
I went to but two or three meetings more, getting myself ready to return home,
and accordingly we took leave, and came down the river to Hampton Roads,
but missing the channel, were forced to lie aground by Newport`'s-Nose,
near twenty-four hours before we could get to Hampton, and when there,
stayed about a week and four days.
George Walker was very kind, invited us to lodge at his house,
where we stayed about four nights, and had a meeting or two,
his wife being more loving than I expected: she was George Keith`'s daughter,
and in her younger days showed great dissatisfaction with Friends,
but after her father`'s death that bitterness abated,
and her husband was very loving and hearty to Friends,
frequently having meetings at his house.

We laid wind bound a week and four days, when the wind sprung up fair,
and we weighed anchor the 29th of the fifth month, 1728, with a fresh and fine gale.
Robert Jordan seemed much pleased that we were on our way,
and a secret joy filled my heart,
being thankful that I had been preserved so well in health,
and assisted with strength both of body and mind
to accomplish this long and tedious journey,
through the severe extremes of heat and cold, in about eighteen months,
and missed but seven meetings which were far back in the woods, namely:
one in the government of New York, two in the Jerseys, and four in Pennsylvania.
I was not easy to miss them, but my friends thought the weather and season of the year,
together with the great scarcity of provision both for man and horse, and the deep snow,
with the extremity of the frost, rendered the journey hazardous, if not impracticable,
and I could not see it my place to stay till the winter broke up; besides which,
by staying so long I should have lost my passage by the homeward-bound ships.
I should have been willing to take those meetings, if I could have saved my passage,
and accomplished the journey so as to waste no time,
but go on diligently as I had done before.
There were but very few meetings I had not visited two, three, and some of them four,
five, or six times, being situated in my way in passing to and fro.
I was not hindered one hour in all this time by any disorder or sickness,
or any accident, I think I may safely say.
Friends had sent word to appoint a meeting for me about thirty miles on my way,
but the weather was so extremely tempestuous, that when we came there,
no meeting was appointed, for it was concluded I could not possibly come;
so I was under a necessity to stay one day longer in that place,
which was the greatest hindrance I met with in all the journey that I remember.

To return to our voyage.
About two hundred and fifty leagues from land, as we thought,
the water seemed like a river after a hasty storm of thunder; on seeing which,
our people were surprised, and tried with the lead for ground, but could find none.
It was so uncommon a thing that the sailors could not tell what to think of it:
this was about the 15th of the sixth month.
We had fine pleasant weather, and a great plenty of dolphins and other fish,
for which providence I was very thankful.

On the 22nd of the same month, about three in the afternoon,
a gust of wind came from the north; such a hurricane as our sailors said they never knew,
which bore so unexpectedly without any warning upon us,
that to all appearance our ship would be in a moment swallowed up in the sea,
the waves running over us,
and the water coming into the great cabin windows and the forecastle,
so that from five or six inches of water in the hold, it so increased,
that we had more than as many feet in a few minutes.
The decks seemed as though they would break down,
being so very heavy with the waves breaking in upon them;
which staved above a ton and a half of water in casks fastened upon deck,
washed some hogs overboard, and several dozen turkeys, geese,
and other fowls were drowned, which afterwards were much missed by us.
Besides all this, the wind tore our sails like paper, broke our foretop-mast,
and several of the yards, like rotten sticks, and the round foretop;
the ship by the violence of the tempest lying on one side,
as though she would not right up again,
so that they were for cutting away her masts and rigging.
I begged the master not to do it, but to trust to Providence,
for I was satisfied she would rise again as soon as the wind abated:
the wind began to abate in a little time, and the ship righted up,
but the tiller of the rudder being broken,
it was very dangerous until they got the rudder fastened, which,
in a little time before it was dark, was effected with great difficulty and danger.
The sea running high, tossed the ship very much, and came in with such violence,
that for some time there was no other appearance but of foundering and sinking immediately,
especially until the rudder was put to rights.
When they had gotten the command of the rudder, there were some hopes of relief,
but while the rudder was at liberty there was no commanding the vessel,
but she lay at the mercy of the sea,
and it seemed as though that would carry away her stern.
When we had got in the dead lights, and secured ourselves in the best manner we could,
all hands began to pump, for we found between seven and eight feet of water in the hold,
but the tossing of the ship made it so difficult to guess right,
that it might be more or less.
Having a good ship, new and firm, our hope increased,
but we were all very wet and fatigued, and it was a dark and troublesome night.
We longed much for the day, but the wind abated,
not lasting above two hours so very strong.
When day-light came we were glad, but that was soon turned into mourning,
by discovering the mean state of our ship, especially the rigging and sails,
and finding our great loss of water and fresh provision, things of value,
next to life itself. These losses were cause of trouble,
but by grieving we could not help ourselves,
but in turning the mind to that Divine Power and Providence who is present everywhere,
ruling both by sea and land, and whom the winds obey,
I found comfort in meditating on his promises to
care for those who put their trust in him.

Our men, who were all preserved from any other damage, than the taking of cold,
of which we all felt the effect to a great degree,
went about putting the rigging to rights again,
which took up a week before we could make sail, the wind blowing strong and variable.
When they had got things in a good condition, the wind was against us for several days,
which made us thoughtful to take care of what water and provision we had,
that we might not be surprised with a shortage,
when we had not power to provide against it.
The men were all called up to hear our proposal,
which was to give every man three pints of water for twenty-four hours,
and five pounds of bread for a week, having other provisions, both fresh and salt,
a good stock, to the full allowance.
At this there was some uneasiness;
but at this rate our provision would hold out by our calculation for about four weeks,
so that if we saw not some hopes of getting in, in two weeks,
we must come to less allowance again.

The wind continued against us until the 7th of the seventh month,
and then veered a little to the southward,
and apprehending ourselves to be too much to the north,
we were not willing if we could avoid it, to put into Ireland;
but in about three days after we had a fair wind, which lasted for some days,
and gave us hopes of seeing land, which we much longed for,
being threatened with lack of bread and water, if Providence did not interpose.
Our hearts were cheerful, and gladness appeared in every countenance,
but alas! it was a short-lived joy,
for in the forenoon on the 13th the wind died away again,
and about five in the afternoon we sounded for ground, but found none.
This made us all look pale, and sadness appeared in every countenance;
and our ship being a dull sailer, added to our trouble,
fearing that we were further from land than we thought by our reckoning.
The greatest comfort we had, was a good ship under us, though a heavy sailer,
therefore we cheered each other with the hope of
gaining our port in due time with safety and comfort.
Thus I moralized to myself,
considering the resemblance of our voyage to a Christian`'s progress through this life,
sometimes in a degree of prosperity, encouraged to press forward with a fair wind,
and anon under as great adversity and discouragement by temptations,
persecutions and afflictions.

In two days more we sounded, and found ground at eighty-two fathom,
judging ourselves from the Lizard sixty leagues,
but the wind veered and blew seven days so strong
against us that we were driven from land as we thought,
a hundred leagues.
This made us talk of shortening our allowance again, but that night,
about twelve o`'clock, the wind veered in our favour, and the sailors cried,
a large wind, a large allowance;
nothing being more disagreeable in its kind than a large wind and short allowance.
The wind being fair, we went on with cheerfulness,
and upon the credit of this fair wind some of the
men had not a morsel of bread left by night,
nor a spoonful of water, and had near thirty-six hours of their week to come.
However, we went along so agreeably that every body looked pleasant;
but this lasted only about sixteen hours before it came right in our teeth again,
and blew very strong.
Such ups and downs we had that the sailors grew very uneasy, and cursed and swore,
no did not stick to blaspheme in a way that was very unpleasant to hear.
This did not last long before it was calm, and the wind came up fair again,
and we speaking with a ship outward bound, they gave us new heart,
by advising us that Scilly bore from us north-east about twenty-two leagues distance.
This day we spoke one of the king`'s ships called the Dragon, from Jamaica,
and in the evening saw several ships coming in; which was very pleasant,
besides a fine gale in our favour,
so that on the 27th we saw the land about five in
the evening and a ship to windward bore down to us,
and told us it was the Lizard,
and we judged that it bore E. N. E. from us about six leagues distance.

Next day the wind was against us,
turning in the night E. N. E. so that we lost sight of the land again,
but tacking and standing the other way we soon saw it, and having the tide,
though but a scant wind, we shot in a considerable way.
After the tide was spent we thought we lost ground,
but the wind veering to our advantage, and a better gale, helped us much,
so that on the 28th we shot pretty near in, thinking to have put into Falmouth,
but the wind being still more favourable, we stood for the Ramshead;
then it grew almost calm, so that what we got by the flood we lost by the ebb,
and we could but just discern the Eddystone like the mast of a ship, through a glass,
and scarcely at all with the naked eye.

On the 29th, it being the first-day of the week,
having a fine tide and good wind in our favour,
gave us some hopes to get into Plymouth by meeting time,
the very thought of which was agreeable; but by eight in the morning we found,
to our sorrow, the tide against us, and the wind dying away.
We lost ground, but shortly after the wind blew pretty strong and fair;
and we found we stemmed the tide and got a little forward, and when the ebb was spent,
the flood with the wind came in very strong, though a neap tide,
so that we raised the land very fast,
and about two in the afternoon came abreast the Eddystone, about a musket-shot from it,
and had a full view thereof.
In about a quarter of an hour after this, pilots came off,
several ships wanting safe conduct, and about nine we got safe to anchor,
just by the passage against Edgcombe house.
On the 30th I landed at Plymouth, and stayed in town that day,
and was very thankful I was safe on shore again,
I having been just nine weeks on our passage,
and the last five of it a very trying and afflicting time,
but the four first were pleasant and comfortable.

I took horse the 1st of the eighth month, 1728, and came to Exeter that night.
Next morning being the 2nd of the month and fourth of the week, I came home,
and as I entered my own house, the inward comfort and pleasure which I felt,
ravished my heart, that I could scarcely forbear to cry out,
God! that God who judges men, is just in all his ways,
and rewards peace into the bosom of those who fear and obey him.
And being by all my family and friends kindly received,
my return was exceedingly delightful.

In about twenty-two months and some days I finished this journey,
and in that time I travelled by land and over rivers about
five thousand three hundred and twenty-two miles,
besides passing and repassing the great ocean.

I had been out of that country somewhat more than twenty-one years,
and found so great an increase of the professors of truth,
that I had a curiosity to examine a little into it,
finding most of the old meetinghouses very much enlarged, some-to hold double,
and some triple, and some four times the people that the old ones would,
and even now some needed to be enlarged, or new ones built at proper distances.
Besides these, new houses were built in that time in places where none had been,
nor any meetings but what were kept in private houses, which grew so numerous,
that necessity put Friends upon erecting houses to accommodate themselves.
In New England and Rhode Island there are twelve: in the government of New York are six:
in both East and West Jersey are nine: in Pennsylvania thirteen: in Maryland four:
in Virginia nine: in North Carolina three.
In all there have been fifty-six new meetinghouses
built within these twenty-two or three years past,
and in these provinces there are about ten places where they need houses,
and many old ones ought to be enlarged, not having room for half the people.
This extraordinary increase of professors is much to be attributed
to the youth retaining the profession of their parents,
and marrying such: for most of the people in Pennsylvania are of this profession,
as well as in the Jerseys and Rhode Island,
so that young people are not under the temptation
to marry those of different judgments in religion,
as in some parts.
Being safely returned home, I was diligent in minding my business,
and attended public meetings, funerals, etc. until the year 1740,
at which time I found a concern to visit some parts of the North, and Ireland,
which comes next in course, with respect to both time and place.
