== Chapter VII.

An account of my travels into the North of England and Ireland the second time,
in the year 1740.

After having acquainted my friends with what I had in view,
requesting as is usual in the like cases, a certificate from the Monthly Meeting,
which was readily granted, I left my house the 1st of the third month, 1740,
and went to the funeral of my intimate friend, Thomas Gary, of Long Sutton,
where the meeting was very large and well.
From there I went to Street, and so for Bristol to the Yearly Meeting,
which was attended by many Friends, and was very much to satisfaction.
I was largely opened both in the public and select meetings of ministers and elders.
Leaving that place I went to Bath, Bradford, Melksham, Chippenham, and Cain in Wiltshire,
and in all these places had meetings to good satisfaction,
though in some more than others.
At Newbury, Reading, Wickham, and Uxbridge, I had meetings, which were satisfactory.
And then to London to the Yearly Meeting,
where I was more particularly enlarged among the
ministers than ever I had been before in England,
which gave me some apprehension it was to be my last visit, and when I was taken sick,
it seemed to confirm it.
I had likewise a very good time in the parting meeting,
which confirmed me that I was in my place.
From there I went to Hertford, to their Monthly Meeting,
and stayed three meetings in that town; then to Ware and Royston,
and had considerable meetings in both places.
Then into Essex to Saffron Walden, Thaxsted and Coggeshall, and had tolerably good times;
so to Colchester Yearly Meeting, which was very large,
and I had the company of John Gurney and Joshua Toft,
who both had very eminent service in that meeting.

I was taken ill with a cold, yet had so good a time among the ministers,
that I thought myself almost cured; but after meeting riding to Bury,
it brought such a fever upon me, that I thought I could not survive it,
and this seemed to confirm my former apprehension,
from that uncommon enlargement I had among the ministers in London,
that I should never have another, and this notion grew upon me,
adding much to my lowness of spirits.
I was obliged to tarry a week with my friend John Drewett, at Bury,
and his kindness and tenderness over me in that low, weak condition,
was very comfortable; he conveyed me to Mildenhall in his chair, but I was very weak,
and obliged to stay at Joseph Ellington`'s one week longer,
who was also very kind and tender over me.

From there I went to Brand, and through some part of Norfolk into Lincolnshire,
and had very large meetings at Lynn, and at Gainsborough, at a funeral,
and meetings at several other places, which were large.
I met my dear friend Joshua Toft at Lynn, and he was with me at Gedney,
and other meetings between that and Gainsborough, and then we parted,
and I went into Yorkshire, and had several large meetings, as at Leeds, Rawdon, Bradford,
Skipton, Settle and Sedberg; at which last place my mouth was first opened in ministry,
and on first-day to Kendal, and had two large meetings,
and then went directly for Whitehaven by Cockermouth,
but had no meeting till I came to Dublin, staying in Whitehaven but about two hours.

I took shipping the 1st of the sixth month, 1740,
and landed safely at Dublin the 4th. I stayed there two first-days,
being under some disorder, and then went to Drogheda and Monallen,
where I was very particular about the call and qualifications of true Gospel ministers,
showing that wicked men could not be such; and from there to Lurgan,
and had satisfactory opportunities, Michael Lightfoot being there at the same time.
I was at one meeting between that and Lisburn,
and went to the north as far as Ballimurry, and then returned to Toberhead,
Old Castle and Coothill, visiting meetings on that side to Limerick, and so to Clonmel,
Youghal, and to the province meeting at Cork,
back by Waterford to a province Quarterly Meeting at Mountmelick,
visiting the meetings as I went to Montrath and Edenderry.
Then I went to Dubhn to a marriage, where for some time I had hard work,
but it ended very well; and from there I went into the country to Wicklow and Carlow,
visiting the meetings until the national Half-yearly Meeting at Dublin,
about the 11th of the ninth month.

I found in that nation a brave,
zealous and living people in the root of true religion and discipline,
or church government, well qualified with experience in Divine wisdom;
but there were also some who seemed very perfect in the form,
and appeared to the outward very exact and zealous against pride and worldly customs,
but for all that, the inside was not right,
so that I found often very close exercise among them,
in warning them against the leaven of the pharisees, which was equally,
if not more hurtful to religion than that of the publicans.
In some places,
I was led to show that it was needful to be good examples in plainness of speech,
as well as apparel, which many had deviated from; but nevertheless such there were,
who though plain, and otherwise strict,
were too much taken up with the world and the riches of it,
making haste to increase their substance,
which was a very great hindrance to their growth in the life of religion,
and made them dwarfish therein; setting forth, that a form, without life,
whether by education or otherwise, would not avail.
I also warned the ministers, in the exercise of their gifts, to keep to the Spirit,
and mind carefully their openings,
and not to preach the letter under a pretence of the Spirit,
and so instead of ministering life, minister death to the people.
In the main I had great comfort and many very good opportunities.

I left that nation full of peace in my own mind, being glad that I went there:
I was at eighty-two or eighty-three meetings in it,
and took shipping the 19th of the ninth month, 1740,
in company with my dear friend Michael Lightfoot, for Workington,
and was but twenty-four hours on the water; it was a rough though very quick passage;
my friend was very sick, and I was also, but not to the degree he was.
We hired horses to go to Whitehaven, it being about six or seven miles,
and stayed there till next day, it being first-day, and had two meetings,
the last very large.
I visited meetings in and about Cockermouth and Pardsay, many of which were very large,
and then by Keswick to Hawkshead, where I was much comforted,
being at a friend Lancaster`'s house at Colthouse, and had two meetings there,
which were very full.

I went to Kendal, but had no meeting, and next morning to Sedberg to the General Meeting,
which was small by reason of a deep snow and very hard weather.
From there to Preston Patrick, and to Crook, and had a small meeting,
then back to Kendal to their week-day meeting, where was a funeral.
It was very bad travelling by reason of the snow and frost,
but I went to Cumberland Quarterly Meeting, by Carlisle and Moorhouse to Wigton,
where it was held; and considering the season, it was very large; holding two days.

At a meeting of ministers and elders held in the evening, I was much enlarged,
as well as at the other meetings.
I returned back to Penrith, accompanied in this Journey by my friend Rowland Wilson,
who was of great service to me at Penrith we had a very large evening meeting,
to good satisfaction; the dissenting teacher, with many of his hearers were there,
and it ended well.
From there to Teril, and to the Monthly Meeting at Great Strickland,
and so by Shap to Kendal,
where I was at three meetings besides the Quarterly Meeting and the meeting of ministers,
all very large and satisfactory.
I took my friend John Wilson`'s house for home at Kendal, and James Wilson`'s at Sedberg,
stayed their first-day meeting, and had an exceeding large meeting in the evening.
That meeting, with Cockermouth and Whitehaven,
were the largest meetings I had in the north during that journey.
From there to my old friend Robert Chambers, and to Preston General Meeting,
which was pretty large, but I was much shut up in it;
and after meeting James and John Wilson, with Robert Chambers, and sundry others,
accompanied me to the Quarterly Meeting at Lancaster, which began next day,
and was very large.
These Quarterly Meetings of Cumberland, "`Westmoreland and Lancashire,
were three of the largest that I remember to have been at, one after the other,
in so short a time, and they had an excellent economy in the management of their affairs;
but there was no meeting of ministers at Lancaster at this time.
It may be justly said, I think,
that these three counties are in a thriving way in the life of religion and true godliness.

Having received information from my dear wife,
that she was weakly and wanted me to return,
I was prevented from visiting the North as I had in view,
so that from Lancaster I had no meeting till I came to Manchester,
where I had two good meetings.
From there to Stockport, Macclesfield and Leek, and had small meetings at each place.
At Birmingham I had two meetings, the last a funeral, pretty large,
but not so edifying as I could have desired.
From there to Worcester, Gloucester and Bristol,
and had meetings to very good satisfaction, especially at Worcester and Bristol.

In this journey I travelled, exclusive of the sea, sixteen hundred and eight miles,
and save my illness at Bury, had my health as well as I could expect,
being humbly thankful,
that I was strengthened both inwardly and outwardly to accomplish my journey so well,
not having that I remember, left anything undone in that nation,
save something I had to say in the men`'s meeting at Dublin,
but their hasty breaking up prevented it, which gave me uneasiness for some weeks after,
and I remark it here for a caution to others;
for I missed such an opportunity as I could nevermore expect to have,
and this added to my uneasiness.
I saw that my fear of breaking in upon the meeting, and hindering their business,
made me lose my time, so that I came off with a burden upon my mind.
