== Chapter VIII.

[.chapter-subtitle--blurb]
An account of my travels since the decease of my wife,
who after a lingering illness departed this life, the 6th of the third month, 1746.

I set out from home the 27th of the fourth month, 1746,
towards the Quarterly Meeting at Liskard in Cornwall,
which in that county and Devonshire, are usually called Yearly Meetings,
and had two small meetings in the way, at Collumpton and Oakhampton; then to Launceston,
where we had a very large meeting, the place considered,
the people being very sober and attentive; the Gospel flowed freely to them,
and I was much comforted.
I went to Liskard to the Quarterly Meeting,
which owing to the unseasonableness of the weather, was smaller than usual,
there being few besides Friends, but things were tolerably well;
and from there to Plymouth; Friends of both counties attend these two meetings.
After which I had a good meeting in the evening at the Parish,
where I think but one family of Friends dwelt, though many people came to it;
then to Kingsbridge, and so for Exeter,
and was at their week-day meeting but had nothing to say;
and going by Collumpton to Chard, returned home,
where I stayed until it was time to set out for the Yearly Meeting in Gloucestershire,
held at Hampton Road, which being well supplied by able ministers,
was thought to be of good service.

I returned by Bath, Froome and Shipton Mallet, had three meetings at Bath, one at Froome,
and one at Shipton, all to very good satisfaction, and then home,
where I stayed some time; but finding the constraint of love to visit London,
I waited to be clearly satisfied in the undertaking,
and was not easy to go till the 20th of the eleventh month.

I went by Bristol, where the meetings were very large; I stayed two first-days,
and had very good satisfaction in being there, then to London through Wiltshire,
and had a tolerably satisfactory opportunity in the evening at Chippenham,
where many strangers came in; next to Cain, and had a meeting,
but not quite so satisfactory; to Marlborough, and had a very open time,
many neighbours coming who were very sober and attentive; to Newbury,
and had a small meeting; to Reading,
and was there on first-day both morning and afternoon, and had good satisfaction.
From there I went to Maidenhead, where several Friends from London met me;
and I went to a meeting at Uxbridge, appointed for Hannah Harris; and so to London,
and was in town four weeks.
I visited all the meetings, and some of them sundry times over,
and had sometimes great satisfaction and comfort, but at other times I was very low,
and under great poverty of spirit.
The first-days were hard service;
the evening meetings at Grace-church street were very open,
and the Gospel flowed very plentifully, at which a variety of hearers frequented,
of different states and professions, but the fountain being opened,
there was a supply suitable to their conditions.

After I was clear of the city, some Friends accompanied me to Esher,
where we had a small but pretty open meeting; from there to Guildford,
where we had a very small and poor meeting.
I queried, why they did not give their neighbours notice?
To which they answered, they did not use to do it.
There is a very great remissness among some Friends in this respect;
if they were diligent, and desirous to have the company of their neighbours,
where the minister is so concerned, it might be of great service to them.
I went from there to Godalming, where we had a very large and open meeting; to Alton,
and had two very agreeable meetings; and to Winchester, where were but a few Friends;
then to Rumsey, and had a small meeting; so to Ringvvood week-day meeting,
which was small, but pretty well; to Pool, and had a meeting or two there, and then home,
being very glad that I succeeded so well, both as to health and ability of mind,
getting home about the middle of the second month, 1747.

I visited the meetings in my neighbourhood, until the 9th of the third month, 1747,
and on that day took my journey for Bristol Yearly Meeting,
which was very large and well.
From there to the Quarterly Meeting for Gloucestershire, held at Thornbury,
where I had a very satisfactory time.
I went to Nailsworth, and was taken unwell in the night, but went to meeting,
although not very fit for it; my dear friend Richard Champion came there,
and I went with him to his house.
The respect and kindness he showed,
proved that he was an excellent sympathizing friend in affliction for my encouragement,
he went to Worcester with me, the meetings being appointed so far.

I was bravely recovered by the time I got to Worcester,
was at three meetings there on first-day, and had good satisfaction and peace in them.
I went from there to Broomsgrove, and had a small but comfortable meeting;
and to Birmingham, where I stayed seventh-day, and went to Coventry on firstday,
and was at two meetings there, which were both open and well;
but the latter more so than the first.
Then to Hinkley, Leicester, Castle-dunnington, and to Nottingham on first-day,
where I was at two meetings, but few besides our own professors were there;
the meetings were tolerably well.
I had not very agreeable service, to my own apprehension, in some of the above meetings,
though some Friends thought my doctrine suitable to their states,
and that is the chief end which we ought to aim at.
I went to Mansfield, and had a very full meeting at a funeral,
with which I had great comfort and peace: then to Chesterfield, Sheffield and Warnsworth,
and had tolerably good opportunities; and to York Quarterly Meeting,
where I had good service.

From York I went into Holderness, taking meetings to Beverly,
where was a Monthly Meeting, which was I hope serviceable,
being a large gathering of Friends and other people of different persuasions;
then to Hull, Wehvick, Oustwick, Hornsey and Burlington.
Oustvvick was a very large meeting, the others but small, but not to complain of;
from there to Scarborough, where I was at two first-day meetings,
which were large and comfortable.
I had seven meetings in that place to good satisfaction;
then I had a small meeting at Staten-dale, and so to Whitby,
and had three meetings there, but they were laborious, being pretty hard to get through.
At Moorsam and Castleton, I had a small meeting;
it being harvest-time many Friends could not attend.
From there to Kirby Moorside, and lodged with my dear and worthy friend John Richardson,
at Hutton in the Hole, and was at a very large meeting at Pickering,
called a Yearly Meeting, but it did not answer expectations,
many of the people who were not Friends, coming to it as to a revel,
and would afterwards get drunk before they went home, which gave Friends much uneasiness,
and room to consider whether it was best to continue it or not.

I returned to my old worthy friend John Richardson`'s,
whose conversation and company were very agreeable and profitable; then to Kirby,
and had a very comfortable meeting; then to several small meetings,
which were pretty open and edifying.
At Yarm my friend Thomas Couldwell, of Darlington, met me;
who had a few words in meetings to good satisfaction; and was an innocent reputable man,
both in ministry and conduct.

James Wilson went with me through the county of Durham,
where we visited most of the meetings.
From there we went to Allendale, and had a pretty large gathering of Friends,
the Monthly Meeting being there; their business was well conducted,
and the affairs carried on to edification and comfort.
At Allenstone Moor, I had a pretty large meeting, and a comfortable opportunity,
it being Monthly Meeting also: from there to Cornwood, which was pretty full,
and I had an agreeable time.
There being here some convincement,
I was opened to show the difference between a true and false ministry,
demonstrating the qualifications of each,
that they might judge whether a spiritual qualification,
which sanctifies and purifies the conscience,
fitting it for receiving the knowledge of the Divine will,
by inspiration of the Holy Spirit; or a human qualification by literature and books,
with what they call ordination,
too often without the sanctification of the heart by the word of Truth,
was most likely to advance the work of true religion.

From this place we went into Cumberland,
but after the first meeting James Wilson went home.
I visited Cumberland pretty thoroughly, and at Coldbeck was taken so ill,
that I could not attend that meeting.
From there I went to Isel and Cockermouth, Pardsay and Whitehaven,
but I was very weak and low in my spirit, which rendered me very unfit for service.
I was at Workington on first-day, and had a very large and open meeting,
so that I was finely recruited, and gathered strength both inwardly and outwardly.
I went to Broughton, Allonby and to Holm, where was a troublesome woman,
in whom an opposing spirit was very strong.
She gave some disturbance, especially to John Urwin, but no body said anything to her;
and after I had spoken some time, and concluded,
she stood up and expressed something to this effect;
"`Here are a great many fine words put well together, but where is the life?`"
And in meetings she would often cast forth reproaches and reflections on ministers,
both of the same county and also strangers.
From Holm we went to Wigton, and I stayed there over first-day,
and had two very edifying meetings; then went to Moorhouse,
and had a tolerably good meeting, and so to the Quarterly Meeting at Carlisle,
which was very large, and I had good satisfaction both in meetings of business,
and the meetings of ministers, to my great comfort.
These meetings very much restored me,
for I had been very low and weak with the disorder I took at Coldbeck,
but my friend John Urwin was of singular good service to me.

In the visit from Carlisle to Penrith,
I went with my friend John Wilson and his brother Crewdson,
who were so kind as to meet me at Carlisle, and we had a very large, good open meeting,
and I doubt not the power of Truth was eminently felt that day by some.
I went to Great Strickland Monthly Meeting for discipline, and to Shap,
and had some service, although I was dejected and low;
and always when I was in that condition, I endeavoured in secret to be still,
waiting in patience,
with fervent prayer that I might be preserved in the simplicity of the Gospel,
to appear just as the Truth assisted,
carefully guarding against forming any image or likeness, from a wrong root,
lest I should offend my Master as Israel did in Moses`' absence,
by forming to themselves that dumb, lifeless idol the calf,
to worship after the manner of the Egyptians.

From Shap I went to Kendal, to the Quarterly Meeting for Westmoreland,
which was very large, and I was much opened in it,
having very satisfactory service both to myself and Friends.
I went to Lancaster to the Quarterly Meeting for that county,
and had there very agreeable service.
The Quarterly Meetings of Cumberland, Westmoreland and Lancashire succeed one another,
and are the largest of any I know in this nation.
I stayed at Lancaster over first-day, and had some service at their two meetings,
both pretty large.
From Lancaster I went to Yelland, and had a small hard meeting,
and to Preston meeting next day, which was small and heavy; my friend Sarah Wilson,
James`' wife, and some other Friends from that side, met me there,
with whom I went to Brigflats meeting, which was a fine gathering,
and I had a comfortable time.
Then to Dent`'s town, to a General Meeting, which was pretty large and well:
from there to Garsdale and Ravenstonedale,
and had two small meetings which were edifying,
although not without some mixture of uneasiness and trouble,
chiefly occasioned by unfaithfulness and indolence prevailing on some of the professors,
from whom one might expect much better by their appearances,
and the places they aimed to fill in the church.

I was at Brigflats meeting on first-day;
and their Monthly Meeting for discipline being on the fourth-day following,
I stayed there, and all was conducted to edification and comfort; from there to Grayrig,
a small meeting; and to Crook, where some Friends from Windermeer met me;
it was but a small meeting, and we had a low poor time.
I came back to Kendal, and was at the first-day meetings;
that in the afternoon was large,
and I opened pretty clearly the difference between a natural and a spiritual state,
showing the necessity of the last,
in order to qualify for the knowledge of Divine things,
as that knowledge is not to be attained by the natural man;
we had an edifying and good time.

I went from Kendal to Bentham, and had a large meeting to satisfaction; then to Settle,
and was at their Monthly Meeting for discipline; to Skipton,
and had a small meeting there; and so to Bradford, where I was on first-day,
and had pretty good satisfaction.
This week`'s labour gave me a good degree of ease and cheerfulness of mind.
I was also at Rawden, Leeds, Gildersome and Bradford Monthly Meeting,
which was very small, chiefly occasioned by the inclemency of the weather,
the rains being very heavy and a great flood.
I returned to Leeds, and so back to Rawden, and to the Monthly Meeting at Asquith,
where I met with dear Benjamin Kidd; the meeting was pretty large,
and I think to good purpose.
I returned to Leeds on first-day, it being my last and farewell meeting.
The widow Horner`'s house was my home,
and in it I had great peace of mind and consolation,
though she was at that time under a very trying exercise,
which gave her some uneasy thoughts; but considering the close trials she had undergone,
she bore it with great patience, plainly demonstrating,
that she was favoured to dwell near the Truth;
to the comfort of her family and sensible Friends who had
the opportunity of her desirable and edifying conversation.

I left Leeds, and went to Wakefield to a funeral,
on which account the meeting was somewhat larger, though it was a very stormy day,
and much snow fell.
John Scott was with me, and we had a good opportunity: from there I went to Pontefract,
and had a small meeting; it was a deep snow, and very hard frost,
which made it very bad travelling; then to Warnsworth to their Monthly Meeting,
and to Blith in Nottinghamshire, to the funeral of a worthy elder and minister,
where we had a very large company, who were orderly and sober in their behaviour.
At Hansworth Woodhouse, I had a small meeting; and then to Sheffield,
and had two large meetings to pretty good satisfaction; then I went to Chesterfield,
and had a small meeting, and at Mansfield; to Nottingham week-day meeting,
and to Leicester on first-day; here John Scott left me.
The morning meeting was but small, but that in the afternoon was larger,
and both were to pretty good satisfaction.
I was at two or three small meetings in the county,
and then came back to the Quarterly Meeting at Leicester,
where I had a satisfactory time before the business came on,
which was conducted with prudence and love.

From Leicester I went to a general Monthly Meeting,
in a parish called Wigston-two-Steeples on first-day, where the meeting was pretty large,
and to good satisfaction; and that evening came back to a meeting at Leicester,
Benjamin Holme being there also; the meeting was well and comfortable: then to Hinkley,
and had a comfortable time, and to Nuneaton, and had a very large meeting,
which I hope was to good purpose.
I was also at Coventry week-day meeting, and at Atherston;
these meetings were of some service, but not large.
At Warwick on first-day, and had an evening meeting the third-day following,
which were comfortable opportunities:
from there to Henley and had a small evening meeting;
but Friends were too negligent in acquainting their neighbours,
for which I had cause to blame them in several places.
I went to Birmingham, and was at their sixth-day meeting, which was small;
stayed over first-day, and had two meetings to pretty good satisfaction,
with which I was comforted.

On fourth-day following I was at their Monthly Meeting, which was well conducted,
and I had an edifying time,
advising the elders to keep their places as watchmen over the youth,
and to be good examples, and to take care the poor were not neglected,
but assisted in due season.
At Stourbridge we had a large meeting, sundry people came in besides Friends,
and it was of good service: from Bewdley I went to Worcester on first-day,
where the morning meeting was small and heavy,
but that in the afternoon was large and more open.
At Tewksbury I had a very open, edifying opportunity, though but a small meeting;
from there to Cheltenham, where, although I requested notice might be given,
it was neglected, and the meeting was very small.
At Painswick I much pressed that notice might be given to their neighbours;
I likewise gave several notice of the meeting myself,
desiring them to acquaint others of it,
and by this means we had a large and open meeting; I hope it was of good service to some,
and the people were very sober and attentive.
From there to Nailsworth, and although it is a considerable meeting,
if not the largest meeting in the county, it was very small,
yet we had a comfortable time together.

I went to Thornbury on first-day to a funeral, which was very large and open;
from there to Bristol, and was at the third and sixth-day meetings,
and on first-day at two meetings, which were all well and comfortable.
Then back to Thornbury to the funeral of a worthy elder, Thomas Ally:
he was much respected,
which his neighbours manifested by giving their attendance at the meeting;
and many Divine truths were opened, which appeared to be to satisfaction,
there being teachers of sundry professions present, who were very attentive.

Then to Frenchay, a small meeting, and so to Bristol.
I was at the sixth-day meeting, and at a funeral in Temple street,
where many of the people called Methodists came; I stayed over first-day,
and had two meetings, being edified in both,
but the last in Temple street rather exceeded.
I came to Dassil near Shipton Mallet, and had a very satisfactory meeting at Roscombe,
about a mile off, where Baptists, Methodists and other dissenters came,
being all very sober and attentive; and what much contributed to enlarge the number was,
that the Baptist teacher gave notice both to his
own people and the inhabitants of the place,
and gave his attendance himself.
After meeting he came to the Friend`'s house where we dined,
and desired a little conversation, which was readily complied with;
this gave some reason to think he intended to object, but it proved the contrary,
for he was rather too much abounding in praise,
commending what he had heard more than I approved of,
wanting to know whether I had not studied that sermon, as he called it,
before I came there.
My answer to him was, I knew not, when I came there,
whether I should have anything to say or not,
so far was I from having anything provided beforehand.
He said it was a very good sermon, and very suitable for those who heard it.
He was very loving, and so we parted.

From Roscombe I came to Long Sutton and had a small meeting; then to Sherborne meeting,
the smallest I ever was at, or had in that place, and to but little satisfaction;
the smallness of the number was much owing to the lack of notice to the town`'s people;
then to a funeral at Yeovill, of an ancient woman upwards of ninety-five years of age.
A large company of the neighbours attended the corpse, and we had a good time,
the people were very serious, and seemed edified with what was spoken;
from there I came home, on the 16th of the twelfth month, 1747.

I stayed at home and visited the neighbouring meetings until the 2nd of the third month,
1748, and then went towards Bristol Yearly Meeting, but had no meeting till I came there,
except the Monthly Meeting for the north division of Somerset,
and though it was very small,
the affairs thereof were conducted with prudence and judgment.
Bristol Yearly Meeting was to general satisfaction.

From Bristol I went to Bath, and had a small meeting, and so to Pickwick.
I had a small meeting at Corsham, and then went to Bradford on first-day;
the morning meeting was small, but pretty open; that in the afternoon was very large,
and I was concerned to distinguish between the theory
and the practical part of true religion,
and many of the people called Methodists being there, were very attentive;
all was quiet and ended well.
I went back to Pickwick to the men`'s Monthly Meeting,
and the adjourned Quarterly Meeting for the county, it was very small,
which manifested too much neglect among the elders
of the Society for the service of these meetings.

From there I came to the Devizes, Melksham and Market Lavington,
and had a meeting at each place, which were pretty comfortable;
and to Salisbury on first-day, and had two large meetings there:
a great many Methodists came to both meetings,
and were in their appearance and behaviour very agreeable several were partly convinced,
and constantly attended meetings; I had very suitable doctrine to their unsettled states,
and seeking conditions, for they seemed to be inquiring the way to the kingdom,
with their faces thitherwards;
and I hope there will be an increase of our Society in that place.

From Salisbury I went to Alton, and had a small meeting there,
and then to the Yearly Meeting at London, which was very large;
and many hopeful young people of both sexes attended it,
who seemed likely to come up in the places of the faithful already gone,
and of those who are going to their long homes.
My heart rejoiced to find in them a right concern for the cause of the Gospel,
and zeal to keep up the testimony for which their parents joyfully suffered.

We had several acceptable and edifying times,
and the affairs of the meeting were conducted in great love and condescension,
and ended well.
The concluding meeting was very large,
and the only one for which I had a particular concern before I left home,
but I was almost shut out, being so narrowed up for time by those who appeared before me,
that it seemed quite unseasonable to hold the meeting longer,
and not likely to comport with the health of the people.
But yet my age and infirmity considered,
and it appearing doubtful whether I might have the like opportunity,
and being pressed in spirit thereto, I stood up under great fear and weakness;
but I was immediately strengthened by the good word of life, through which I was helped,
and came off beyond my expectation,
being afterwards filled with Divine peace and consolation,
which confirmed me that I was in my place and duty.

I stayed in London over first-day, but had no service in public ministry,
except at the morning meeting of ministers on second-day,
where I was much drawn forth to the ministers,
the meeting being very large with country Friends, and I was much comforted.
Next morning I went with my worthy friend Samuel Waring, by Esher to Alton,
to their first-day meeting, had a meeting at Great Fraile,
and stayed the Monthly Meeting at Alton, which was comfortable and well,
though not much appearance of service.
I went to Rumsey, but was taken ill on the road, and was very much fatigued,
yet next day was bravely recovered, and had a small meeting with the two families,
which was very comfortable.
Then to Ringwood on first-day, and had two open meetings;
next day was their Quarterly Meeting, where their affairs were well conducted;
and the day following was the Yearly Meeting of the
two counties of Southampton and Dorset,
pretty large both in the forenoon and afternoon, and of good service.
Then to Pool to the Quarterly Meeting of Dorsetshire, and I stayed there over first-day,
and had two pretty full meetings, especially the last, which was very large and open;
many Divine truths were clearly and plainly declared to the people,
who by their stillness and attention,
manifested a good disposition to hear and be informed;
I came home the last day of the fifth month, 1748.

[.blurb]
=== An account of my journey to Bristol Yearly Meeting, and to London, Norwich, etc.

I left home the 17th of the second month, 1749, and had a meeting near Shipton Mallet,
to good satisfaction; then to Bristol, and stayed the Yearly Meeting,
where I had some very agreeable opportunities, both in the select and public meetings.
Being clear of that place, I proceeded by Chippenham, Cain and Marlborough,
and had a meeting in each place; then to Newbury, and had two meetings on first-day,
the last pretty large and agreeable; to Reading, Henley, Wickham and Uxbridge,
and had but small meetings, though satisfactory at each place.
From Uxbridge I went to London,
and had some very acceptable times in the select meetings of ministers,
and was largely opened in the public meetings, and I found my concern to grow upon me.

When I was clear I left London in company with John Wilson of Kendal,
and went to Colchester the 27th of the third month,
the Yearly Meeting beginning next day,
and the Quarterly Meeting for the county the day following,
and the select meeting of ministers on the morning of the third-day of the week,
which appeared to me but of little advantage,
but the public meetings were very large and edifying, and ended to good satisfaction.
From there to Manningtree, and had a small meeting, and so to Ipswich,
and was at their weekly meeting, in company with Jane Hoskins, formerly Fenn,
and Elizabeth Hudson, both from Pennsylvania, who had agreeable service among Friends.
I stayed in Ipswich over the first-day, and the last meeting was very large,
being appointed about the fourth hour in the afternoon,
and many of other professions were there, and were very attentive and sober,
and some very much affected and broken into tears,
so that I hope that meeting was of service to many:
I was largely opened on the subject of working out our own salvation,
and the means whereby it is attainable.

From Ipswich I went to Woodbridge,
it being the Quarterly Meeting for the county of Suffolk,
and there being some uneasiness among them.
Friends were concerned to advise them to a reconciliation,
lest they should be wounded by a breach of union and affection.
The meeting, by adjournment, held all day,
and Friends seemed in a good degree of sweetness and condescension one to another,
though a contentious party spirit had got in among them.
Next morning was a meeting of ministers, to good satisfaction;
and then the Yearly Meetings for worship followed, which were exceedingly large,
and with the parting meeting the day following, were all very much to satisfaction.
In the parting meeting I was enlarged on the progressive
advancement in a living and saving faith,
which is the very life of true religion.
We had a small meeting the day following, being their weekly meeting;
then I went to Brand, Edmund Peckover being with me; he had very good service,
and the meeting ended well.
I went back to Woodbridge, and stayed over first-day,
but there were very few besides Friends,
though it was expected the last meeting would have been large,
but for lack of notice it was not.
From there to Layston, Peason-hall and Beccles,
and had a small meeting at each place to tolerable satisfaction;
then to Mutford and Pakefield,
and had as large meetings as the accommodation would permit; what was chiefly lacking,
was room for the people in both places.
At Yarmouth, I had a pretty large meeting to edification; one at North Walsham;
and then to Norwich Yearly Meeting, which was very large.
I was enlarged on the qualification of true ministers, showing,
that without the Divine aid of the Spirit of Truth,
that work could not be rightly performed to the edification of the hearers.

From Norwich I went to Lamas General Meeting, which was very large,
too much for the house to contain, but the people were very quiet; then back to Norwich,
and stayed the week-day and first-day meetings following.
I had ten meetings, though in two of them I had nothing to say,
and they were mostly very large and to good purpose,
being full enough for my natural strength to go through with;
but I was thankful and glad in finding inward strength
and assistance every day to help me through,
to my own comfort and his praise who is God, blessed forever;
and he has given me faith to believe,
that so long as he engages my mind in the work of the ministry,
he will give a fresh supply of strength, both inward and outward,
adequate to his requirings.
From Norwich I came to Mattishal, Windham and Teasborough,
and had a meeting at each place,
the last was enlarged considerably with Friends from Norwich,
but I was under great poverty of spirit in these small meetings.
I went to Diss to a General Meeting;
Friends from Norwich and other distant places came in and attended,
which laid me very low indeed, but I saw in the opening of Divine virtue,
that as the blessing of Christ my master,
upon a small quantity of but plain and low food, gave satisfaction to a multitude,
more than we were likely to be, so I found it best to retire to my gift, and be still.
The meeting was very large, quiet and well,
and I was concerned to set forth the folly and emptiness of all forms of religion,
without the virtue and power of the Spirit of Christ,
and was opened on this subject very largely, much to my own satisfaction,
all being quiet and well.
At Bardwell I had a small meeting, which was pretty well;
then had three meetings at Bury, and one at Rattlesdon, all to pretty good satisfaction.

From Rattlesdon I went to Walden, Royston and Baldock, and so to Hitchin;
had but low times in all these last meetings; from there to Hartford and Ware,
and had tolerably good satisfaction; to Bishop Stortford and Dunmow,
and had a small meeting at each place; and so to Chelmsford on first-day;
things were well and comfortable.
At Billerica I had a small meeting,
and then went with my friend Samuel Arnold to his house, in a parish called Stock,
stayed some days, and came with him to London, being the 20th of the sixth month, 1749.
I was in town several weeks, and my concern grew upon me,
and being filled with Gospel virtue, I had some very agreeable service,
visiting all the meetings in the city, some three or four times,
and the first-day meetings were very full, but week-day meetings were small.

Finding myself easy and clear of the city,
I left it in great peace on the 3d of the eighth month, 1749,
and came to Esher to a small meeting, so to Guildford, Godalming and Alton, Basingstoke,
Baghurst and Andover, and had some very agreeable times,
and in the main was pretty well satisfied.
From there to Salisbury, and had a very full meeting; and to Fording-bridge,
and was at a funeral, where many people attended.
I had good satisfaction in being there,
and left the place in much comfort and inward peace; from there to Ringwood,
and had a pretty large evening meeting to good satisfaction; to Pool, and so to Weymouth,
and had opportunities in both places;
and from there I came home the 2nd of the ninth month, 1749.

From this time it does not appear that our dear friend
kept any account of the meetings he attended,
but upon application to his Monthly Meeting,
they sent us the following brief testimony of his service,
from the time he finished his journal to his decease:

[.embedded-content-document.epistle]
--

[.blurb]
=== From our Monthly Meeting held at Bridport, the 21st of the ninth month, 1755, to Friends at their second-day`'s morning meeting in London.

[.salutation]
Dear friends and brethren.

The journal of our dear and worthy friend, Samuel Bownas,
seems to break off somewhat abruptly, ending the second of the ninth month, 1749,
and we cannot find that he kept any account of his travels,
labours and services in the ministry, from that time to the time of his decease,
which was on the 2nd day of the fourth month, 1753.
During this time he took no long journeys, for being advanced in years, his hands shook,
and his eye-sight failed him much,
but he was very diligent in attending meetings both at home and in the neighbourhood,
for twenty or thirty miles round, as long as his health and strength continued;
and his ministry was lively and powerful to the last,
to the edification and comfort of those who were favoured with it.
His removal was a great loss to Friends, in these parts,
but we have reason to believe it was his great gain, for in his last illness,
which was very short, he seemed quite sensible of his approaching change,
saying that he could not stay long with us,
and hoped that kind Providence would be pleased to take him to himself.

[.signed-section-closing]
Signed in and on behalf of the said meeting, by

[.signed-section-signature]
Joseph Curtis, William Kenway, Robert Curtis, Joseph Hutchins, Tho. Westcombe.

--

[.the-end]
THE END.
