== Chapter III.

[.chapter-subtitle--blurb]
An account of my travels in America the first time.

As advised by the Friends appointed to assist me, I took my passage on board the Josiah,
John Sowden master, bound for West river in Maryland,
and left England about the 24th of the third month, 1702,
and landed in the river Patuxent in Maryland,
about the 29th of the fifth month following.

I visited some meetings in that province; but George Keith being there,
and challenging disputes wherever he came, gave both me and Friends some exercise: to me,
by challenging a dispute without my previous knowledge, in the following terms:

[.embedded-content-document.letter]
--

[.salutation]
To the preacher lately arrived from England.

Sir, I intend to give notice after sermon, that you and myself are to dispute tomorrow,
and would have you give notice thereof accordingly.

[.signed-section-closing]
Sir, I am your humble servant,

[.signed-section-signature]
George Keith.

[.signed-section-context-close]
Dated the first Sunday in August, 1702.

--

He wrote this on occasion of an honest Friend`'s speaking sharply to him,
and giving him the title of an apostate; adding,
she could not pretend to dispute with him,
but a Friend who was to be at their meeting on first-day next, meaning me,
she did not doubt would talk with him.
"`Well then,`" said Keith, "`next monday let him come,
and I will prove him and all the Quakers, unsound in faith and principle.`"
With more of that kind.
The honest woman being warm and zealous for the cause, replied,
"`He will not be afraid of thee, I am sure.`"

The messenger who brought the letter, delivered it in haste, as he was ordered,
to John Faulkner, a young man from Scotland,
who was then storekeeper in B. Bains and Co`'s. employ.
A considerable number of us in company were just
then going to a meeting at Chester in the woods,
some distance from any house, and John insisted for me to write an answer, adding,
"`Keith would call the country together, and make much noise about it,
as if we were afraid, etc., and it was best to nip his expectation in the bud.`"
As we knew nothing of the conference Keith had with the woman Friend two days before,
I wrote to the following effect, being dated the same day:

[.embedded-content-document.letter]
--

[.salutation]
George Keith,

I have received thine,
and think myself no way obliged to take notice of one who
hath been so very mutable in his pretences to religion;
besides, as thou hast long since been disowned,
after due admonition given thee by our Yearly Meeting in London,
for thy quarrelsome and irregular practices, thou art not worthy of my notice,
being no more to me than a heathen man and a publican; is the needful from

[.signed-section-signature]
Samuel Bownas.

--

John Faulkner carried our answer, and we went to our meeting,
being at Chester in Maryland, as aforesaid.
By the time the meeting was fully gathered, John Faulkner came back,
and we had a comfortable meeting: afterwards John Faulkner told us,
George Keith read my letter publicly amongst his company,
appearing very angry at the contents of it; and the company laughed very heartily,
many of them being much pleased with it.
John Faulkner came out of the company, and a substantial planter followed him,
and told him, he had much rather go with him to our meeting,
than to hear George Keith rail and abuse the Quakers;
but being in the commission of the peace, he must,
as Keith was recommended by the bishop of London, show him some respect; adding,
that John Faulkner should bring me to his house to dine the next day;
from which John would have been excused, urging, that as they had a value for me,
Friends would be for bringing me on my way further; adding,
we should incommode his house.
He urged it the more, saying, we should all be welcome.
Accordingly several went with me there, and he was very kind,
giving us an account of George Keith`'s railing against us the day before,
and how disagreeable it was to the assembly.
Keith left a broad sheet printed,
wherein he pretended to prove the Quakers no Christians, out of their own books;
I had an answer thereto in print, which Friends were glad of,
and I left with them several to spread where he left his.

After we had dined, we took our leave and a Friend, my guide,
went with me to a people called Labadies, where we were civilly entertained in their way.
When supper came in, it was placed upon a long table in a large room, where,
when all things were ready, about twenty men or upwards, came in, at a call,
but no woman: we all sat down,
they placing me and my companion near the head of the table,
and having paused a short space, one pulled off his hat,
but not the rest till a short space after, and then one after another,
they all pulled their hats off and in that uncovered posture sat silent,
uttering no words that we could hear, nearly half a quarter of an hour;
and as they did not uncover at once, so neither did they cover themselves again at once;
but as they put on their hats fell to eating,
not regarding those who were still uncovered,
so that it might be about two minutes time or more
between the first and last putting off their hats.
I afterwards queried with my companion concerning the reason of their conduct,
and he gave this for answer,
that they held it unlawful to pray till they felt some inward motion for the same;
and that secret prayer was more acceptable than to utter words;
and that it was most proper for every one to pray,
as moved thereto by the spirit in their own minds.

I likewise queried, if they had no women amongst them?
He told me they had, but the women eat by themselves, and the men by themselves,
having all things in common, respecting their household affairs,
so that none could claim any more right than another to any part of their stock,
whether in trade or husbandry; and if any had a mind to join with them,
whether rich or poor they must put what they had in the common stock,
and if they had a mind to leave the society, they must likewise leave what they brought,
and go out empty handed.

They frequently expounded the Scriptures amongst themselves,
and being a very large family, in all upwards of a hundred men, women and children,
carried on something of the manufactory of linen,
and had a very large plantation of corn, tobacco, flax and hemp,
together with cattle of several kinds.
But at my last going there, these people were all scattered and gone,
nothing remaining of a religious community in that shape.

I left this place and travelled through the country to Philadelphia,
and was there seized with a fever and ague, which held me about thirteen weeks.
I stayed there till the Yearly Meeting came on, which was very large,
but my disorder of the ague would not admit of my being at one meeting.
George Keith with his companions came,
but the disturbance they gave was a considerable advantage to Friends,
and the meeting ended to great satisfaction.

Being recovered and pretty strong, I left Pennsylvania,
and travelled through the Jerseys east and west.
I had given expectation to a Friend, one James Miller in Scotland,
who had a sister married to one of the Barclay family,
that if I came near where she dwelt, I would visit her at his request.
She was a very zealous honest Friend, but her husband joined with Keith,
and left his friends; and on inquiring about her, where she dwelt,
I was told it would be very little out of my way.
A young man offered to be my guide, to pay her a visit; and when we came to the house,
there were sundry priests, with others, met to sprinkle an infant,
the said Barclay`'s grandchild.
The ceremony was over before we got there, we coming from Shrewsbury Yearly Meeting,
where Keith also had been, but gave us no disturbance,
nor did he come to our meeting at all,
but held a meeting at a small distance from us for two days, and then went off.
Our meeting held three days, and was thought to be larger by much,
in expectation that George Keith would be there.
It ended well, and it was said some were convinced.

But to return to my friend Barclay; she was in an apartment by herself,
and gave me a short account of what they had been doing; saying,
"`they have sprinkled the babe, my grandchild, and the ceremony is over,
but they have not yet been to dinner;`" to which she added,
"`my husband will be earnest for thy company: if thou hast freedom to go,
I shall leave thee at liberty, but if thou refusest to go,
they will be ready to report that thou durst not face them;`" adding,
"`I would be pleased with your company,`" meaning me and my companion, "`to dine with me,
but it will be best, I think, for you to dine with them, and I hope,`" said she,
"`the Lord will give you wisdom so to conduct yourselves,
that they may have no just cause to reproach the
principle on your account,`" She had no sooner ended,
than her husband came, and after some compliments, and inquiry about his brother-in-law,
James Miller, and relations at Ury, we were called to dinner,
and by no means would he excuse me: we went in, and the mistress of the feast,
the mother of the babe then sprinkled, would have me sit at her right hand,
and George Keith at her left.

We sat all down, and after a short pause, George Keith stood up,
with all the rest of his company except me and my companion;
we kept our places and hats on, while he repeated a long prayer for the church and state,
bishops, and all the inferior clergy, the queen, and dutchess dowager of Hanover, etc.
The grace being ended, the mistress carved, and would serve me first.
I would have refused, and put it to George Keith, but he refused it likewise:
when she had done helping us and herself,
she began to catechise me in the following manner:

After inquiring about her relations at Ury, in Scotland, and her uncle Miller,
she then desired to know my business in Scotland,
pretending to suppose me a merchant that dealt in linen to sell in England.
I saw her design was to lead me to some unwary answer,
for Keith and the rest to find matter of objection to.
This put me upon my guard, to make reply cautiously.
I freely owned I had no concern in buying or selling any sort of goods.
"`Pray then, sir, what was your call there?`"
I replied, that I thought it my place sometimes to advise my friends and others,
to endeavour so to live, that death, when it comes, might not be a terror to them;
and doubt not but thou wilt count this a good work, and needful to be done.
She readily allowed that it was very needful, and the more so, as the age was very wicked.
Then she proceeded to query the reason of my coming into these parts,
pretending to suppose it was on account of trade, as being a supercargo,
with many trifling and impertinent questions, as when I was in such and such places?
To all which I gave her answers to the same effect as before,
that my business was the same in this country as in Scotland.
Then she proceeded to more trifling questions, as when I landed?
and where, and which way I was going?
All the company at the table gave ear to our dialogue,
which appeared to me very weak in such a learned
company as they thought themselves to be,
and none so much as put in a word between us.
Dinner being ended, I desired to be excused, for that time called me away,
and my friends would wait for me at the ferry, which we had to pass that evening.
Thus Keith and I met and parted.

Then taking leave, I went to see my worthy friend in her own apartment,
with whom we had a short, but very agreeable opportunity:
we took our leave and went to Woodbridge, where the next day we had a meeting;
George Keith preached at Amboy the same day, which places are not far apart.
We often interfered one with the other, but he no more gave any challenge to dispute,
but took another method to put a stop to my travelling, as will appear afterwards.
We came to Long Island, and a meeting was appointed for him to preach within our hearing,
and between the two appointments, there was a very large gathering.
I being young and strong, my voice was plainly heard by the people who were with Keith,
so that they all left his meeting and came to ours, except he that officiated as clerk,
and one William Bradford, who had been a printer for Friends at Philadelphia,
but deserting the Society, Friends took the business from him,
and we had room enough for both meetings, it being in a very large barn.

Some time after,
Keith and the said Bradford agreed that Bradford should
come and try if no advantage could be taken of my doctrine;
accordingly he came, and pulled out of his pocket a small book, with pen and ink,
and steadfastly stared in my face, to put me out of countenance if he could;
but I was above being daunted at that time, though at other times very incident to it.
He opened his book, and wrote about two lines in it, then shut it again,
continuing his staring, to try, as some thought, whether he could not daunt me.
But it was past his skill, for I felt both inward and outward strength,
and Divine power to fill my heart, and my face was like brass to all opposition;
he opened his book, wrote about two lines more, and a little after about two more,
in the whole about six lines on a small octavo leaf;
and after I had done he stood up and said,
"`Will you stand by these doctrines in public that have been now preached?`"
meaning by public dispute.
A worthy Friend, John Rodman by name, desired him to be quiet,
and after meeting was ended he should be answered.
Accordingly the meeting concluded, and he waited for his answer.
To which friend Rodman said, "`William,
thou knowest that what our friend hath been concerned to speak about this day,
are such points as have been by the press argued over and over;
and as the controversy has been some years in the press,
it is therefore needless at this time of day to reduce it to a verbal dispute.`"
But he wanted to hear what I would say to the matter; and I told him,
his questions being more for contention than edification,
I therefore did not think myself obliged to answer them; more especially,
since for his contentions and disorderly walking,
he had been dealt with and advised in a brotherly and Christian spirit to repent,
but his persisting in the same, had obliged his friends to disown him,
and for this reason, I said, I have no more to say to thee on that head.
He turned from me, and in a very angry manner said, "`I should hear of it another way.`"
But I called him back, having something to say on another subject:
which was to deliver some tokens of gold sent his wife, by her sister from London:
this softened him somewhat, he finding the pieces to agree with the letter,
which I requested might be opened before my friends there, and brought him to confess,
that he believed I was a very honest man,
and he was sorry I should be under such a delusion,
as to be in communion with that erroneous people.
But at his return to Keith, they laid their heads together,
and trumped up the following deposition from what he had written, viz:

[.embedded-content-document.legal]
--

I William Bradford, of the city of New York, aged about forty years,
depose upon the holy evangelists.
The 21st of November, 1702, going into the Quakers`' meeting at Nathaniel Pearsal`'s,
deceased, in Hempstead, I heard one Bown, that is lately come out of England, preach,
and the first words I heard him say were "`the Sign of the Cross;`" and thus; Friends,
having gone through the Papist baptism, let us examine the church of England.
Well, what do they do?
Why the bishop lays his hands upon those that have learned the languages,
and ordains them to be ministers.
Well, and what do they do?
Why they baptize the children, the young children,
and sprinkle a little water in their faces, and by this they make the child a Christian,
as they say,
and for so doing the children`'s`' parents must give the priest four pence or a groat:
indeed this is an easy way of making Christians for a groat!
And how do they do this?
Their own catechism tells us the priest says to the child.
What is thy name?
The child answers Thomas, James, Mary, etc.
Well! and who gave thee this name?
The child answers, my godfathers and godmothers in my baptism,
wherein I was made a member of Christ.
This is a brave way to be a member of Christ!
Who would not have a little water sprinkled in their faces?
And what did your godfathers and godmothers then for you?
Answer.
They did promise and vow three things in my name; first,
That I should renounce the devil and all his works,
the pomps and vanities of this wicked world, and all the sinful lusts of the flesh.
Ay! did they so! this is brave.
Well! what did they promise more?
secondly.
That I should keep God`'s holy will and commandments,
and walk in the same all the days of my life.
And yet in contradiction to this, they plead for sin during the term of life,
and say they cannot keep God`'s commandments in this life.
Why! this is strange,
that the godfathers and godmothers should promise what they believe they cannot perform.
And do the godfathers and godmothers thus promise?
Yes, they do.
But this is strange, that their God should need a godfather and godmother.
But Friends, our God is the true and living God; in the first of John it is said,
'`in the beginning was the Word,
and the Word was God.`' But this God had no need of a godfather or godmother.

Well, and what do the Presbyterians do?
Why they baptize their infants also;
but they do not make use of godfathers or godmothers, nor the cross.
They have thrown away that piece of popery.

Next, as to the Lord`'s supper, I shall speak very brief.
Christ says,
'`that which goes in at the mouth defiles not.`' So I shall make this application:
The bread and wine which they receive, and call the Lord`'s supper, goes in at the mouth,
and into the draught, and profits not.
They call it a sign; yea, and an empty sign it is.
But by these ways and forms the hirelings deceive the people.
But we have had sufficient proof of these hirelings in our day;
for they will turn with every wind, and every turn that will answer their priests`' ends,
as we have seen fulfilled largely in our day.

[.signed-section-signature]
William Bradford,

[.signed-section-signature]
Coram nobis Edward Burrows, Joseph Smith, Justices.

[.signed-section-context-close]
A true copy by Thomas Cardall, High Sheriff.

--

Having patched up the above deposition in their own way and manner,
and form of expression, Keith informs, and Bradford was his evidence;
and being at a loss for want of another evidence to confirm Bradford`'s,
without which they could not proceed, they met with a young man who was there,
and Keith got some words out of him, which he said he heard spoken.
They threatened what they would do to him,
if he did not come in for evidence to what he had heard; therefore he was prevailed on,
through fear, to give his evidence on oath,
in the words George Keith had got from him by guile, before the said two justices,
which he did as followeth, although to no purpose.

[.embedded-content-document.legal]
--

Richard Smith, aged about twenty-eight years, deposeth upon the four evangelists;
that on Sunday last, he, this deponent, was at a Quakers`' meeting in Hempstead,
where he heard a man preach, whose name he since understands is Samuel Bowne:
in his preaching, he, this deponent, remembers to have heard him speak these words,
or words to the like effect, viz:
That the church of England in baptism made use of godfathers and godmothers;
but our God is the ever living God, and has no need of a godfather or a godmother:
and further this deponent saith not.

[.signed-section-signature]
Richard Smith.

[.signed-section-signature]
Joseph Smith, Edward Burrows, Justices.

[.signed-section-context-close]
Jurat 24th Die 9bris 1702, coram nobis.

--

[.offset]
Having thus laid a foundation for a prosecution, a warrant was issued;
a copy of which is as under:

[.embedded-content-document.legal]
--

[.salutation]
Queen`'s County, ss.

Joseph Smith, Esq.; E. Burrows, Esq.; justices of the peace for Queen`'s County,
to the high sheriff of the county, greeting:

You are hereby, in her majesty`'s name, strictly charged and commanded,
immediately on the receipt hereof, to attach the body of Samuel Bowne, a Quaker,
if he can be found in your bailiwick, and to bring his body before us,
to answer for such matters of misdemeanour,
as shall on her majesty`'s behalf be objected against him.
And hereof fail not at your peril.
Dated under our hands and seals this 24th November, 1702.

[.signed-section-signature]
Vera Copia Ex. p. Joseph Smith,

[.signed-section-signature]
Thos. Cardall, vic. Ed. Burrows, Justices

--

Thus all things were ready to be put in execution and several substantial people,
not Friends, would have had me gone off, but that I could not do.
On the 29th of the same month, I was at Flushing in Long Island,
it being the Half-yearly Meeting, which was very large, Keith being expected there.
When the meeting was fully set, the high sheriff came with a very large company,
who were all armed; some with guns, others pitchforks, others swords, clubs, halberts,
etc. as if they should meet with great opposition
in taking a poor harmless sheep out of the flock.
The sheriff stepping up into the gallery, took me by the hand,
and told me I was his prisoner.
"`By what authority?`"
said I; he pulled out his warrant, and showed it me.
I told him that warrant was to take up Samuel Bowne, and my name was not Samuel Bowne,
but that Friend`'s name is so, pointing at the Friend by me.
"`We know him,`" said he, "`this is not the man, but you are the man: pray then,
what is your name?`"
"`That is a question which requires consideration, whether proper to answer or not,
for no man is bound to answer to his own prejudice;
the law forces none to accuse himself.`"
Thus we pro`'d and con`'d a little time, and I got up from my seat, and John Rodman,
Samuel Bowne, and sundry other Friends, walked out of the meeting,
it not being proper to discourse there at that time; and they,
on conversing with the sheriff, who in his nature was a very moderate man,
having known Friends in England, easily prevailed on him to stay the meeting,
with all his retinue, and afterwards they would consider what was best to be done.
They willingly laid down their arms on the outside of the door, and came in,
which increased the throng very much: the meeting was silent a considerable time,
and the sheriff`'s company queried of each other privately, so that I heard it,
Why I did not preach; others concluding I should preach no more, being now a prisoner;
that is enough to silence him, said they.
But finding the word like a fire, I could no longer contain, but standing up,
I had a very agreeable service, both to myself and Friends, with the rest of the company;
the sheriff himself, and his company also, spoke well of it:
it was the first day of the meeting, and the seventh of the week.
After meeting was ended, several Friends went to Samuel Bowne`'s,
to consult with the sheriff, and he being very moderate, and in a very good humour,
spoke very mildly and courteously, blaming Keith and Bradford,
and gave liberty that I should stay with my friends until the fifth-day following,
there being two days of the meeting yet to come,
and the funeral of a noted Friend to be the day after it ended.
The meeting increased, and the last was the largest and most open:
it was supposed there might be nearly two thousand people the last day,
but Keith did not come there.

The time for my appearing before the justices being come,
several substantial Friends went with me, and a great crowd of other people came to hear;
but for want of the conveniency of a large hall, which they might have had,
but by the coldness of the season, as was pretended, the justices would not go there,
they were deprived of the opportunity, for want of room, to hear my examination.

There were four justices, viz: Joseph Smith, Edward Burrows,
John Smith and Jonathan Whitehead.
The last was a very moderate man, and endeavoured much to have me set at liberty;
but they had a priest with them,
who tried to put the worst construction on everything I said.
They had shut a man up in a closet, to take in short hand the examination,
that they might peruse the same to their own advantage: but the man was so drunk,
that he lost his papers going home, and a Friend providentially found them,
to their great disappointment and shame:
great inquiry was made about them among the people.

Having done what they thought fit in examining me,
they turned me and my friends out of the room, to consult what was to be further done;
and after a little time, we were all called in, I to receive my doom,
and my friends to hear it.
The clerk, as mouth to the court, said, "`These honourable justices have agreed,
that you must enter into two thousand pounds bail; yourself in one thousand,
and two of your friends in five hundred each, or else be committed to the common jail.`"
I answered, I could enter into no bond on that account.
Here one of the justices queried, if the sum was too large?
I answered, that was nothing to the matter,
if as small a sum as three half-pence would do, I should not do it,
it being a matter of such a nature as I could by no means comply with.
Then the last justice offered to be bound for me, in what sum they required.
But not only I, but all my friends opposed it with all our might giving them,
as well as him, the reason for it.
I went with my kind friend the young justice to his house,
and found very good and kind entertainment, his wife being a very religious,
tender-hearted Friend, and took great care of me.
Next morning we met again, the mittimus was brought in, executed, and was as under:

[.embedded-content-document.legal]
--

[.salutation]
Queen`'s County, ss.

Joseph Smith, Esq.; E. Burrows, Esq.; justices of the peace for Queen`'s County, etc.,
to the high sheriff of Queen`'s County, greeting:

We send you herewithal the body of Samuel Bownas, a Quaker, brought before us this day,
and charged with speaking scandalous lies of, and reflections against,
the church of England as by law established,
and other misdemeanours by him done and spoken at a public assembly in Hempstead,
in this county, on the 21st day of this instant November.
And therefore these are in behalf of her majesty to command you,
that immediately you receive the said Samuel Bownas,
and him safely keep in the common jail of this county,
until that he shall be thence delivered, by the due course of her majesty`'s laws.
Dated under our hands and seals at Jamaica, this 30th of November,
in the second year of the reign of our sovereign lady Queen Anne, of England, etc.
Annoq.
Dom. 1702.

[.signed-section-signature]
A true copy, by Thomas Cardall.

[.signed-section-signature]
Joseph Smith, Edward Burrows, John Smith, Jonathan Whitehead.

--

I was delivered up a prisoner, and my friends left me,
having first got me a good wholesome room, and a very good bed,
taking care that I should want nothing necessary for life.
This continued for three months;
at the end of which a special commission of Oyer and Terminer,
and general jail delivery was given to John Bridges, Esq., chief justice of the province;
Robert Miller, Esq., second; Thomas Willet, John Jackson, and Edward Burrows;
and on the 26th day of the twelfth month.
Bridges and Miller came, attended with much company, in great pomp,
with trumpets and other music before them, to hold the said court;
and about the fourth hour in the afternoon, they in the same order went to court,
which was held in the hall, read their commission, and called over the jury,
to whom they gave an uncommon charge, adjourning till monday the 28th,
at ten o`'clock in the morning.

At the same time the court met and called over the grand jury,
consisting of twenty-two men, and charged them to retire to their chamber,
and the attorney general should send them business.--The court then adjourned.

The grand jury retired, and had a bill of indictment sent them against me,
but I could never get a copy of it first nor last.
I had prepared sundry reasons to set Bradford`'s evidence aside,
which the grand jury had before them, and they were of considerable weight with them.
On the 29th the court met, and the clerk ordered to call over the jury.

Then it was demanded, what business the jury had to lay before the court;
and they presented two bills, one against a woman for some misdemeanour,
and the bill against me, both endorsed ignoramus, upon which the judge was very angry.
The other justices on the bench being mostly Presbyterians,
said little or nothing to the matter, but he addressing himself to the jury, said,
"`Gentlemen, surely you have forgotten your oaths,
and for so doing I could give you some hard names, but at present shall forbear:
is this your verdict touching the Quaker?`"
for they mattered not the other bill, if they could have their ends on me.

[.discourse-part]
The foreman said, "`It is Sir.`"

[.discourse-part]
_Judge._--I demand your reasons, why you have not found the bill against him?

One, whose name was James Clement, a bold man, well skilled in the law, answered,
we are sworn to keep the queen`'s secrets, our fellows and our own;
and for that reason we declare no reasons.

[.discourse-part]
_Judge._--Now Mr. Wiseman speaks, but I tell you, you are not so sworn,
and I could find in my heart to lay you by the heels, and a fine upon your brethren.

Clement replied, he might if he pleased, but when it was done,
it should be exposed with as much expedition as the case would admit in Westminster-hall;
for, adds he, juries,
neither grand nor petty are to be menaced with threats of stocks or fines,
but they are to act freely,
according to the best of their judgments on the evidence before them.

The judge finding he had not children to deal with, altered his manner of address,
and began to flatter, and requested that they would take back both bills,
and resume their considerations upon them.
On this the jury was in judgment divided, but at last they all consented,
and then the court adjourned till nine o`'clock the next day.

The court met according to adjournment, and the jury being called over, the judge said,
"`Foreman, how find you the bills?`"

[.discourse-part]
_Foreman._--As we did yesterday.

[.discourse-part]
On which the judge, in great wrath, charged them with obstructing the course of justice.

[.discourse-part]
"`Why,`" says Clement! "`because we cannot be of the same mind as the court?
We would have you to know, that we desire no other but that justice may take place.`"

The judge now threatened to lay Clement by the heels again.
But Clement, no way daunted, told him he might if he pleased; but if he did,
he should hear of it in another place.

The clerk was now ordered to call over the jury by name singly, to show their reasons,
why they could or could not find the bills.
Sundry of them refused to say any more than, "`That is our verdict.`"
Others again, said, "`How unreasonable, and against law it is,
that the court should endeavour to perjure the jury,
by revealing their secrets in the face of the country.`"
It appeared after the examination of the jury, that seven were for finding the bill,
and fifteen stood firm for the verdict, as signed by the foreman.
This angered the judge to that degree,
that he gave strict orders to keep me more close than before; threatening,
"`As justice cannot be here come at, I will send him to London,
chained to a man of war`'s deck, like other vile criminals,
with his crimes and misdemeanours along with him, which are of the highest nature,
and most dangerous consequence, as tending to subvert both church and state.`"

When an account of this was brought me, I was under a great cloud,
and the power of darkness so very strong upon me, that I desired death rather than life,
fearing that if I was so served, I should be an object of derision to all on board;
and greatly doubting that I should not be able to bear the
suffering which I must undergo in such a case,
with that decency and honour that were requisite in so good a cause.

The Friends left me alone, and I having lost all my faith,
which was still worse than being alone, I thought myself the most wretched among men,
and scarcely able to live under it.
At which time, an honest old man, Thomas Hicks,
who had been chief justice in the province some years, and well versed in the law,
came to visit me, and on my standing up to show my respects to him,
he took me in his arms, saluting me with tears; and thus expressed himself;
"`Dear Samuel, the Lord hath made use of you, as an instrument,
to put a stop to our arbitrary courts of justice,
which have met with great encouragement since his lordship
came here for governor;`" meaning the lord Cornbury,
who oppressed the people sorely.
"`But there never has been so successful a stand made against it as at this time:
and now, they threaten to send you to England chained to the man of war`'s deck.
Fear not, Samuel, they can no more send you there than they can send me;
for the law both here and in England is such,
that every criminal must be tried where the cause of action is; else,
why in England do they remove criminals from one county
to another to take their trials where the offence was committed?
But, after the judgment of the court is given,
you may bring your appeal against that judgment;
and securing the payment of such fees as are commonly allowed in the like case,
they dare not deny your appeal.
The judge frets because he cannot have his end against you;
and the governor is disgusted also,
he expecting to have made considerable advantage by it.
But the eyes of the country are now opened, and you are not now alone,
but it is the case of every subject;
and they will never be able to get a jury to answer their end.
Had the Presbyterians stood as you have done,
they had not so tamely left their meeting-houses to the church;
but that people had never so good a hand at suffering in the case of conscience,
as they have had in persecuting others who differed from them.`"
Here he blamed that people very much,
for being so compliant to all the claims of the governor,
although ever so unreasonable and against law.
This honest man, as if he had been sent by Divine commission,
by his discourse raised my drooping spirits, renewed my faith,
and I was quite another man: and as he said, so it proved.
They could not get the next jury to find the bill against me.

I could never get a copy of the mittimus or indictment against me,
but the judge gave the sheriff orders to keep me more close.
I was accordingly put up in a small room made of logs,
which had been protested against as an unlawful prison two years before;
but that made no difference: I was locked up there, and my friends denied coming to me.
I was now advised to demand my liberty, as a right due by law, and I did so:
but it was denied me, without showing any other reason,
than that I might thank the grand jury for my then confinement.
It was likewise thought proper to lay the case before the governor by petition,
and demand my liberty of him also; which petition is omitted for brevity`'s sake.
But all was in vain,
for they said they were resolved not to be so baffled by the country,
but would bring me to justice.
Keith printed some sheets, pretending to open the eyes of the people, saying,
that I had reproached the church, the ordinances and government;
aggravating the case to the highest.
But what he printed with a design to make my case appear the worse,
had quite the contrary effect upon the people,
it being looked upon as no other than envy and revenge against the Quakers in general,
and me in particular.

The court was adjourned for six weeks;
and finding myself more closely confined than before,
and not knowing when or how it would end,
I began to be very thoughtful what method to take, not to be chargeable to my friends.
As I was full of thought on my pillow about the matter,
it came into my mind to try if I could learn to make shoes;
and applying myself to a Scotch churchman in the neighbourhood, one Charles Williams,
a good natured man, I made a proposal to buy a pair of shoes of him,
cut out for me to make up, and to give him the same price as if made,
desiring him to let me have materials and tools to go on with the work,
and requesting that he would be so kind as to show me how to begin and proceed in it.
I acquainted him with my reason for so doing.
He replied, "`It is very honest and honourable in you: but,`" added he,
"`if one of our ministers were in the like state,
they would think it too mean for them to take up such a practice,
though it were for bread; and your friends perhaps will not like it.`"
However he readily fell in with me, that if I could get my bread with my own hands,
it was most agreeable with Paul`'s practice;
and accordingly next morning he brought me leather cut out,
with materials and tools to work with,
and with his direction I closed one of the upper leathers before he left me,
and he put it on the last for me, and by night I finished that shoe;
which when he came to see, he admired it was so well done,
showing me how to mend the faults in the next, which I finished the next day.
He then supposed I had done something at the trade before, but was mistaken:
and when I would have paid him, he refused it,
and told me he would not take any money of me; so I proposed,
that if he would give the leather, I would give my work;
and so we gave the shoes to a poor honest man who went on errands for us both.
I had then more work of him, and he was so pleased with it,
that he would allow me half pay for making it up,
and was so forward to advance my wages in a few weeks, that unless I would take full pay,
he cheerfully told me, I must look out for another master.
I as pleasantly replied, I did not desire to change.
"`Well then,`" said he, "`I sell the shoes you make,
for as much as any of the like sizes made in my shop.`"

I made such improvement in this business,
that I could in a little time earn fifteen shillings per week,
being three shillings of their money for making a pair of large man`'s shoes,
which was my chief work.
Their shilling was about nine pence sterling.
This new trade was of very great service to me, by diverting both body and mind;
and finding I now could supply my own wants with my own hands,
it gave me great ease indeed: but some Friends were uneasy that I should do it,
supposing it would be to their dishonour; but others were glad,
and thought it an honour to the cause of the Gospel,
and rejoiced with thankful hearts that I succeeded so well.

Going on thus some weeks my kind master came one morning,
and did not bring so much work as before.
I asked him the reason; adding pleasantly, "`Doth my credit sink,
that I have no more work brought?`"
He smiling said?
"`It is not best to trust jail birds too far,
and I am now resolved you shall work no more for me after this I have now brought.`"
"`Why! what is the matter?`"
said I. He added, "`you shall be a master as well as I.`" "`How can that be?`"
said I. He replied, "`you shall have leather of your own,
and by doing that you may get eight-pence, ten-pence, or a shilling a pair,
more profit than you do now.`"
But I told him I had rather work journey-work for him than to do so:
for I knew not how to get leather or other materials, and when I had,
then I was a stranger to cutting out.
"`Trouble not yourself about that,`" said he,
"`for I will do all this for you:`" and so he did with much cheerfulness,
delighting to serve me effectually.

I went on thus for several months, and he came to me every day once or twice,
and was a very cheerful pleasant tempered man,
but too much addicted to take delight in some of his neighbours`' company,
who were disguised with strong liquor, and he would often say,
if you were to continue here, I should overcome it,
and I verily believe should be a sober Quaker.
I told him he must leave the company he frequented; which he not observing,
I heard afterward they proved very hurtful to him.
We had very often serious conversation about religion, and it appeared to me,
he had been favoured with an enlightened understanding, and would confess,
if there was any such thing as preaching Christ truly, it was amongst the Quakers;
for Churchmen, Presbyterians, Independents and others, all preach themselves,
and for their own advantage in this world; so that if there was no pay,
there would be no preaching.
He frequently attended our meetings for a time.

But, to return to the proceedings of the court,
which adjourned from the 4th day of the first month, 1702-3, for about six weeks,
and so continued by adjournments to the last day of the eighth month following.
The occasion of these adjournments was this: Judge Bridges was ill,
and had been for some time declining,
but was expected to be able to attend the service of the court,
and take vengeance on me and the Quakers, none being thought so fit for that work as he;
yet he never did, but died some months before I was set at liberty.

In this time of confinement I had several visits,
two of which were more remarkable than the rest.
The first was by an Indian king, with three of his chief men;
and the other by one John Rogers from New London, who stayed with me about six days.
An abstract of both conferences follows, viz:

I shall first take notice of the conference with the Indian king, as he styled himself;
but his nation was much wasted and almost extinct,
so that he had but a small people to rule.
However, there were some marks of superiority above the other three who attended him,
who showed some regard to him as their sovereign.

This Indian, with his attendants, stayed some time, inquiring the cause of my confinement:
an account of which I gave them as intelligibly as I could,
finding they understood English better than they could speak it.
The conference was mostly between the king and me,
the rest but very seldom putting in a word.

The king asked, "`if I was a Christian?`"
I told him I was.
"`And are they,`" said he, "`Christians too that keep you here?`"
I said they professed themselves to be so.
Then he and the company showed their admiration,
that one Christian could do thus to another.
Then he inquired concerning the difference between me and them.
I replied, it consisted of sundry particulars;
first my adversaries hold with sprinkling a little water on the face of an infant,
using a form of words,
and the ceremony of making the sign of a cross with their finger on the babe`'s forehead,
calling this baptism, and urging it as essential to future happiness: and I,
with my brethren,
can see no good in this ceremony.--Here they talked one with another again,
but I understood them not.
After which they asked me, "`If I thought there was nothing in this ceremony,
of good to secure our future happiness?`"
I said, I see nothing of good in it.
I was right, they said, "`neither do we;`" asking,
"`wherein do you further differ from them?`"
I proceeded, that they held it needful to take, at certain times,
a piece of bread to eat, with a small quantity of wine to drink after it is consecrated,
as they call it, which they pretend to do in remembrance of Christ our Saviour,
urging this as necessary to our future happiness, as the former,
calling this the Lord`'s supper.
He told me, they had seen both these ceremonies put in practice by the Presbyterians,
but could not understand, that if it was a supper,
why they used it in the middle of the day;
but they looked upon them both as very insignificant to the end proposed; saying,
"`The Great Spirit looked at the heart, how it was devoted,
and not at these childish things.`"
Asking, "`wherein do you differ further from them?`"
I proceeded, that they held it lawful to kill and destroy their enemies;
but we cannot think that good and right in us;
but rather endeavour to overcome our enemies with
courteous and friendly offices and kindness,
and to assuage their wrath by mildness and persuasion,
and bring them to consider the injury they are doing to
such as cannot in conscience revenge themselves again.
He assented that this was good, "`but who can do it,`" said he;
"`when my enemies seek my life,
how can I do other than use my endeavour to destroy them in my own defence?`"
My answer was,
that unless we were under the government of a better spirit than our enemies,
we could not do it; but if we are under the government of the good Spirit,
which seeks not to destroy men`'s lives, but to save them,
and teaches us to do good for evil, and to forgive injuries,
then we can submit to Providence,
putting our trust in the great God to save us from the violence and wrath of our enemies.
The king said, "`Indeed this is very good;
but do you thus when provoked by your enemies?`"
I said, many of our friends had done so, and been saved from the rage of their enemies,
who have confessed Friends to be good men.
"`Ay,`" said he, "`they are good indeed; for if all came into this way,
there would then be no more need of war,
nor killing one another to enlarge their kingdoms,
nor one nation want to overcome another.`"

I then asked him if this was not a right principle;
and what would much add to the happiness of mankind?
They all four said, "`it was very good indeed;
but feared few would embrace this doctrine.`"
I said all things have their beginning, and it is now our duty to embrace this truth,
hoping that others by this example may do the same.
They lifted up their eyes as a token of their assent,
showing by their words their desire that this good spirit might prevail in the world:
"`Then,`" said they, "`things will go well.
But wherein,`" added he, "`do you differ more from them?`"
I said we held it unlawful to swear in any case; but our adversaries did not.
I found they had not any notion about oaths, and so they dropped it,
being desirous of introducing another subject;
for having observed our friends`' behaviour in not pulling off their hats as others did,
they wanted to know our reasons for it.
I said uncovering our heads was a token of honour which
we paid to the great God in our prayers to him;
and we thought any homage equal to it ought not to be given to any of his creatures.
They said, "`It is all very good.`"
Then we sat silent some time; and I asked them what they thought of the great God?
One of them took a piece of wood coal from the hearth, like charcoal half burnt,
and made a black circle therewith on the hearth-stone, and said,
"`they believed the great God,`" or Monettay, as they then called him, "`to be all eye,
that he saw everything at once; and all ear, that he heard everything in like manner;
and all mind, that he knew all things, and nothing could be hid from his sight, hearing,
or knowledge.`"

I asked what they thought of the devil?
or bad Monettay, as they called him.
They said they did not look upon his power independent of the good Monettay,
but that what he did was by permission;
nor indeed did they think he had any power at all
but what he was suffered to exercise over Indians,
to bring about some good designs of the good Monettay for their advantage,
to reclaim them when they were bad, and had displeased the good Monettay.
They believed the good Monettay had all power, and employed his servants or angels,
as we term them, to execute his will.
The Indian who made the circle,
described four small circles on the edge of the great one,
and showed their opinion how the little gods were
employed to chastise the Indians when bad,
and to comfort and encourage them in good:
they likewise supposed the four small circles to
answer to the four quarters of the world;
that they had inferiors under them again to execute their
will when they received a commission from that great Mind;
but that all derived their power from the Supreme eye, ear, and mind;
demonstrating their meaning thus: Supposing the Indians bad, the good Monettay sees it,
and gives orders to that in the north, and by him to them under him, and by hard frosts,
great snows, and cold winds in the winter, we are very much afflicted with want of food,
and cold; and in the summer,
either extreme heat or wet prevents the fruits of the earth from coming to perfection,
until we are made humble and good.
Then we pray for relief, and commission is given to the Monettay in the south,
and by him to them under him, whereby we have warm winds,
and pleasant rains in the spring, that makes deer easy to be taken, and fat, etc.
And in the summer, fruitful good weather, neither too wet nor too dry.
Thus they account for all distempers, and common calamities by sickness or famine;
and on the other side, health and plenty, etc.
In like manner, when two nations are both wicked,
they are stirred up to destroy each other, either by the devil,
or by some of these Monettays by him employed, etc.

I then proceeded to query, what thoughts they had of a future state after this life:
first desiring to have their opinion,
whether they did not think they had a part in them that would never die?
which they readily granted, and gave me their opinion,
what both the state of the good and bad Indians would be in the other world;
that the good Indians would go into the south and south west,
where it was very warm and pleasant,
and plenty of all things both for pleasure and profit.
Supposing that they should have the delight of enjoying the comforts of eating, drinking,
hunting, and all other pleasures they enjoyed here,
in a more agreeable way to please their desires, than ever they could in this world.
They described heaven as best suited their natural senses,
endeavouring to Instil into their youth, as they said, principles of virtue and justice,
that when they die, as to this world,
they may be fit and worthy of this good country or heaven,
where it always is serene and quiet, no night nor winter in this pleasant country;
but all things are plenty, very good, well and comfortable.
But then, the wicked and bad Indians, when they die, go into the north and north west,
a country extremely cold, dark, and unpleasant; with no sunshine.
They endeavour to get something to satisfy their hunger, but cannot,
for the deer are very poor, and they cannot catch them.
In this extremity they desire to die, but cannot;
nor can they find any means to put an end to this miserable and wretched life,
but they must continue in sorrow and trouble without any hopes of end.
Thus they described their thoughts of a future state, either in heaven or in hell,
according to their notions of both.

I then turned my discourse and asked them,
what they thought of a good Spirit who was present with them in their minds?
finding they had no notion of Christ, as to his bodily appearance.
They readily acknowledged that a good Spirit attended them, and did reprove,
or make them sorrowful when they did badly.
They likewise believed the bad Monettay, or devil, persuaded them in their minds to evil,
and the more they strove against the devil, and prayed for strength,
by and from the good and great Monettay,
the more they prevailed over these wicked temptations of the devil in their own minds,
which had, they said, no power to lead them into evil, but by their own consent;
nor could do them any hurt if they did not yield to his alluring and deceitful temptations.
I further inquired, if all the Indians were much of the same mind in these matters?
But they could not answer me.

I inquired whether any amongst them were looked upon as instructors, more than others?
They said no,
but the head of every family ought to do his best endeavours to instruct his family,
but it was neglected;
yet they retained the practice of all coming together once in a year,
and the elder advised the younger, what their parents and elders had told them,
and thus they transmitted the knowledge of former things from one generation to another,
by having them repeated in these assemblies.

Here our conference ended: and I treated them with some refreshment,
which they thankfully received; and we parted in great friendship and love,
after a stay of one night and almost two days.

Some weeks after this, John Rogers, a seventh-day Baptist, from New London,
in New England, came nearly two hundred miles on purpose to visit me.
He was the chief elder of that society, called by other people Quaker Baptists,
as imagining, though falsely,
that in their principles and doctrines they seemed one with us;
whereas they differed from us in these material particulars, viz:
about the seventh-day sabbath, and in making use of baptism in water to grown persons,
after the manner of other Baptists,
and using the ceremony of bread and wine as a communion,
and also of anointing the sick with oil: nor did they admit of the light of Christ,
or manifestation of the spirit, only to believers; alleging Scripture for the whole.
They bore a noble testimony against fighting, swearing, vain compliments,
and the superstitious observation of days,
for which John Rogers had endured sundry long imprisonments,
and other very great sufferings besides, both of body and goods.
He was a prisoner when William Edmundson was in that country,
see his journal page ninety,
and had by sufferings obtained so complete a victory over his opposers,
that now they took no notice of him, he might do and say what he pleased.
He thought himself,
that he had carried his opposition to the observation of the first-day as a sabbath,
a little too far at times, so that he would do all sorts of work, yea,
drive goods or merchandize of sundry sorts in a wheelbarrow,
and expose them to sale before the pulpit,
when the priest was about the middle of his discourse, if he was not hindered,
which some times, though but seldom, happened; and would do any other kind of labour,
letting the people know his reason for so doing, was,
to expose their ignorance and superstition in observing that day,
which had more of law than Gospel in it, for Christ was the true sabbath of believers;
withal adding, that he was raised up for that very end.
They admitted women to speak at their meetings,
believing some qualified by the gift of the spirit for that work,
and sometimes they had but very little said in their meetings,
and sometimes were wholly silent, though not often; for they admitted any one,
who wanted information concerning the meaning of any text, to put the question,
and it was then expounded and spoken to, as they understood it,
any one being admitted to show his dissent, with his reasons for it: "`thus,`" said he,
"`we improve our youth in Scripture knowledge.`"
I asked him if they did not sometimes carry their difference in sentiment too far,
to their hurt?
He acknowledged there was danger in doing so,
but they guarded against it as much as they could.

He gave me a large account of the conference he had with William Edmundson, and told me,
that nothing ever gave him so much trouble and close uneasiness,
as his opposing William Edmundson at that time, desiring me,
if I lived to see William Edmundson,
to acquaint him with the sincere sorrow he had upon his mind for that night`'s work.

At my return, I acquainted William Edmundson therewith, who desired me,
if I lived to see him again,
to let him know that it was the truth to which William Edmundson bore testimony,
and therefore it was no wonder that he was so much
troubled for his foolish attempt to oppose it.

He gave me an account of his convincement and conversion, which was very large,
and although at first it was agreeable and very entertaining,
yet his spinning it out so long, made it disagreeable,
for he stayed with me five or six days,
and it was the greatest part of his discourse all that time,
although I several times started other subjects, which he would soon get off,
and go on about his own experiences.

I queried why he was so very stiff about the seventh-day, and whether,
upon a mild consideration of the opposition he gave about their sabbath,
it was not by him carried too far?
He acknowledged,
that he did not at first see clearly into the true meaning of the sabbath,
but that the provocations he met with from the priests,
who stirred up the people and mob against him,
might sometimes urge him further than he was afterwards easy with, in opposing them;
but when he kept his place, he had inexpressible comfort and peace in what he did;
adding, "`that the wrath of man works not the righteousness of God.`"

I queried with him, why they kept to the use of bread and wine,
and plunging or dipping into water,
since he taught his people to put no confidence in those ceremonies,
by supposing any virtue or holiness in them?
He replied that they did it for the sake of those who were weak in faith; adding,
that if our friends had taken those two sacraments along with them,
they would have driven all before them.
This led us into a long conference, the substance of which was to the effect following.

He spoke much of his satisfaction and unity with George Fox, John Stubbs, John Burnyeat,
and William Edmundson, as the Lord`'s servants,
with others of the first visitors of that country, whom he knew to be sent of God,
and that they had carried the reformation further
than any of the Protestants did before them,
since the general apostacy from the purity both of faith and doctrine.
The church of England did nothing in the end but made an
English translation of the Latin service used before;
the Presbyterians dissented, and the Independents also,
but came not to the root of the matter; the Baptists dissented from all the other three,
but went not through.

Though I could not wholly agree with him in his assertions,
I queried if he thought that all these several steps,
as of the English church from popery,
the Presbyterians and Independents from the English church,
and the Baptists from all three of them, had not something of good in them?
I mean whether the first concerned in dissenting from popery,
though they afterwards rested too much in the form of worship in the Episcopal way,
had not the aid of Christ`'s spirit to assist them in their dissent?
And so for all the rest.
This he readily granted to be a great truth; and also allowed that the first reformers,
actuated by Divine light, and being faithful to what was made known to them,
had their reward;
and their successors sat down in the form in which their predecessors left them,
but did not regard that power and life by which they were actuated,
and so became zealots for the form, but opposed the power.
This, said he, is the true cause of the several steps of dissent one from another;
and the reason why there is so little Christian love,
and so much bitterness and envy one against another, is their sitting down contented,
each in their own form, without the power, so that they are all in the same spirit,
acting their part in the several forms of worship in their own wills and time,
not only opposing the Spirit of Truth, but making it the object of their scorn,
and those who adhere to it the subject of their reproach, contempt and envy;
and this is the foundation of persecution.
But we shall, said I, digress too far from what we had in view:
thou allowest the aforementioned Friends to be servants of Christ,
and guided by his word,
and that they advanced the reformation higher than any had done before them;
and it is plain they had a concern to lay aside fighting, swearing, vain compliments,
as well as baptism and bread and wine, these two sacraments, as you call them;
and as you continue in the practice of them, it must be in your own will,
and not in the will of God, by thy own confession.
"`How dost thou,`" said he, "`make that out?`"
Thus, said I; first, thou allowest those Friends to be true ministers,
and declarest thy unity with them as such,
and they had a concern to draw people`'s minds from
depending upon these shadows to trust in the substance:
now how could this be so effectually done,
as by persuading the people to discontinue the use of those shadows?
For whilst they used them,
though at the same time they were told there was nothing in them,
yet weak minds would still retain some regard, as though they had some real good in them,
when in truth there was none.
But if our friends had a concern from the Lord to do this,
how canst thou in reason suppose,
that by the same spirit you had a concern from the
Lord to continue in the performance of them,
unless thou wilt suppose contradictory principles
and doctrines proceed from that good Spirit;
which I hope is far from thy thoughts.
"`Yea,`" said he, "`so that is indeed.`"
Adding, "`we do not act so, for we say as you do,
that there is nothing in these ceremonies but a sign;
it is the power of an endless life that we persuade them to seek for in themselves,
and not to look on these as any advantage in a spiritual sense at all.`"
Then, said I, you had better do as we do, wholly lay them aside;
remember the brazen serpent that proved a snare to Israel:
but he would not yield to this.
I asked him, if he thought either of these ceremonies of more use than the other?
"`No,`" replied he; "`set one aside and set both,
for there is no more virtue in one than the other.`"
I then queried with him,
if ever he had seen a small treatise entitled the "`Doctrine
of Baptisms,`" written in Cromwell`'s time by William Dell?
He said he had never heard of such a book.
I had it by me, and turned to the last paragraph in the preface,
where the author in a prophetic way has these words,
"`But because I see this present generation so rooted
and built up in the doctrines of men,
I have the less hope that this truth will prevail with them;
and therefore I appeal to the next generation,
which will be further removed from these evils, and will be brought nearer to the word;
but especially to that people whom God hath and shall form by his Spirit for himself,
for these only will be able to make just and righteous judgment in this matter,
seeing they have the Anointing to be their teacher, and the Lamb to be their light.`"

Having read this paragraph, he took the book and read it to himself,
and was silent till I observed to him that the author plainly pointed at our people.
He allowed there was reason so to think.
By this time it was late, and I desired him to take the book, read and consider it,
and let me have his thoughts the next day.
So for that time we parted, and he came not till late in the afternoon the next day,
although he lodged hard by the place of my confinement.
When he came, he told me he had read it carefully and considered it closely,
confessing that it was the language of the Spirit, and true doctrine.
I told him,
now I hoped he was satisfied that it was most safe for them to lay these shadows aside,
and labour to bring their people to the substance.
He allowed that it might be proper to do so.
"`But,`" added he, "`it must be done with great care and tenderness,
lest some should be hurt by it.`"
To which I replied,
they would be more in danger of being hurt by following those shadowy observations,
in which they could have no benefit,
and continuing in them might be a means to lead them into superstition and idolatry,
and make them sit down and take their rest in shadows, and seek no further.

Having said what we could, both of us dropped it by consent; and after some short pause,
for he could not long be silent, we fell on the subject of election and reprobation,
he asserting that saving light and grace was only given to the elect, or true believers,
and the rest were blinded.
I alleged the contrary; that an offer of Divine love was made to all,
but all did not make good use of it: so to argument we went,
and I requested the reason for his belief in this doctrine;
desiring him first to explain whether he thought that reprobates were from their
cradles or births so fixed that no means ordained could alter them?
He paused some time, and at last said, "`All things with God are possible;
but from the doctrine of Paul, Rom.
ix. it plainly appears,`" says he, "`to be so, and that God is glorified by both,
as in the case of Pharaoh.`"
I replied, Pharaoh`'s case could not properly be adapted to this doctrine,
because it was in itself peculiarly intended for the convincing of the Egyptians,
as well as the rest of mankind; that he (God) was the only all powerful God,
worthy of obedience, and that the life and power of kings was with him;
and to confirm that weak people the Jews,
that if they leaned upon God who had done all this before their eyes,
they need not fear the wrath of kings,
though accompanied with strong and numerous armies; for God, who had chosen them,
could soon overthrow their enemies,
and save them by a mighty deliverance from their rage and wrath.
But how this can be brought to support election and reprobation as it is now understood,
and preached up by some pretended teachers, I see not;
I therefore desire that thou wouldst explain it as thou understands it.
He then proceeded as follows; first calling for the book, and turning to the text, Rom.
ix. he began at the tenth verse, and went on, expounding very strongly and undeniably,
in his own view, to the twenty-first verse,
continuing his exposition to an uncommon length.
I heard with a profound silence, and he became silent too at last,
and we sat in silence some time, and then I spoke to the effect following:
that it appeared to me the twenty-second verse took off much of
the edge of what he had said with respect to reprobation;
which I read, and he confessed it did pretty much so.
I further added, that the doctrine of election and reprobation,
in the way it is now expounded by thee, is very injurious,
in reflecting on the infinite mercy of God,
and directly opposing the chief end of the Gospel, and of the coming of our Saviour,
"`who tasted death for every man,`" and offers life by his good Spirit and grace to all.
Besides thy way of expounding the apostle in this epistle,
makes him quite contradict himself in other places,
where he clearly sets forth the love of God by and through Christ,
to be universally offered to both Jews and Gentiles, in order to salvation.

And last of all, as thou hast explained thyself now upon this doctrine,
thou renders that great duty of prayer almost impertinent, if not quite useless,
with all other religious endeavours, etc.;
so that if thou canst not make it out otherwise than this, I may, I think,
without any breach of charity,
conclude thee unsound in thy faith and doctrine of
the Gospel of our Lord and Saviour Jesus Christ,
who died for all men,
and was by his apostle preached as the Saviour of the world to both Jews and Greeks.
We must expound Paul in Rom.
ix. after another manner, so as to reconcile Paul with himself, where he plainly shows,
God wills all men to be saved, and to come to the knowledge of the Truth,
as in the second of the first of Timothy, and abundantly elsewhere,
that we have already touched upon: but if thou wilt give me leave, without interruption,
I will give thee my thoughts on this subject, which in short are these, viz:
It is beyond all doubt or question with me, that God wills all men to be saved:
and to complete his will and offers of salvation to all,
he has ordained the means to procure the end by his own Son,
"`who tasted death for every man,`" whereby all have it put into their power,
as free agents, to make choice for themselves, by applying to the means ordained by God,
through his Son our Lord Jesus Christ, for obtaining that which he has willed for them,
viz: salvation.
If this is true, as the Scriptures assert,
and our own experience confirms it to ourselves, then it follows,
that all who are diligent, through the obedience of faith,
endeavouring to make their calling and election sure,
by applying to the means ordained of God, viz:
the grace and truth that come by Jesus Christ,
for obtaining that which he has willed for them,
we may safely conclude all in this state, to be the elect of God in Christ.
But all who, contrary to this, neglect and slight, nay,
rebel against the inward convictions of grace and truth in their own minds,
which is the only guide and rule for doing better,
and continue therein until they are hardened in their sins and wickedness,
being given up to a reprobate mind, having their consciences seared as with a hot iron,
are past feeling any remorse for their ungodly deeds.
These I take to be in a reprobate condition, and this reprobation is of themselves,
they having chosen it;
for they had the offers of the same grace and truth to assist them to do better,
as the elect had, but would not apply themselves thereto, but did willfully reject it.
All this thou knowest may be fairly proved by the Scriptures, and thou canst, I think,
do no otherwise than allow it to be conclusive to decide this point; for it is plain,
the first are the children of God, made so by their co-working with the Spirit of Christ;
and the other are reprobates and children of antichrist,
made so by their rebellion against the Spirit of Truth,
and obedience to the spirit of error: and here I conclude with the apostle`'s words,
"`What if God, willing to show his wrath, and make his power known,
endured with much long suffering the vessels of wrath,`" by their own rebellion,
"`fitted to destruction?
Here we closed the discourse;
and now I shall go on with my imprisonment and clearing from the same.

About the beginning of the eighth month, 1703,
the sheriff had an order to call eighteen men for a jury,
to try their success a second time:
but whether they went upon the old indictment or a new one, I could not understand,
though it was thought by some of the last jury,
to be the same indictment that the first jury went upon;
but I never was admitted to see it.
The sheriff had private instructions to get such men put into the jury,
as they thought would answer their end, which he showed me with abhorrence, assuring me,
he would never do it; so the jury was fairly named,
and they made no great matter about it, but in a short time,
as their predecessors had done, came in with their bill, signed ignoramus;
which gave some of the lawyers cause to say, in a jocular way,
they were got into an ignoramus country.

This was on the 2nd day of the ninth month, and the court adjourned to the next day,
at which time I was had into court; which I was told,
was not regular or lawful to bring a man to the bar
who had nothing laid to his charge by his peers,
the grand inquest.
I was asked, if I had anything to offer to the court?
I desired my liberty and reparation for the wrong done me in taking it from me, etc.
The judge told me, I might have my liberty, paying my fees.
I replied, that I was informed there were no fees due, as the case then was,
according to law; but if there had been, I should not pay any,
it being to me a matter of conscience.
The judge said, he believed so, and smiled, speaking something to those near him,
that was not heard by me: however I was set at liberty by proclamation;
and a large body of my dear friends, from all parts of the island,
came to see me cleared, and had me away with them in a kind of triumph,
being not a little glad that I came off so honourably;
and even the country people who were not Friends were there in abundance,
and rejoiced exceedingly at my enlargement.
